load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync",
    srcs = [
        "sync.go",
        "sync_mock.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/lib/sync",
    visibility = ["//visibility:public"],
)

go_test(
    name = "sync_test",
    srcs = ["sync_test.go"],
    embed = [":sync"],
)
