load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(
    [
        "mod.rs",
        "ledger.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_services_capital",
    srcs = [
        "mod.rs",
        "ledger.rs",
        "double_entry_repo.rs",
        "double_entry_ledger_service.rs",
        "double_entry_ledger_test.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:ledger_prost",
        "//src/proto:ledger_tonic",
        "//src/server/common:server_common",
        "//src/server:server_lib",
        "@crates//:chrono",
        "@crates//:sqlx",
        "@crates//:tonic",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "server_services_capital_unit_test",
    size = "small",
    crate = ":server_services_capital",
    edition = "2024",
    env = {
        "RUST_TEST_THREADS": "1",
    },
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
