load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "checkpointer",
    srcs = [
        "checkpointer.go",
        "pg_saver.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/checkpointer",
    visibility = ["//visibility:public"],
    deps = ["//srcs/server/db"],
)

go_test(
    name = "checkpointer_test",
    srcs = ["checkpointer_test.go"],
    embed = [":checkpointer"],
    deps = ["//srcs/server/db"],
)
