load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "integration_test",
    srcs = ["integration_test.go"],
    data = ["//srcs/server/agents/builtin:ohc-builtin-agent"],
    tags = ["integration"],
    deps = [
        "//srcs/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
