load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "growth",
    srcs = [
        "handler.go",
        "router.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/api/growth",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/analytics",
        "//services/growth",
    ],
)

go_test(
    name = "growth_test",
    srcs = ["handler_test.go"],
    embed = [":growth"],
    deps = ["//lib/analytics"],
)
