load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "growth",
    srcs = ["referrals.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/api/growth",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/telemetry",
        "@io_opentelemetry_go_otel//:otel",
    ],
)

go_test(
    name = "growth_test",
    srcs = ["referrals_test.go"],
    embed = [":growth"],
)
