[package]
name = "server_integrations_distributed_lock"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
redis = { version = "0.27.6", features = ["tokio-comp"] }

[lib]
path = "mod.rs"
