load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tiers",
    srcs = [
        "models.go",
        "service.go",
        "api.go",
    ],
    importpath = "onehumancorp/srcs/server/tiers",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tiers_test",
    srcs = ["service_test.go", "api_test.go"],
    embed = [":tiers"],
    deps = [
    ],
)
