load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kairos",
    srcs = ["worker.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/agents/kairos",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
    ],
)

go_test(
    name = "kairos_test",
    srcs = ["worker_test.go"],
    embed = [":kairos"],
    deps = [
        "//srcs/server/db",
        "@com_github_stretchr_testify//assert",
    ],
)
