load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_services_intake",
    srcs = glob(["*.rs"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/common:server_common",
        "@crates//:axum",
        "@crates//:chrono",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:tracing",
        "@crates//:uuid",
    ],
)
