load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "nats",
    srcs = ["nats.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/integrations/nats",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/proto:hub_go_proto",
        "//srcs/server/telemetry",
        "@org_golang_google_protobuf//proto",
        "@com_github_nats_io_nats_go//:nats_go",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "nats_test",
    srcs = ["nats_test.go"],
    embed = [":nats"],
    deps = [
        "@com_github_stretchr_testify//assert",
    ],
)
