// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interop.proto

package interoppb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Mode specifies the execution environment.
type DeploymentMode int32

const (
	DeploymentMode_MODE_UNSPECIFIED DeploymentMode = 0
	DeploymentMode_MODE_CLOUD       DeploymentMode = 1
	DeploymentMode_MODE_STANDALONE  DeploymentMode = 2
)

var DeploymentMode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	1: "MODE_CLOUD",
	2: "MODE_STANDALONE",
}

var DeploymentMode_value = map[string]int32{
	"MODE_UNSPECIFIED": 0,
	"MODE_CLOUD":       1,
	"MODE_STANDALONE":  2,
}

func (x DeploymentMode) String() string {
	return proto.EnumName(DeploymentMode_name, int32(x))
}

func (DeploymentMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{0}
}

// StateHandoff carries mission context across the mode boundary.
type StateHandoff struct {
	MissionId            string         `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	TenantId             string         `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SourceMode           DeploymentMode `protobuf:"varint,3,opt,name=source_mode,json=sourceMode,proto3,enum=ohc.interop.DeploymentMode" json:"source_mode,omitempty"`
	TargetMode           DeploymentMode `protobuf:"varint,4,opt,name=target_mode,json=targetMode,proto3,enum=ohc.interop.DeploymentMode" json:"target_mode,omitempty"`
	TimestampMs          int64          `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	StateSnapshotJson    []byte         `protobuf:"bytes,6,opt,name=state_snapshot_json,json=stateSnapshotJson,proto3" json:"state_snapshot_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StateHandoff) Reset()         { *m = StateHandoff{} }
func (m *StateHandoff) String() string { return proto.CompactTextString(m) }
func (*StateHandoff) ProtoMessage()    {}
func (*StateHandoff) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{0}
}

func (m *StateHandoff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateHandoff.Unmarshal(m, b)
}
func (m *StateHandoff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateHandoff.Marshal(b, m, deterministic)
}
func (m *StateHandoff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateHandoff.Merge(m, src)
}
func (m *StateHandoff) XXX_Size() int {
	return xxx_messageInfo_StateHandoff.Size(m)
}
func (m *StateHandoff) XXX_DiscardUnknown() {
	xxx_messageInfo_StateHandoff.DiscardUnknown(m)
}

var xxx_messageInfo_StateHandoff proto.InternalMessageInfo

func (m *StateHandoff) GetMissionId() string {
	if m != nil {
		return m.MissionId
	}
	return ""
}

func (m *StateHandoff) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *StateHandoff) GetSourceMode() DeploymentMode {
	if m != nil {
		return m.SourceMode
	}
	return DeploymentMode_MODE_UNSPECIFIED
}

func (m *StateHandoff) GetTargetMode() DeploymentMode {
	if m != nil {
		return m.TargetMode
	}
	return DeploymentMode_MODE_UNSPECIFIED
}

func (m *StateHandoff) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

func (m *StateHandoff) GetStateSnapshotJson() []byte {
	if m != nil {
		return m.StateSnapshotJson
	}
	return nil
}

// HealthPing is broadcasted across the Swarm to check connectivity.
type HealthPing struct {
	SourceNodeId         string         `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	CurrentMode          DeploymentMode `protobuf:"varint,2,opt,name=current_mode,json=currentMode,proto3,enum=ohc.interop.DeploymentMode" json:"current_mode,omitempty"`
	TimestampMs          int64          `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HealthPing) Reset()         { *m = HealthPing{} }
func (m *HealthPing) String() string { return proto.CompactTextString(m) }
func (*HealthPing) ProtoMessage()    {}
func (*HealthPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{1}
}

func (m *HealthPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthPing.Unmarshal(m, b)
}
func (m *HealthPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthPing.Marshal(b, m, deterministic)
}
func (m *HealthPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthPing.Merge(m, src)
}
func (m *HealthPing) XXX_Size() int {
	return xxx_messageInfo_HealthPing.Size(m)
}
func (m *HealthPing) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthPing.DiscardUnknown(m)
}

var xxx_messageInfo_HealthPing proto.InternalMessageInfo

func (m *HealthPing) GetSourceNodeId() string {
	if m != nil {
		return m.SourceNodeId
	}
	return ""
}

func (m *HealthPing) GetCurrentMode() DeploymentMode {
	if m != nil {
		return m.CurrentMode
	}
	return DeploymentMode_MODE_UNSPECIFIED
}

func (m *HealthPing) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

// HealthAck acknowledges receipt of a HealthPing.
type HealthAck struct {
	SourceNodeId         string   `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId         string   `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TimestampMs          int64    `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthAck) Reset()         { *m = HealthAck{} }
func (m *HealthAck) String() string { return proto.CompactTextString(m) }
func (*HealthAck) ProtoMessage()    {}
func (*HealthAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{2}
}

func (m *HealthAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthAck.Unmarshal(m, b)
}
func (m *HealthAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthAck.Marshal(b, m, deterministic)
}
func (m *HealthAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthAck.Merge(m, src)
}
func (m *HealthAck) XXX_Size() int {
	return xxx_messageInfo_HealthAck.Size(m)
}
func (m *HealthAck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthAck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthAck proto.InternalMessageInfo

func (m *HealthAck) GetSourceNodeId() string {
	if m != nil {
		return m.SourceNodeId
	}
	return ""
}

func (m *HealthAck) GetTargetNodeId() string {
	if m != nil {
		return m.TargetNodeId
	}
	return ""
}

func (m *HealthAck) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

// Dispatches a background job to the builtin agent.
type JobDispatch struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId             string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActionName           string   `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	PayloadJson          []byte   `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TimestampMs          int64    `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDispatch) Reset()         { *m = JobDispatch{} }
func (m *JobDispatch) String() string { return proto.CompactTextString(m) }
func (*JobDispatch) ProtoMessage()    {}
func (*JobDispatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{3}
}

func (m *JobDispatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDispatch.Unmarshal(m, b)
}
func (m *JobDispatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDispatch.Marshal(b, m, deterministic)
}
func (m *JobDispatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDispatch.Merge(m, src)
}
func (m *JobDispatch) XXX_Size() int {
	return xxx_messageInfo_JobDispatch.Size(m)
}
func (m *JobDispatch) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDispatch.DiscardUnknown(m)
}

var xxx_messageInfo_JobDispatch proto.InternalMessageInfo

func (m *JobDispatch) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobDispatch) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *JobDispatch) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *JobDispatch) GetPayloadJson() []byte {
	if m != nil {
		return m.PayloadJson
	}
	return nil
}

func (m *JobDispatch) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

// Acknowledges receipt of a JobDispatch.
type JobAck struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimestampMs          int64    `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobAck) Reset()         { *m = JobAck{} }
func (m *JobAck) String() string { return proto.CompactTextString(m) }
func (*JobAck) ProtoMessage()    {}
func (*JobAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{4}
}

func (m *JobAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobAck.Unmarshal(m, b)
}
func (m *JobAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobAck.Marshal(b, m, deterministic)
}
func (m *JobAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobAck.Merge(m, src)
}
func (m *JobAck) XXX_Size() int {
	return xxx_messageInfo_JobAck.Size(m)
}
func (m *JobAck) XXX_DiscardUnknown() {
	xxx_messageInfo_JobAck.DiscardUnknown(m)
}

var xxx_messageInfo_JobAck proto.InternalMessageInfo

func (m *JobAck) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobAck) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *JobAck) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

// Represents a job in the queue.
type QueueJob struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId             string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ParentTaskId         string   `protobuf:"bytes,3,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"`
	AgentRole            string   `protobuf:"bytes,4,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	Payload              string   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Attempts             int32    `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts          int32    `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	RunAfterMs           int64    `protobuf:"varint,9,opt,name=run_after_ms,json=runAfterMs,proto3" json:"run_after_ms,omitempty"`
	LockedUntilMs        int64    `protobuf:"varint,10,opt,name=locked_until_ms,json=lockedUntilMs,proto3" json:"locked_until_ms,omitempty"`
	CreatedAtMs          int64    `protobuf:"varint,11,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	UpdatedAtMs          int64    `protobuf:"varint,12,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueJob) Reset()         { *m = QueueJob{} }
func (m *QueueJob) String() string { return proto.CompactTextString(m) }
func (*QueueJob) ProtoMessage()    {}
func (*QueueJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{5}
}

func (m *QueueJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueJob.Unmarshal(m, b)
}
func (m *QueueJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueJob.Marshal(b, m, deterministic)
}
func (m *QueueJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueJob.Merge(m, src)
}
func (m *QueueJob) XXX_Size() int {
	return xxx_messageInfo_QueueJob.Size(m)
}
func (m *QueueJob) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueJob.DiscardUnknown(m)
}

var xxx_messageInfo_QueueJob proto.InternalMessageInfo

func (m *QueueJob) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueJob) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *QueueJob) GetParentTaskId() string {
	if m != nil {
		return m.ParentTaskId
	}
	return ""
}

func (m *QueueJob) GetAgentRole() string {
	if m != nil {
		return m.AgentRole
	}
	return ""
}

func (m *QueueJob) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *QueueJob) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueueJob) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *QueueJob) GetMaxAttempts() int32 {
	if m != nil {
		return m.MaxAttempts
	}
	return 0
}

func (m *QueueJob) GetRunAfterMs() int64 {
	if m != nil {
		return m.RunAfterMs
	}
	return 0
}

func (m *QueueJob) GetLockedUntilMs() int64 {
	if m != nil {
		return m.LockedUntilMs
	}
	return 0
}

func (m *QueueJob) GetCreatedAtMs() int64 {
	if m != nil {
		return m.CreatedAtMs
	}
	return 0
}

func (m *QueueJob) GetUpdatedAtMs() int64 {
	if m != nil {
		return m.UpdatedAtMs
	}
	return 0
}

// Reports the status of an executing job.
type JobStatusUpdate struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId             string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DetailsPayload       []byte   `protobuf:"bytes,4,opt,name=details_payload,json=detailsPayload,proto3" json:"details_payload,omitempty"`
	TimestampMs          int64    `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatusUpdate) Reset()         { *m = JobStatusUpdate{} }
func (m *JobStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*JobStatusUpdate) ProtoMessage()    {}
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebda08fe93041da, []int{6}
}

func (m *JobStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatusUpdate.Unmarshal(m, b)
}
func (m *JobStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatusUpdate.Marshal(b, m, deterministic)
}
func (m *JobStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatusUpdate.Merge(m, src)
}
func (m *JobStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_JobStatusUpdate.Size(m)
}
func (m *JobStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatusUpdate proto.InternalMessageInfo

func (m *JobStatusUpdate) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobStatusUpdate) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *JobStatusUpdate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *JobStatusUpdate) GetDetailsPayload() []byte {
	if m != nil {
		return m.DetailsPayload
	}
	return nil
}

func (m *JobStatusUpdate) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

func init() {
	proto.RegisterEnum("ohc.interop.DeploymentMode", DeploymentMode_name, DeploymentMode_value)
	proto.RegisterType((*StateHandoff)(nil), "ohc.interop.StateHandoff")
	proto.RegisterType((*HealthPing)(nil), "ohc.interop.HealthPing")
	proto.RegisterType((*HealthAck)(nil), "ohc.interop.HealthAck")
	proto.RegisterType((*JobDispatch)(nil), "ohc.interop.JobDispatch")
	proto.RegisterType((*JobAck)(nil), "ohc.interop.JobAck")
	proto.RegisterType((*QueueJob)(nil), "ohc.interop.QueueJob")
	proto.RegisterType((*JobStatusUpdate)(nil), "ohc.interop.JobStatusUpdate")
}

func init() {
	proto.RegisterFile("interop.proto", fileDescriptor_4ebda08fe93041da)
}

var fileDescriptor_4ebda08fe93041da = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xe2, 0x46,
	0x14, 0xad, 0x21, 0x21, 0xf8, 0xda, 0x31, 0x74, 0xd2, 0x0f, 0xd4, 0xa8, 0x2a, 0x45, 0x51, 0x8b,
	0xfa, 0x00, 0x52, 0xfb, 0xd8, 0x28, 0x12, 0x0d, 0x54, 0x81, 0x06, 0x92, 0x9a, 0xf0, 0xd2, 0x3e,
	0x58, 0x63, 0x7b, 0x02, 0x0e, 0xf6, 0x8c, 0xe5, 0x19, 0x4b, 0x49, 0xff, 0x47, 0x1f, 0xfa, 0x0f,
	0xba, 0xbf, 0x72, 0x57, 0xf3, 0x01, 0x49, 0xb4, 0xbb, 0x02, 0xed, 0x13, 0xcc, 0xb9, 0xe7, 0x7a,
	0xe6, 0x9c, 0x7b, 0x66, 0xe0, 0x38, 0xa1, 0x82, 0x14, 0x2c, 0xef, 0xe5, 0x05, 0x13, 0x0c, 0x39,
	0x6c, 0x15, 0xf5, 0x0c, 0xd4, 0xf9, 0xaf, 0x02, 0xee, 0x5c, 0x60, 0x41, 0xae, 0x30, 0x8d, 0xd9,
	0xfd, 0x3d, 0xfa, 0x16, 0x20, 0x4b, 0x38, 0x4f, 0x18, 0x0d, 0x92, 0xb8, 0x65, 0xb5, 0xad, 0xae,
	0xed, 0xdb, 0x06, 0x19, 0xc7, 0xe8, 0x14, 0x6c, 0x41, 0x28, 0xa6, 0x42, 0x56, 0x2b, 0xaa, 0x5a,
	0xd7, 0xc0, 0x38, 0x46, 0xe7, 0xe0, 0x70, 0x56, 0x16, 0x11, 0x09, 0x32, 0x16, 0x93, 0x56, 0xb5,
	0x6d, 0x75, 0xbd, 0x9f, 0x4f, 0x7b, 0x2f, 0xf6, 0xeb, 0x0d, 0x49, 0x9e, 0xb2, 0xa7, 0x8c, 0x50,
	0x31, 0x65, 0x31, 0xf1, 0x41, 0xf3, 0xe5, 0x7f, 0xd9, 0x2d, 0x70, 0xb1, 0x24, 0x42, 0x77, 0x1f,
	0xec, 0xd1, 0xad, 0xf9, 0xaa, 0xfb, 0x7b, 0x70, 0x45, 0x92, 0x11, 0x2e, 0x70, 0x96, 0x07, 0x19,
	0x6f, 0x1d, 0xb6, 0xad, 0x6e, 0xd5, 0x77, 0xb6, 0xd8, 0x94, 0xa3, 0x1e, 0x9c, 0x70, 0x29, 0x35,
	0xe0, 0x14, 0xe7, 0x7c, 0xc5, 0x44, 0xf0, 0xc0, 0x19, 0x6d, 0xd5, 0xda, 0x56, 0xd7, 0xf5, 0x3f,
	0x57, 0xa5, 0xb9, 0xa9, 0x4c, 0x38, 0xa3, 0x9d, 0x7f, 0x2d, 0x80, 0x2b, 0x82, 0x53, 0xb1, 0xba,
	0x4d, 0xe8, 0x12, 0x9d, 0x81, 0x67, 0xd4, 0x51, 0x16, 0x93, 0x67, 0x77, 0x5c, 0x8d, 0xce, 0x58,
	0x4c, 0xc6, 0x31, 0xba, 0x00, 0x37, 0x2a, 0x8b, 0x82, 0x50, 0x23, 0xa3, 0xb2, 0x5b, 0x86, 0x63,
	0x1a, 0x3e, 0xa8, 0xa3, 0xfa, 0x9e, 0x8e, 0xce, 0x3f, 0x60, 0xeb, 0x63, 0x0d, 0xa2, 0xf5, 0x9e,
	0xa7, 0x3a, 0x03, 0xcf, 0x78, 0xbb, 0x61, 0xe9, 0xd9, 0xb9, 0x1a, 0x35, 0xac, 0x3d, 0xf6, 0xfe,
	0xdf, 0x02, 0x67, 0xc2, 0xc2, 0x61, 0xc2, 0x73, 0x2c, 0xa2, 0x15, 0xfa, 0x12, 0x6a, 0x0f, 0x2c,
	0x7c, 0xde, 0xf6, 0xf0, 0x81, 0x85, 0xbb, 0x62, 0xf2, 0x1d, 0x38, 0x38, 0x12, 0x32, 0x61, 0x14,
	0x67, 0x3a, 0x26, 0xb6, 0x0f, 0x1a, 0x9a, 0xe1, 0x4c, 0x79, 0x90, 0xe3, 0xa7, 0x94, 0xe1, 0x58,
	0x4f, 0xe8, 0x40, 0x4d, 0xc8, 0x31, 0x98, 0x9c, 0xcd, 0x1e, 0xe3, 0xee, 0xfc, 0x0d, 0xb5, 0x09,
	0x0b, 0xa5, 0x47, 0x1f, 0x39, 0xe4, 0xd7, 0x70, 0xf4, 0xda, 0x8d, 0x1a, 0xdd, 0xdb, 0x87, 0xb7,
	0x15, 0xa8, 0xff, 0x59, 0x92, 0x92, 0x4c, 0x58, 0x88, 0x3c, 0xa8, 0x6c, 0xbf, 0x5d, 0x49, 0x76,
	0xa8, 0x3f, 0x03, 0x2f, 0xc7, 0x2a, 0x1f, 0x02, 0xf3, 0xb5, 0x64, 0x68, 0x03, 0x5c, 0x8d, 0xde,
	0x61, 0xbe, 0x1e, 0xc7, 0xf2, 0x1a, 0xe2, 0xa5, 0x24, 0x15, 0x2c, 0xd5, 0x77, 0xc1, 0xf6, 0x6d,
	0x85, 0xf8, 0x2c, 0x25, 0xa8, 0x05, 0x47, 0xc6, 0x0d, 0xa5, 0xdc, 0xf6, 0x37, 0x4b, 0xf4, 0x15,
	0xd4, 0x64, 0x92, 0x4b, 0xae, 0x72, 0x6d, 0xfb, 0x66, 0x85, 0xbe, 0x81, 0x3a, 0x16, 0x82, 0x64,
	0xb9, 0xe0, 0xad, 0xa3, 0xb6, 0xd5, 0x3d, 0xf4, 0xb7, 0x6b, 0xa9, 0x37, 0xc3, 0x8f, 0xc1, 0xb6,
	0x5e, 0x57, 0x75, 0x27, 0xc3, 0x8f, 0x83, 0x0d, 0xa5, 0x0d, 0x6e, 0x51, 0xd2, 0x00, 0xdf, 0x0b,
	0x52, 0x48, 0x4b, 0x6c, 0x65, 0x09, 0x14, 0x25, 0x1d, 0x48, 0x68, 0xca, 0xd1, 0x0f, 0xd0, 0x48,
	0x59, 0xb4, 0x26, 0x71, 0x50, 0x52, 0x91, 0xa4, 0x92, 0x04, 0x8a, 0x74, 0xac, 0xe1, 0x85, 0x44,
	0xa7, 0x1c, 0x75, 0xe0, 0x38, 0x2a, 0x08, 0x16, 0x24, 0x0e, 0xb0, 0x90, 0x2c, 0x47, 0xbb, 0x6b,
	0xc0, 0x81, 0xd0, 0x9c, 0x32, 0x8f, 0x5f, 0x70, 0x5c, 0xcd, 0x31, 0xa0, 0xe4, 0x74, 0xde, 0x58,
	0xd0, 0x98, 0xb0, 0x70, 0xae, 0xe4, 0x2d, 0x54, 0xe1, 0x93, 0xd2, 0xf8, 0x6c, 0x58, 0xf5, 0x95,
	0x61, 0x3f, 0x42, 0x23, 0x26, 0x02, 0x27, 0x29, 0x0f, 0x36, 0x56, 0xeb, 0x1c, 0x7a, 0x06, 0xbe,
	0x35, 0x8e, 0xef, 0x8e, 0xe2, 0x4f, 0x7f, 0x80, 0xf7, 0xfa, 0xce, 0xa3, 0x2f, 0xa0, 0x39, 0xbd,
	0x19, 0x8e, 0x82, 0xc5, 0x6c, 0x7e, 0x3b, 0xba, 0x1c, 0xff, 0x3e, 0x1e, 0x0d, 0x9b, 0x9f, 0x21,
	0x0f, 0x40, 0xa1, 0x97, 0xd7, 0x37, 0x8b, 0x61, 0xd3, 0x42, 0x27, 0xd0, 0x50, 0xeb, 0xf9, 0xdd,
	0x60, 0x36, 0x1c, 0x5c, 0xdf, 0xcc, 0x46, 0xcd, 0xca, 0x6f, 0x17, 0x7f, 0x9d, 0x2f, 0x13, 0xb1,
	0x2a, 0xc3, 0x5e, 0xc4, 0xb2, 0x3e, 0xa3, 0x64, 0x55, 0x66, 0x98, 0x46, 0xac, 0xc8, 0xfb, 0x19,
	0xa3, 0xac, 0xcf, 0x8b, 0xa8, 0xaf, 0x5e, 0xfa, 0x3e, 0x5b, 0x45, 0x7d, 0xf3, 0xe6, 0xfc, 0x6a,
	0x7e, 0xf3, 0x30, 0xac, 0xa9, 0xe2, 0x2f, 0xef, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xc3, 0xaf,
	0xec, 0x17, 0x06, 0x00, 0x00,
}
