load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_oidc",
    srcs = ["mod.rs"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:jsonwebtoken",
        "@crates//:reqwest",
        "@crates//:tokio",
        "@crates//:chrono",
        "@crates//:tracing",
        "//src/server/common:server_common",
        "//src/server/config:server_config",
    ],
)
