load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_oidc",
    srcs = ["mod.rs"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:jsonwebtoken",
        "@crates//:reqwest",
        "@crates//:tokio",
        "@crates//:chrono",
        "@crates//:tracing",
        "//src/server/common:server_common",
    ],
)

rust_test(
    name = "server_oidc_unit_test",
    size = "small",
    crate = ":server_oidc",
    edition = "2024",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "@crates//:temp-env",
    ],
)
