[package]
name = "server_oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
jsonwebtoken = "9"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
server_common = { path = "../common" }
server_telemetry = { path = "../telemetry" }
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
temp-env = "0.3.6"

[lib]
path = "mod.rs"

[lints]
workspace = true
