load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files([
    "mod.rs",
    "webhook.rs",
])

rust_library(
    name = "voice",
    srcs = [
        "bazel_lib.rs",
        "mod.rs",
        "webhook.rs",
    ],
    crate_root = "bazel_lib.rs",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/voice:voice",
        "@crates//:axum",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:lazy_static",
        "@crates//:tokio",
    ],
)
