load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "google_business",
    srcs = [
        "client.rs",
        "mod.rs",
    ],
    crate_root = "mod.rs",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/common:server_common",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tracing",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)
