import React, { useState } from 'react';
export function Step7ProductAdd({ onNext }: { onNext: () => void }) {
   const [desc, setDesc] = useState('');
   const [image, setImage] = useState<string | null>(null);
   const handleGenerateAI = () => {
     setDesc('Generating...');
     setTimeout(() => setDesc('Premium, handcrafted item tailored for you. Auto-generated by OHC AI.'), 1000);
   };
   return <div className="p-8"><h2>Add your first product or service</h2><input type="text" placeholder="What is the name of this product?" className="border p-2 block mb-2" /><input type="text" placeholder="0.00" className="border p-2 block mb-2" /><textarea value={desc} readOnly placeholder="Product description..." className="border p-2 block mb-2 w-full h-24" /><button className="bg-purple-600 text-white p-2 rounded mb-2 block" onClick={handleGenerateAI}>Generate AI Description</button><input type="file" onChange={(e) => setImage("uploaded")} className="mb-2 block" />{image && <span className="block text-green-600 mb-2">Photo Cropped & Uploaded</span>}<button className="bg-blue-600 text-white p-2 rounded" onClick={onNext}>Next →</button></div>;
}
