filegroup(
    name = "srcs",
    srcs = [
        "business_advisory_agent.rs",
        "customer_success_agent.rs",
        "finance_agent.rs",
        "legal_agent.rs",
        "marketing_agent.rs",
        "mod.rs",
        "operations_agent.rs",
        "orchestrator.rs",
        "sales_agent.rs",
        "throttling.rs",
        "types.rs",
        "//src/server/orchestration/departments/memory:srcs",
    ],
    visibility = ["//src/server/orchestration:__pkg__"],
)
