// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/billing.proto

package billingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Model            string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	CostUsd          float64                `protobuf:"fixed64,6,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	OccurredAtUnix   int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

func (x *TokenUsage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TokenUsage) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TokenUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TokenUsage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *TokenUsage) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type CostSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId      string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TotalCostUsd        float64                `protobuf:"fixed64,2,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	TotalTokens         int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ProjectedMonthlyUsd float64                `protobuf:"fixed64,4,opt,name=projected_monthly_usd,json=projectedMonthlyUsd,proto3" json:"projected_monthly_usd,omitempty"`
	Agents              []*AgentCostSummary    `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CostSummary) Reset() {
	*x = CostSummary{}
	mi := &file_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostSummary) ProtoMessage() {}

func (x *CostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostSummary.ProtoReflect.Descriptor instead.
func (*CostSummary) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CostSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CostSummary) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *CostSummary) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *CostSummary) GetProjectedMonthlyUsd() float64 {
	if x != nil {
		return x.ProjectedMonthlyUsd
	}
	return 0
}

func (x *CostSummary) GetAgents() []*AgentCostSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentCostSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,2,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	TokenUsed     int64                  `protobuf:"varint,3,opt,name=token_used,json=tokenUsed,proto3" json:"token_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCostSummary) Reset() {
	*x = AgentCostSummary{}
	mi := &file_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCostSummary) ProtoMessage() {}

func (x *AgentCostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCostSummary.ProtoReflect.Descriptor instead.
func (*AgentCostSummary) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *AgentCostSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCostSummary) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *AgentCostSummary) GetTokenUsed() int64 {
	if x != nil {
		return x.TokenUsed
	}
	return 0
}

type BudgetAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ThresholdUsd   float64                `protobuf:"fixed64,3,opt,name=threshold_usd,json=thresholdUsd,proto3" json:"threshold_usd,omitempty"`
	NotifyAtPct    float64                `protobuf:"fixed64,4,opt,name=notify_at_pct,json=notifyAtPct,proto3" json:"notify_at_pct,omitempty"`
	Triggered      bool                   `protobuf:"varint,5,opt,name=triggered,proto3" json:"triggered,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BudgetAlert) Reset() {
	*x = BudgetAlert{}
	mi := &file_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAlert) ProtoMessage() {}

func (x *BudgetAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAlert.ProtoReflect.Descriptor instead.
func (*BudgetAlert) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetAlert) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *BudgetAlert) GetThresholdUsd() float64 {
	if x != nil {
		return x.ThresholdUsd
	}
	return 0
}

func (x *BudgetAlert) GetNotifyAtPct() float64 {
	if x != nil {
		return x.NotifyAtPct
	}
	return 0
}

func (x *BudgetAlert) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

var File_proto_billing_proto protoreflect.FileDescriptor

const file_proto_billing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/billing.proto\x12\vohc.billing\"\xfd\x01\n" +
	"\n" +
	"TokenUsage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12\x19\n" +
	"\bcost_usd\x18\x06 \x01(\x01R\acostUsd\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix\"\xea\x01\n" +
	"\vCostSummary\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0etotal_cost_usd\x18\x02 \x01(\x01R\ftotalCostUsd\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x122\n" +
	"\x15projected_monthly_usd\x18\x04 \x01(\x01R\x13projectedMonthlyUsd\x125\n" +
	"\x06agents\x18\x05 \x03(\v2\x1d.ohc.billing.AgentCostSummaryR\x06agents\"g\n" +
	"\x10AgentCostSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bcost_usd\x18\x02 \x01(\x01R\acostUsd\x12\x1d\n" +
	"\n" +
	"token_used\x18\x03 \x01(\x03R\ttokenUsed\"\xad\x01\n" +
	"\vBudgetAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rthreshold_usd\x18\x03 \x01(\x01R\fthresholdUsd\x12\"\n" +
	"\rnotify_at_pct\x18\x04 \x01(\x01R\vnotifyAtPct\x12\x1c\n" +
	"\ttriggered\x18\x05 \x01(\bR\ttriggered2\x9a\x01\n" +
	"\x0eBillingService\x12C\n" +
	"\x0fTrackTokenUsage\x12\x17.ohc.billing.TokenUsage\x1a\x17.ohc.billing.TokenUsage\x12C\n" +
	"\x0eGetCostSummary\x12\x17.ohc.billing.TokenUsage\x1a\x18.ohc.billing.CostSummaryB?Z=github.com/onehumancorp/mono/srcs/proto/ohc/billing;billingpbb\x06proto3"

var (
	file_proto_billing_proto_rawDescOnce sync.Once
	file_proto_billing_proto_rawDescData []byte
)

func file_proto_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)))
	})
	return file_proto_billing_proto_rawDescData
}

var file_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_billing_proto_goTypes = []any{
	(*TokenUsage)(nil),       // 0: ohc.billing.TokenUsage
	(*CostSummary)(nil),      // 1: ohc.billing.CostSummary
	(*AgentCostSummary)(nil), // 2: ohc.billing.AgentCostSummary
	(*BudgetAlert)(nil),      // 3: ohc.billing.BudgetAlert
}
var file_proto_billing_proto_depIdxs = []int32{
	2, // 0: ohc.billing.CostSummary.agents:type_name -> ohc.billing.AgentCostSummary
	0, // 1: ohc.billing.BillingService.TrackTokenUsage:input_type -> ohc.billing.TokenUsage
	0, // 2: ohc.billing.BillingService.GetCostSummary:input_type -> ohc.billing.TokenUsage
	0, // 3: ohc.billing.BillingService.TrackTokenUsage:output_type -> ohc.billing.TokenUsage
	1, // 4: ohc.billing.BillingService.GetCostSummary:output_type -> ohc.billing.CostSummary
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_billing_proto_init() }
func file_proto_billing_proto_init() {
	if File_proto_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_proto = out.File
	file_proto_billing_proto_goTypes = nil
	file_proto_billing_proto_depIdxs = nil
}
