load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "growth",
    srcs = [
        "quota_service.go",
        "referral.go",
        "referrals_repo.go",
    ],
    importpath = "github.com/onehumancorp/mono/services/growth",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/analytics",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

go_test(
    name = "growth_test",
    srcs = [
        "ab_test.go",
        "ab_test_test.go",
        "quota_service_test.go",
        "referral_test.go",
        "referrals_repo_test.go",
    ],
    embed = [":growth"],
    deps = [
        "//lib/analytics",
        "@com_github_alicebob_miniredis_v2//:miniredis",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)
