load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "analytics",
    srcs = ["events.go"],
    importpath = "github.com/onehumancorp/mono/lib/analytics",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute:attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "analytics_test",
    srcs = ["events_test.go"],
    embed = [":analytics"],
)
