load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "analytics",
    srcs = ["viral_loop.go"],
    importpath = "github.com/onehumancorp/mono/lib/analytics",
    visibility = ["//visibility:public"],
)

go_test(
    name = "analytics_test",
    srcs = ["viral_loop_test.go"],
    embed = [":analytics"],
)
