import {render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {parseAuthRuntimeConfig} from '@/lib/auth/runtimeConfig';
import {parseSessionKeyRing} from '@/lib/auth/sessionKeys';
import {sealSession} from '@/lib/auth/sessionCodec';
import {cookieForSession,serializeSessionCookie,sessionCodecContext} from '@/lib/auth/sessionCookie';
import {proxyAuthenticatedRequest,type BackendTransportDependencies} from '@/lib/auth/backendTransport';
import {GET} from '../api/v1/[...path]/route';
import Page from './page';
const bridge=vi.hoisted(()=>({run:vi.fn()}));
vi.mock('@/lib/auth/backendTransport',async original=>({...(await original<typeof import('@/lib/auth/backendTransport')>()),proxyBackendRequest:(...args:unknown[])=>bridge.run(...args)}));
vi.mock('next/navigation',()=>({useRouter:()=>({back:vi.fn()})}));
vi.mock('../components/PoweredByOmniSolo',()=>({PoweredByOmniSolo:()=>null}));
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();});
it.each([200,404])('the actual fallback transport permits the editor private GET with status%s',async status=>{
 const now=Math.floor(Date.now()/1000);const owner={userId:'owner-a',tenantId:'tenant-a',expiresAt:(now+600)*1000};
 const profile={store_name:'Recorded profile',bio:'Stored private details',theme:'light',links:[],remove_branding:false};
 const backend=vi.fn<typeof fetch>().mockImplementation(async()=>status===404?new Response('',{status:404}):Response.json(profile));
 const config=parseAuthRuntimeConfig({OMNISOLO_WEB_CANONICAL_ORIGIN:'https://app.example.com',BACKEND_URL:'https://api.example.com'});
 const ring=await parseSessionKeyRing({OMNISOLO_WEB_SESSION_KEY_ID:'test-v1',OMNISOLO_WEB_SESSION_SECRET:'Ww7LSLEn9AaAN6IT5kwJ0yGqVO11CMI9nOEqi7wF10I'});
 const session={version:1 as const,iat:now,exp:now+600,accessToken:'synthetic.backend.token',user:{id:owner.userId,username:'Fixture owner',roles:['ADMIN'],organizationId:owner.tenantId}};
 const compact=await sealSession(session,ring,sessionCodecContext(config),{now,backendExpiresAt:session.exp});
 const cookie=serializeSessionCookie(cookieForSession(config,compact,now,session.exp)).split(';',1)[0];
 const deps:BackendTransportDependencies={config,ring,now:()=>now,fetchImpl:backend,timeoutMs:1000,requestLimitBytes:4096,responseLimitBytes:4096};
 const observed:{status:number;body:string}[]=[];
 bridge.run.mockImplementation(async(request,path,options)=>{const response=await proxyAuthenticatedRequest(request,path,deps,options);observed.push({status:response.status,body:await response.clone().text()});return response;});
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{
   const path=String(input);if(path==='/api/v1/auth/session-identity')return Response.json(owner);
   const headers=new Headers(init?.headers);headers.set('cookie',cookie);
   return GET(new Request('https://app.example.com'+path,{...init,headers}),{params:Promise.resolve({path:path.replace('/api/v1/','').split('/').map(decodeURIComponent)})});
 }));
 render(<Page/>);
 await waitFor(()=>expect(observed).toHaveLength(1));
 expect(observed[0].status,observed[0].body).toBe(status);
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save private configuration'})).toBeEnabled());
 expect(backend).toHaveBeenCalledTimes(1);
 if(status===200)expect(screen.getByDisplayValue('Recorded profile')).toBeVisible();
 else expect(screen.getByRole('status',{name:'Private profile status'})).toHaveTextContent('No saved private profile');
 const request=bridge.run.mock.calls[0][0] as Request;
 expect(request.headers.get('content-type')).toBeNull();expect(request.headers.get('x-ohc-expected-user')).toBe(owner.userId);expect(request.headers.get('x-ohc-expected-tenant')).toBe(owner.tenantId);
});
