load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "onboarding",
    srcs = ["onboarding_service.go"],
    importpath = "github.com/onehumancorp/ohc/services/onboarding",
    visibility = ["//visibility:public"],
)

go_test(
    name = "onboarding_test",
    srcs = ["onboarding_service_test.go"],
    embed = [":onboarding"],
)
