load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "onboarding",
    srcs = ["env_verifier.go", "server.go"],
    importpath = "github.com/onehumancorp/mono/services/onboarding",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "onboarding_test",
    srcs = ["env_verifier_test.go", "server_test.go"],
    embed = [":onboarding"],
)
