load("@aspect_rules_js//js:defs.bzl", "js_library", "js_binary")

js_library(
    name = "lib",
    srcs = glob(["src/**/*.ts", "src/**/*.tsx"], allow_empty = True) + ["tsconfig.json", "package.json"],
    visibility = ["//visibility:public"],
)

js_binary(
    name = "cli",
    data = [":lib", "//:node_modules"],
    entry_point = "src/index.tsx",
)
