load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = [
        "http_handler.go",
        "local_mesh.go",
        "mesh.go",
        "redis_mesh.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

go_test(
    name = "mesh_test",
    srcs = [
        "http_handler_test.go",
        "mesh_test.go",
    ],
    embed = [":mesh"],
    deps = [
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)
