load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = [
        "broker.go",
        "http_handler.go",
        "local_broker.go",
        "redis_broker.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_redis_rueidis//:rueidis",
    ],
)

go_test(
    name = "mesh_test",
    srcs = ["broker_test.go"],
    embed = [":mesh"],
    deps = [
        "@com_github_redis_rueidis//:rueidis",
    ],
)
