// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/hub.proto

package hub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_AdvertiseCapabilities_FullMethodName = "/hub.HubService/AdvertiseCapabilities"
	HubService_DiscoverAgents_FullMethodName        = "/hub.HubService/DiscoverAgents"
	HubService_StreamMeshEvents_FullMethodName      = "/hub.HubService/StreamMeshEvents"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	AdvertiseCapabilities(ctx context.Context, in *AdvertiseCapabilitiesRequest, opts ...grpc.CallOption) (*AdvertiseCapabilitiesResponse, error)
	DiscoverAgents(ctx context.Context, in *DiscoverAgentsRequest, opts ...grpc.CallOption) (*DiscoverAgentsResponse, error)
	StreamMeshEvents(ctx context.Context, in *StreamMeshEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMeshEventsResponse], error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) AdvertiseCapabilities(ctx context.Context, in *AdvertiseCapabilitiesRequest, opts ...grpc.CallOption) (*AdvertiseCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvertiseCapabilitiesResponse)
	err := c.cc.Invoke(ctx, HubService_AdvertiseCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) DiscoverAgents(ctx context.Context, in *DiscoverAgentsRequest, opts ...grpc.CallOption) (*DiscoverAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverAgentsResponse)
	err := c.cc.Invoke(ctx, HubService_DiscoverAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) StreamMeshEvents(ctx context.Context, in *StreamMeshEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMeshEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_StreamMeshEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMeshEventsRequest, StreamMeshEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_StreamMeshEventsClient = grpc.ServerStreamingClient[StreamMeshEventsResponse]

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
type HubServiceServer interface {
	AdvertiseCapabilities(context.Context, *AdvertiseCapabilitiesRequest) (*AdvertiseCapabilitiesResponse, error)
	DiscoverAgents(context.Context, *DiscoverAgentsRequest) (*DiscoverAgentsResponse, error)
	StreamMeshEvents(*StreamMeshEventsRequest, grpc.ServerStreamingServer[StreamMeshEventsResponse]) error
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) AdvertiseCapabilities(context.Context, *AdvertiseCapabilitiesRequest) (*AdvertiseCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseCapabilities not implemented")
}
func (UnimplementedHubServiceServer) DiscoverAgents(context.Context, *DiscoverAgentsRequest) (*DiscoverAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverAgents not implemented")
}
func (UnimplementedHubServiceServer) StreamMeshEvents(*StreamMeshEventsRequest, grpc.ServerStreamingServer[StreamMeshEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMeshEvents not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call panics, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_AdvertiseCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).AdvertiseCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_AdvertiseCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).AdvertiseCapabilities(ctx, req.(*AdvertiseCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_DiscoverAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).DiscoverAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_DiscoverAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).DiscoverAgents(ctx, req.(*DiscoverAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_StreamMeshEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMeshEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).StreamMeshEvents(m, &grpc.GenericServerStream[StreamMeshEventsRequest, StreamMeshEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_StreamMeshEventsServer = grpc.ServerStreamingServer[StreamMeshEventsResponse]

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdvertiseCapabilities",
			Handler:    _HubService_AdvertiseCapabilities_Handler,
		},
		{
			MethodName: "DiscoverAgents",
			Handler:    _HubService_DiscoverAgents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMeshEvents",
			Handler:       _HubService_StreamMeshEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hub.proto",
}
