syntax = "proto3";

package ohc.auth;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/onehumancorp/mono/srcs/proto/ohc/auth";

message UserMetadata {
  string id = 1;
  string username = 2;
  string email = 3;
  repeated string roles = 4;
  bool active = 5;
  string organization_id = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
  string oidc_subject = 9;
}

message User {
  UserMetadata metadata = 1;
  string password_hash = 2;
}
