-- +goose Up
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_email VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tier VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS state TEXT;

-- +goose Down
ALTER TABLE tenants DROP COLUMN IF EXISTS owner_email;
ALTER TABLE tenants DROP COLUMN IF EXISTS tier;
ALTER TABLE tenants DROP COLUMN IF EXISTS state;
