-- +goose Up
ALTER TABLE IF EXISTS mcp_servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ohc_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mcp_audit_sync_log ENABLE ROW LEVEL SECURITY;

-- +goose Down
