-- +goose Up
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_audit_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ohc_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE kairos_shared_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE kairos_state_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kairos_sub_agent_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE autodream_vector_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE autodream_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE local_telemetry_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE swarm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE state_machine_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_tasks_decomposition ENABLE ROW LEVEL SECURITY;
ALTER TABLE consolidated_memory ENABLE ROW LEVEL SECURITY;

-- +goose Down
-- No-op for down migration since dropping RLS is generally safe
