-- +goose Up
ALTER TABLE consolidated_memory ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE consolidated_memory ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;
