load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@npm//:defs.bzl", "npm_link_all_packages")

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

npm_link_all_packages(name = "node_modules")

exports_files(["tsconfig.json"])

# Plugin and rule infrastructure for protobuf TypeScript generation in bazel/rules

# Fix for misplaced alias error with rules_nodejs
filegroup(
    name = "node_fixed",
    srcs = ["@nodejs//:node"],
    visibility = ["//visibility:public"],
)

# gazelle:prefix github.com/onehumancorp/mono
exports_files([
    "pubspec.yaml",
])


config_setting(
    name = "linux",
    constraint_values = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "macos",
    constraint_values = ["@platforms//os:macos"],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "windows",
    constraint_values = ["@platforms//os:windows"],
    visibility = ["//visibility:public"],
)



sh_binary(
    name = "deploy_dev",
    srcs = ["//deploy:deploy_dev.sh"],
    data = [
        "//deploy:docker-compose.yml",
        "//deploy:server_load",
        "//deploy:setup_k8s.sh",
    ],
    tags = ["manual"],
)

filegroup(
    name = "docs_srcs",
    srcs = glob(["docs/**"]) + ["mkdocs.yml"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "docs_build",
    srcs = ["docs/mkdocs_via_bazel.sh"],
    args = ["build"],
    data = [":docs_srcs"],
    tags = ["manual"],
)

sh_binary(
    name = "docs_serve",
    srcs = ["docs/mkdocs_via_bazel.sh"],
    args = ["serve"],
    data = [":docs_srcs"],
    tags = ["manual"],
)

sh_binary(
    name = "update-deps",
    srcs = ["update_deps.sh"],
    data = [
        "MODULE.bazel",
    ],
    tags = ["manual"],
)


# Alias to run hello-world agent easily
alias(
    name = "hello-world",
    actual = "//src/examples/hello-world-agent:hello-world",
    tags = ["manual"],
)

load("@gazelle//:def.bzl", "gazelle")
# gazelle:prefix onehumancorp
gazelle(name = "gazelle")
