FROM postgres:16-alpine
RUN apk add --no-cache git build-base clang15 llvm15 llvm15-dev
RUN git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install
