import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component Test inherits Window {
    preferred-width: 1440px;
    preferred-height: 900px;

    HorizontalBox {
        alignment: center;
        VerticalBox {
            alignment: center;
            max-width: 400px;

            Rectangle {
                background: blue;
                height: 200px;
                Text { text: "Hello World"; }
            }
        }
    }
}
