load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_integrations_p2p_mesh",
    srcs = glob(["**/*.rs"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/common:server_common",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:uuid",
    ],
)
