load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tasks",
    srcs = [
        "models.go",
        "service.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/tasks",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
    ],
)

go_test(
    name = "tasks_test",
    srcs = ["service_test.go"],
    embed = [":tasks"],
    deps = [
        "//srcs/server/db",
    ],
)
