load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "chaos_system_test",
    srcs = ["chaos_system_test.go"],
    deps = [
        "//srcs/server/lib/resilience/chaos",
    ],
)

go_test(
    name = "kairos_parity_chaos_test",
    srcs = ["kairos_parity_chaos_test.go"],
    deps = [
        "//srcs/server/orchestration/kairos",
    ],
)
