load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mercadopago",
    srcs = ["mercadopago.go"],
    importpath = "github.com/onehumancorp/mono/src/server/integrations/mercadopago",
    visibility = ["//visibility:public"],
)

go_test(
    name = "mercadopago_test",
    srcs = ["mercadopago_test.go"],
    embed = [":mercadopago"],
)
