load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "scout",
    srcs = ["scout.go"],
    importpath = "github.com/onehumancorp/mono/src/server/lib/integrations/scout",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/lib/integrations/hybrid_discovery",
    ],
)

go_test(
    name = "scout_test",
    srcs = ["scout_e2e_test.go"],
    deps = [
        ":scout",
        "//src/server/lib/integrations/hybrid_discovery",
        "@org_modernc_sqlite//:sqlite",
    ],
)
