apiVersion: v1
kind: ResourceQuota
metadata:
  name: ohc-cloud-quota
  namespace: ohc-cloud
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    pods: "100"
