load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "powersync",
    srcs = ["provider.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/integrations/powersync",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/proto:hub_go_proto",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "powersync_test",
    srcs = ["provider_test.go"],
    embed = [":powersync"],
)
