load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_auth",
    srcs = [
        "postgres_store.rs",
        "grpc.rs",
        "mod.rs",
        "orchestration.rs",
    ],
    edition = "2024",
    crate_root = "mod.rs",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/config:server_config",
        "//src/server/common:server_common",
        "//src/server/ohc:server_ohc",
        "//src/server/oidc:server_oidc",
        "@crates//:bcrypt",
        "@crates//:chrono",
        "@crates//:hex",
        "@crates//:hmac",
        "@crates//:jsonwebtoken",
        "@crates//:rand",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sha2",
        "@crates//:sqlx",
        "@crates//:tokio",
        "@crates//:tonic",
        "@crates//:tracing",
        "@crates//:uuid",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)
