load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

# Shell script wrapper for running playwright tests via docker compose
sh_binary(
    name = "run_playwright_e2e",
    srcs = ["run_playwright.sh"],
    data = [
        "//scripts:run-playwright.mjs",
        "//deploy:docker-compose.e2e.yml",
        "//src/server:server",
    ],
    visibility = ["//visibility:public"],
)
