load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "registry",
    srcs = ["registry.go"],
    importpath = "onehumancorp/srcs/backend/tools/registry",
    visibility = ["//visibility:public"],
)

go_test(
    name = "registry_test",
    srcs = ["registry_test.go"],
    embed = [":registry"],
)
