load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "onboarding",
    srcs = ["config_generator.go", "cli.go"],
    importpath = "github.com/onehumancorp/mono/apps/onboarding",
    visibility = ["//visibility:public"],
)

go_test(
    name = "onboarding_test",
    srcs = ["config_generator_test.go", "cli_test.go"],
    embed = [":onboarding"],
)
