load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "onboarding_lib",
    srcs = ["main.go"],
    importpath = "github.com/onehumancorp/mono/apps/onboarding",
    visibility = ["//visibility:private"],
    deps = [
        "//services/onboarding",
    ],
)

go_binary(
    name = "onboarding",
    embed = [":onboarding_lib"],
    visibility = ["//visibility:public"],
)
