
use serde::{Deserialize, Serialize};

/// Represents the exhaustive set of all possible Swarm Protocol messages.
/// This file implements the complete OHC-SIP definition for robust cross-agent communication.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", content = "payload")]
pub enum SipMessage {
    MissionCreate {
        mission_id: String,
        objective: String,
        priority: u8,
    },
    MissionUpdate {
        mission_id: String,
        status: String,
        progress: f32,
    },
    MissionHandoff {
        mission_id: String,
        target_agent: String,
        blockers: String,
    },
    MissionComplete {
        mission_id: String,
        result_summary: String,
    },
    MissionFail {
        mission_id: String,
        error_code: u32,
        details: String,
    },
    AgentSpawn {
        agent_id: String,
        role: String,
        capability_level: u8,
    },
    AgentTerminate {
        agent_id: String,
        reason: String,
    },
    AgentHeartbeat {
        agent_id: String,
        current_load: f32,
        status: String,
    },
    AgentMetrics {
        agent_id: String,
        cpu_usage: f32,
        mem_usage: f32,
        active_tasks: u32,
    },
    AgentLog {
        agent_id: String,
        level: String,
        message: String,
    },
    ResourceAllocate {
        resource_id: String,
        amount: u64,
        requester: String,
    },
    ResourceRelease {
        resource_id: String,
        amount: u64,
        requester: String,
    },
    ResourceStatus {
        resource_id: String,
        total_available: u64,
        total_used: u64,
    },
    TaskAssign {
        task_id: String,
        agent_id: String,
        timeout_secs: u32,
    },
    TaskRevoke {
        task_id: String,
        agent_id: String,
        reason: String,
    },
    TaskProgress {
        task_id: String,
        percent_complete: u8,
        status_message: String,
    },
    QueryRequest {
        query_id: String,
        query_text: String,
        context: String,
    },
    QueryResponse {
        query_id: String,
        response_data: String,
        confidence: f32,
    },
    EventBroadcast {
        event_id: String,
        event_type: String,
        payload: String,
    },
    StateSnapshot {
        snapshot_id: String,
        state_data: String,
        timestamp: i64,
    },
    LockAcquire {
        lock_id: String,
        requester: String,
        ttl_secs: u32,
    },
    LockRelease {
        lock_id: String,
        requester: String,
    },
    CacheSet {
        key: String,
        value: String,
        ttl_secs: u32,
    },
    CacheGet {
        key: String,
    },
    CacheInvalidate {
        key: String,
    },
    ConfigUpdate {
        config_key: String,
        new_value: String,
        version: u32,
    },
    AuthTokenRequest {
        agent_id: String,
        permissions: Vec<String>,
    },
    AuthTokenResponse {
        agent_id: String,
        token: String,
        expiry: i64,
    },
    DiscoveryAnnounce {
        service_name: String,
        endpoint: String,
        version: String,
    },
    DiscoveryLookup {
        service_name: String,
        required_version: String,
    },
    MetricRecord {
        metric_name: String,
        value: f64,
        labels: std::collections::HashMap<String,
        String>,
    },
    AlertTrigger {
        alert_name: String,
        severity: String,
        description: String,
    },
    AlertResolve {
        alert_name: String,
        resolution_notes: String,
    },
    PolicyEvaluate {
        policy_id: String,
        context_data: String,
    },
    PolicyResult {
        policy_id: String,
        allowed: bool,
        reason: String,
    },
    DataSyncRequest {
        sync_id: String,
        target_node: String,
        data_type: String,
    },
    DataSyncAck {
        sync_id: String,
        status: String,
        bytes_received: u64,
    },
    PluginLoad {
        plugin_name: String,
        plugin_path: String,
        config: String,
    },
    PluginUnload {
        plugin_name: String,
        force: bool,
    },
    PluginStatus {
        plugin_name: String,
        is_active: bool,
        version: String,
    },
    ExtensionMessage1 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage2 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage3 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage4 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage5 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage6 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage7 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage8 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage9 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage10 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage11 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage12 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage13 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage14 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage15 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage16 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage17 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage18 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage19 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage20 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage21 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage22 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage23 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage24 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage25 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage26 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage27 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage28 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage29 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage30 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage31 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage32 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage33 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage34 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage35 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage36 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage37 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage38 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage39 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage40 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage41 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage42 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage43 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage44 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage45 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage46 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage47 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage48 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage49 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage50 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage51 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage52 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage53 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage54 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage55 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage56 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage57 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage58 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage59 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage60 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage61 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage62 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage63 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage64 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage65 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage66 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage67 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage68 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage69 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage70 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage71 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage72 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage73 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage74 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage75 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage76 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage77 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage78 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage79 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage80 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage81 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage82 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage83 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage84 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage85 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage86 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage87 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage88 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage89 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage90 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage91 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage92 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage93 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage94 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage95 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage96 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage97 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage98 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage99 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage100 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage101 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage102 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage103 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage104 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage105 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage106 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage107 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage108 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage109 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage110 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage111 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage112 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage113 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage114 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage115 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage116 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage117 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage118 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage119 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage120 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage121 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage122 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage123 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage124 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage125 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage126 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage127 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage128 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage129 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage130 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage131 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage132 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage133 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage134 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage135 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage136 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage137 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage138 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage139 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage140 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage141 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage142 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage143 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage144 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage145 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage146 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage147 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage148 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
    ExtensionMessage149 {
        ext_id: String,
        ext_field_a: String,
        ext_field_b: u64,
        ext_flags: u32,
        is_active: bool,
        description: String,
        tags: Vec<String>,
    },
}


impl SipMessage {
    pub fn is_system_level(&self) -> bool {
        match self {
            SipMessage::MissionCreate { .. } => true,
            SipMessage::MissionUpdate { .. } => true,
            SipMessage::MissionHandoff { .. } => true,
            SipMessage::MissionComplete { .. } => true,
            SipMessage::MissionFail { .. } => true,
            SipMessage::AgentSpawn { .. } => true,
            SipMessage::AgentTerminate { .. } => true,
            SipMessage::AgentHeartbeat { .. } => true,
            SipMessage::AgentMetrics { .. } => true,
            SipMessage::AgentLog { .. } => true,
            SipMessage::ResourceAllocate { .. } => true,
            SipMessage::ResourceRelease { .. } => true,
            SipMessage::ResourceStatus { .. } => true,
            SipMessage::TaskAssign { .. } => true,
            SipMessage::TaskRevoke { .. } => true,
            SipMessage::TaskProgress { .. } => true,
            SipMessage::QueryRequest { .. } => true,
            SipMessage::QueryResponse { .. } => true,
            SipMessage::EventBroadcast { .. } => true,
            SipMessage::StateSnapshot { .. } => true,
            SipMessage::LockAcquire { .. } => true,
            SipMessage::LockRelease { .. } => true,
            SipMessage::CacheSet { .. } => true,
            SipMessage::CacheGet { .. } => true,
            SipMessage::CacheInvalidate { .. } => true,
            SipMessage::ConfigUpdate { .. } => true,
            SipMessage::AuthTokenRequest { .. } => true,
            SipMessage::AuthTokenResponse { .. } => true,
            SipMessage::DiscoveryAnnounce { .. } => true,
            SipMessage::DiscoveryLookup { .. } => true,
            SipMessage::MetricRecord { .. } => true,
            SipMessage::AlertTrigger { .. } => true,
            SipMessage::AlertResolve { .. } => true,
            SipMessage::PolicyEvaluate { .. } => true,
            SipMessage::PolicyResult { .. } => true,
            SipMessage::DataSyncRequest { .. } => true,
            SipMessage::DataSyncAck { .. } => true,
            SipMessage::PluginLoad { .. } => true,
            SipMessage::PluginUnload { .. } => true,
            SipMessage::PluginStatus { .. } => true,
            SipMessage::ExtensionMessage1 { .. } => false,
            SipMessage::ExtensionMessage2 { .. } => false,
            SipMessage::ExtensionMessage3 { .. } => false,
            SipMessage::ExtensionMessage4 { .. } => false,
            SipMessage::ExtensionMessage5 { .. } => false,
            SipMessage::ExtensionMessage6 { .. } => false,
            SipMessage::ExtensionMessage7 { .. } => false,
            SipMessage::ExtensionMessage8 { .. } => false,
            SipMessage::ExtensionMessage9 { .. } => false,
            SipMessage::ExtensionMessage10 { .. } => false,
            SipMessage::ExtensionMessage11 { .. } => false,
            SipMessage::ExtensionMessage12 { .. } => false,
            SipMessage::ExtensionMessage13 { .. } => false,
            SipMessage::ExtensionMessage14 { .. } => false,
            SipMessage::ExtensionMessage15 { .. } => false,
            SipMessage::ExtensionMessage16 { .. } => false,
            SipMessage::ExtensionMessage17 { .. } => false,
            SipMessage::ExtensionMessage18 { .. } => false,
            SipMessage::ExtensionMessage19 { .. } => false,
            SipMessage::ExtensionMessage20 { .. } => false,
            SipMessage::ExtensionMessage21 { .. } => false,
            SipMessage::ExtensionMessage22 { .. } => false,
            SipMessage::ExtensionMessage23 { .. } => false,
            SipMessage::ExtensionMessage24 { .. } => false,
            SipMessage::ExtensionMessage25 { .. } => false,
            SipMessage::ExtensionMessage26 { .. } => false,
            SipMessage::ExtensionMessage27 { .. } => false,
            SipMessage::ExtensionMessage28 { .. } => false,
            SipMessage::ExtensionMessage29 { .. } => false,
            SipMessage::ExtensionMessage30 { .. } => false,
            SipMessage::ExtensionMessage31 { .. } => false,
            SipMessage::ExtensionMessage32 { .. } => false,
            SipMessage::ExtensionMessage33 { .. } => false,
            SipMessage::ExtensionMessage34 { .. } => false,
            SipMessage::ExtensionMessage35 { .. } => false,
            SipMessage::ExtensionMessage36 { .. } => false,
            SipMessage::ExtensionMessage37 { .. } => false,
            SipMessage::ExtensionMessage38 { .. } => false,
            SipMessage::ExtensionMessage39 { .. } => false,
            SipMessage::ExtensionMessage40 { .. } => false,
            SipMessage::ExtensionMessage41 { .. } => false,
            SipMessage::ExtensionMessage42 { .. } => false,
            SipMessage::ExtensionMessage43 { .. } => false,
            SipMessage::ExtensionMessage44 { .. } => false,
            SipMessage::ExtensionMessage45 { .. } => false,
            SipMessage::ExtensionMessage46 { .. } => false,
            SipMessage::ExtensionMessage47 { .. } => false,
            SipMessage::ExtensionMessage48 { .. } => false,
            SipMessage::ExtensionMessage49 { .. } => false,
            SipMessage::ExtensionMessage50 { .. } => false,
            SipMessage::ExtensionMessage51 { .. } => false,
            SipMessage::ExtensionMessage52 { .. } => false,
            SipMessage::ExtensionMessage53 { .. } => false,
            SipMessage::ExtensionMessage54 { .. } => false,
            SipMessage::ExtensionMessage55 { .. } => false,
            SipMessage::ExtensionMessage56 { .. } => false,
            SipMessage::ExtensionMessage57 { .. } => false,
            SipMessage::ExtensionMessage58 { .. } => false,
            SipMessage::ExtensionMessage59 { .. } => false,
            SipMessage::ExtensionMessage60 { .. } => false,
            SipMessage::ExtensionMessage61 { .. } => false,
            SipMessage::ExtensionMessage62 { .. } => false,
            SipMessage::ExtensionMessage63 { .. } => false,
            SipMessage::ExtensionMessage64 { .. } => false,
            SipMessage::ExtensionMessage65 { .. } => false,
            SipMessage::ExtensionMessage66 { .. } => false,
            SipMessage::ExtensionMessage67 { .. } => false,
            SipMessage::ExtensionMessage68 { .. } => false,
            SipMessage::ExtensionMessage69 { .. } => false,
            SipMessage::ExtensionMessage70 { .. } => false,
            SipMessage::ExtensionMessage71 { .. } => false,
            SipMessage::ExtensionMessage72 { .. } => false,
            SipMessage::ExtensionMessage73 { .. } => false,
            SipMessage::ExtensionMessage74 { .. } => false,
            SipMessage::ExtensionMessage75 { .. } => false,
            SipMessage::ExtensionMessage76 { .. } => false,
            SipMessage::ExtensionMessage77 { .. } => false,
            SipMessage::ExtensionMessage78 { .. } => false,
            SipMessage::ExtensionMessage79 { .. } => false,
            SipMessage::ExtensionMessage80 { .. } => false,
            SipMessage::ExtensionMessage81 { .. } => false,
            SipMessage::ExtensionMessage82 { .. } => false,
            SipMessage::ExtensionMessage83 { .. } => false,
            SipMessage::ExtensionMessage84 { .. } => false,
            SipMessage::ExtensionMessage85 { .. } => false,
            SipMessage::ExtensionMessage86 { .. } => false,
            SipMessage::ExtensionMessage87 { .. } => false,
            SipMessage::ExtensionMessage88 { .. } => false,
            SipMessage::ExtensionMessage89 { .. } => false,
            SipMessage::ExtensionMessage90 { .. } => false,
            SipMessage::ExtensionMessage91 { .. } => false,
            SipMessage::ExtensionMessage92 { .. } => false,
            SipMessage::ExtensionMessage93 { .. } => false,
            SipMessage::ExtensionMessage94 { .. } => false,
            SipMessage::ExtensionMessage95 { .. } => false,
            SipMessage::ExtensionMessage96 { .. } => false,
            SipMessage::ExtensionMessage97 { .. } => false,
            SipMessage::ExtensionMessage98 { .. } => false,
            SipMessage::ExtensionMessage99 { .. } => false,
            SipMessage::ExtensionMessage100 { .. } => false,
            SipMessage::ExtensionMessage101 { .. } => false,
            SipMessage::ExtensionMessage102 { .. } => false,
            SipMessage::ExtensionMessage103 { .. } => false,
            SipMessage::ExtensionMessage104 { .. } => false,
            SipMessage::ExtensionMessage105 { .. } => false,
            SipMessage::ExtensionMessage106 { .. } => false,
            SipMessage::ExtensionMessage107 { .. } => false,
            SipMessage::ExtensionMessage108 { .. } => false,
            SipMessage::ExtensionMessage109 { .. } => false,
            SipMessage::ExtensionMessage110 { .. } => false,
            SipMessage::ExtensionMessage111 { .. } => false,
            SipMessage::ExtensionMessage112 { .. } => false,
            SipMessage::ExtensionMessage113 { .. } => false,
            SipMessage::ExtensionMessage114 { .. } => false,
            SipMessage::ExtensionMessage115 { .. } => false,
            SipMessage::ExtensionMessage116 { .. } => false,
            SipMessage::ExtensionMessage117 { .. } => false,
            SipMessage::ExtensionMessage118 { .. } => false,
            SipMessage::ExtensionMessage119 { .. } => false,
            SipMessage::ExtensionMessage120 { .. } => false,
            SipMessage::ExtensionMessage121 { .. } => false,
            SipMessage::ExtensionMessage122 { .. } => false,
            SipMessage::ExtensionMessage123 { .. } => false,
            SipMessage::ExtensionMessage124 { .. } => false,
            SipMessage::ExtensionMessage125 { .. } => false,
            SipMessage::ExtensionMessage126 { .. } => false,
            SipMessage::ExtensionMessage127 { .. } => false,
            SipMessage::ExtensionMessage128 { .. } => false,
            SipMessage::ExtensionMessage129 { .. } => false,
            SipMessage::ExtensionMessage130 { .. } => false,
            SipMessage::ExtensionMessage131 { .. } => false,
            SipMessage::ExtensionMessage132 { .. } => false,
            SipMessage::ExtensionMessage133 { .. } => false,
            SipMessage::ExtensionMessage134 { .. } => false,
            SipMessage::ExtensionMessage135 { .. } => false,
            SipMessage::ExtensionMessage136 { .. } => false,
            SipMessage::ExtensionMessage137 { .. } => false,
            SipMessage::ExtensionMessage138 { .. } => false,
            SipMessage::ExtensionMessage139 { .. } => false,
            SipMessage::ExtensionMessage140 { .. } => false,
            SipMessage::ExtensionMessage141 { .. } => false,
            SipMessage::ExtensionMessage142 { .. } => false,
            SipMessage::ExtensionMessage143 { .. } => false,
            SipMessage::ExtensionMessage144 { .. } => false,
            SipMessage::ExtensionMessage145 { .. } => false,
            SipMessage::ExtensionMessage146 { .. } => false,
            SipMessage::ExtensionMessage147 { .. } => false,
            SipMessage::ExtensionMessage148 { .. } => false,
            SipMessage::ExtensionMessage149 { .. } => false,

        }
    }

    pub fn get_routing_key(&self) -> String {
        match self {
            SipMessage::MissionCreate { mission_id, .. } => format!("mission.{}", mission_id),
            SipMessage::MissionUpdate { mission_id, .. } => format!("mission.{}", mission_id),
            SipMessage::MissionHandoff { mission_id, .. } => format!("mission.{}", mission_id),
            SipMessage::MissionComplete { mission_id, .. } => format!("mission.{}", mission_id),
            SipMessage::MissionFail { mission_id, .. } => format!("mission.{}", mission_id),
            SipMessage::AgentSpawn { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::AgentTerminate { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::AgentHeartbeat { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::AgentMetrics { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::AgentLog { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::ResourceAllocate { .. } => "global".to_string(),
            SipMessage::ResourceRelease { .. } => "global".to_string(),
            SipMessage::ResourceStatus { .. } => "global".to_string(),
            SipMessage::TaskAssign { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::TaskRevoke { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::TaskProgress { task_id, .. } => format!("task.{}", task_id),
            SipMessage::QueryRequest { .. } => "global".to_string(),
            SipMessage::QueryResponse { .. } => "global".to_string(),
            SipMessage::EventBroadcast { .. } => "global".to_string(),
            SipMessage::StateSnapshot { .. } => "global".to_string(),
            SipMessage::LockAcquire { .. } => "global".to_string(),
            SipMessage::LockRelease { .. } => "global".to_string(),
            SipMessage::CacheSet { .. } => "global".to_string(),
            SipMessage::CacheGet { .. } => "global".to_string(),
            SipMessage::CacheInvalidate { .. } => "global".to_string(),
            SipMessage::ConfigUpdate { .. } => "global".to_string(),
            SipMessage::AuthTokenRequest { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::AuthTokenResponse { agent_id, .. } => format!("agent.{}", agent_id),
            SipMessage::DiscoveryAnnounce { .. } => "global".to_string(),
            SipMessage::DiscoveryLookup { .. } => "global".to_string(),
            SipMessage::MetricRecord { .. } => "global".to_string(),
            SipMessage::AlertTrigger { .. } => "global".to_string(),
            SipMessage::AlertResolve { .. } => "global".to_string(),
            SipMessage::PolicyEvaluate { .. } => "global".to_string(),
            SipMessage::PolicyResult { .. } => "global".to_string(),
            SipMessage::DataSyncRequest { .. } => "global".to_string(),
            SipMessage::DataSyncAck { .. } => "global".to_string(),
            SipMessage::PluginLoad { .. } => "global".to_string(),
            SipMessage::PluginUnload { .. } => "global".to_string(),
            SipMessage::PluginStatus { .. } => "global".to_string(),
            SipMessage::ExtensionMessage1 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage2 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage3 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage4 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage5 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage6 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage7 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage8 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage9 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage10 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage11 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage12 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage13 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage14 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage15 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage16 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage17 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage18 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage19 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage20 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage21 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage22 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage23 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage24 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage25 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage26 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage27 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage28 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage29 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage30 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage31 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage32 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage33 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage34 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage35 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage36 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage37 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage38 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage39 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage40 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage41 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage42 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage43 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage44 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage45 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage46 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage47 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage48 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage49 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage50 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage51 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage52 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage53 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage54 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage55 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage56 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage57 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage58 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage59 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage60 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage61 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage62 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage63 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage64 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage65 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage66 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage67 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage68 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage69 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage70 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage71 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage72 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage73 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage74 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage75 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage76 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage77 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage78 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage79 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage80 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage81 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage82 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage83 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage84 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage85 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage86 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage87 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage88 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage89 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage90 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage91 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage92 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage93 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage94 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage95 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage96 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage97 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage98 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage99 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage100 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage101 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage102 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage103 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage104 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage105 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage106 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage107 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage108 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage109 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage110 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage111 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage112 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage113 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage114 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage115 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage116 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage117 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage118 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage119 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage120 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage121 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage122 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage123 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage124 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage125 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage126 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage127 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage128 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage129 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage130 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage131 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage132 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage133 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage134 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage135 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage136 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage137 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage138 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage139 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage140 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage141 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage142 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage143 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage144 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage145 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage146 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage147 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage148 { ext_id, .. } => format!("ext.{}", ext_id),
            SipMessage::ExtensionMessage149 { ext_id, .. } => format!("ext.{}", ext_id),

        }
    }
}
