load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "monitoring",
    srcs = ["metrics.go"],
    importpath = "ohc/server/monitoring",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//attribute",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)

go_test(
    name = "monitoring_test",
    srcs = ["metrics_test.go"],
    embed = [":monitoring"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_prometheus_client_golang//prometheus",
    ],
)
