load("@rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "server",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/memory:memory",
        "//srcs/server/onboarding:onboarding",
        "//srcs/server/orchestration:orchestration",
        "@com_github_mattn_go_sqlite3//:go_sqlite3",
    ],
)
