load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "harness",
    srcs = [
        "harness.go",
        "proxy.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/harness",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "harness_test",
    srcs = [
        "harness_test.go",
        "proxy_test.go",
    ],
    embed = [":harness"],
)
