load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "billing",
    srcs = [
        "postgres_tracker.go",
        "repository.go",
        "sqlite_tracker.go",
        "tracker.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/billing",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
        "//srcs/server/telemetry",
    ],
)

go_test(
    name = "billing_test",
    srcs = [
        "burn_rate_test.go",
        "tracker_test.go",
    ],
    embed = [":billing"],
)
