load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "shipengine",
    srcs = [
        "mod.rs",
        "provider.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/common:server_common",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tracing",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ]
)

rust_test(
    name = "shipengine_test",
    crate = ":shipengine",
    edition = "2024",
    deps = [
        "@crates//:tokio",
    ],
)
