load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "bash_sandbox",
    srcs = ["linux_sandbox.go"],
    importpath = "onehumancorp/srcs/server/bash_sandbox",
    visibility = ["//visibility:public"],
)

go_test(
    name = "bash_sandbox_test",
    srcs = ["linux_sandbox_test.go"],
    embed = [":bash_sandbox"],
)
