[package]
name = "server_integrations_zoom"
version = "0.1.0"
edition = "2024"

[lib]
path = "mod.rs"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
server_integrations_core = { version = "0.1.0", path = "../core" }
