import 'package:app/providers/wizard_provider.dart';
import 'package:app/services/api_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:app/main.dart';
import 'package:app/screens/business_setup_wizard_screen.dart';

class MockApiService extends ApiService {
  @override
  Future<Map<String, dynamic>?> getState(String tenantId) async {
    return null;
  }

  @override
  Future<void> saveState(Map<String, dynamic> state, String tenantId) async {
    // Mock save
  }

  @override
  Future<void> submitBusinessData(Map<String, dynamic> data) async {
    // Mock submit
  }

  @override
  Future<String> autoGenerateDescription(String productName) async {
    await Future.delayed(const Duration(seconds: 1));
    return 'A fantastic AI-generated description for $productName!';
  }
}

void main() {
  group('Wizard Provider Unit Tests', () {
    testWidgets('Wizard State Updates and Step Navigation', (WidgetTester tester) async {
      final container = ProviderContainer();
      container.read(wizardProvider.notifier).setApiService(MockApiService());
      await tester.pumpWidget(
        UncontrolledProviderScope(
          container: container,
          child: Consumer(
            builder: (context, ref, child) {
              final state = ref.watch(wizardProvider);
              final notifier = ref.read(wizardProvider.notifier);

              return MaterialApp(
                home: Scaffold(
                  body: Column(
                    children: [
                      Text('Step: ${state.currentStep}'),
                      Text('Company: ${state.companyName}'),
                      Text('Template: ${state.templateSelection}'),
                      ElevatedButton(
                        key: const Key('nextBtn'),
                        onPressed: () => notifier.nextStep(),
                        child: const Text('Next'),
                      ),
                      ElevatedButton(
                        key: const Key('updateProfileBtn'),
                        onPressed: () => notifier.updateBusinessProfile(companyName: 'Acme Corp'),
                        child: const Text('Update Profile'),
                      ),
                      ElevatedButton(
                        key: const Key('setTemplateBtn'),
                        onPressed: () => notifier.setTemplateSelection('Modern'),
                        child: const Text('Set Template'),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      );

      // Initial state
      expect(find.text('Step: 0'), findsOneWidget);
      expect(find.text('Company: null'), findsOneWidget);

      // Trigger next step
      await tester.tap(find.byKey(const Key('nextBtn')));
      await tester.pump();
      expect(find.text('Step: 1'), findsOneWidget);

      // Update business profile
      await tester.tap(find.byKey(const Key('updateProfileBtn')));
      await tester.pump();
      expect(find.text('Company: Acme Corp'), findsOneWidget);

      // Update template selection
      await tester.tap(find.byKey(const Key('setTemplateBtn')));
      await tester.pump();
      expect(find.text('Template: Modern'), findsOneWidget);
    });
  });

  group('Wizard Features testing', () {
    testWidgets('Wizard toggles goals and deployment preferences', (WidgetTester tester) async {
      final container = ProviderContainer();
      container.read(wizardProvider.notifier).setApiService(MockApiService());
      await tester.pumpWidget(
        UncontrolledProviderScope(
          container: container,
          child: Consumer(
            builder: (context, ref, child) {
              final state = ref.watch(wizardProvider);
              final notifier = ref.read(wizardProvider.notifier);

              return MaterialApp(
                home: Scaffold(
                  body: Column(
                    children: [
                      Text('Goals: ${state.goals.join(', ')}', key: const Key('goalsText')),
                      Text('Deployment: ${state.deploymentPreference}', key: const Key('deploymentText')),
                      ElevatedButton(
                        key: const Key('toggleGoalBtn'),
                        onPressed: () => notifier.toggleGoal('Build software'),
                        child: const Text('Toggle Goal'),
                      ),
                      ElevatedButton(
                        key: const Key('setDeploymentBtn'),
                        onPressed: () => notifier.setDeploymentPreference('Cloud'),
                        child: const Text('Set Deployment'),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      );

      // Initial state
      expect(find.text('Goals: '), findsOneWidget);
      expect(find.text('Deployment: null'), findsOneWidget);

      // Toggle goal on
      await tester.tap(find.byKey(const Key('toggleGoalBtn')));
      await tester.pump();
      expect(find.text('Goals: Build software'), findsOneWidget);

      // Toggle goal off
      await tester.tap(find.byKey(const Key('toggleGoalBtn')));
      await tester.pump();
      expect(find.text('Goals: '), findsOneWidget);

      // Set deployment
      await tester.tap(find.byKey(const Key('setDeploymentBtn')));
      await tester.pump();
      expect(find.text('Deployment: Cloud'), findsOneWidget);
    });
  });

  group('BusinessSetupWizardScreen Flow Tests', () {
    testWidgets('Wizard progression to Dashboard (3 steps)', (WidgetTester tester) async {
      final container = ProviderContainer();
      container.read(wizardProvider.notifier).setApiService(MockApiService());
      await tester.pumpWidget(
        UncontrolledProviderScope(
          container: container,
          child: const MaterialApp(
            home: BusinessSetupWizardScreen(environmentMode: EnvironmentMode.cloud),
          ),
        ),
      );

      // 1. Welcome Screen
      final emailField = find.byKey(const Key('signupEmailField'));
      await tester.ensureVisible(emailField);
      await tester.enterText(emailField, 'test@test.com');
      await tester.enterText(find.byKey(const Key('signupPasswordField')), 'pw');
      final signupBtn = find.byKey(const Key('signupBtn'));
      await tester.ensureVisible(signupBtn);
      await tester.tap(signupBtn);
      await tester.pump(const Duration(milliseconds: 500));

      // 2. Product Configuration
      await tester.enterText(find.byKey(const Key('productNameField')), 'Cool Widget');
      await tester.tap(find.byType(ElevatedButton).last); // Next
      await tester.pump(const Duration(milliseconds: 500));

      // 3. Review & Launch -> Launch My Business
      final launchBtn = find.byKey(const Key('launchAIBtn'));
      await tester.ensureVisible(launchBtn);
      await tester.tap(launchBtn);
      await tester.pump(const Duration(milliseconds: 500));

      // After launch, we proceed to Dashboard (main layout). Because this is just the wizard screen standalone,
      // it won't actually push a new route if we didn't mock the router, but the state will be 3.
      await tester.pump(const Duration(seconds: 2));

      final state = container.read(wizardProvider);
      expect(state.currentStep, 3);
    });
  });
}
