import 'package:app/providers/wizard_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:app/services/api_service.dart';
import 'package:app/main.dart';


class MockApiService implements ApiService {
  @override
  Future<String> autoGenerateDescription(String productName) async {
    return 'Generated description for $productName';
  }

  @override
  Future<void> submitBusinessData(Map<String, dynamic> data) async {}

  @override
  Future<void> saveState(Map<String, dynamic> state, String tenantId) async {}

  @override
  Future<Map<String, dynamic>?> getState(String tenantId) async {
    return null;
  }
}

void main() {
  testWidgets('Business Setup Wizard E2E test', (WidgetTester tester) async {
    // Build our app and trigger a frame.

    final mockApiService = MockApiService();

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          wizardProvider.overrideWith(() {
             final notifier = WizardNotifier();
             notifier.setApiService(mockApiService);
             return notifier;
          }),
        ],
        child: const OHCApp(),
      ),
    );


    // 1. Welcome Screen
    expect(find.text('Welcome to One Human Corp'), findsOneWidget);
    final emailField = find.byKey(const Key('signupEmailField'));
    await tester.ensureVisible(emailField);
    await tester.enterText(emailField, 'newuser@example.com');
    await tester.enterText(find.byKey(const Key('signupPasswordField')), 'password123');

    // Select Industry
    final industryDropdown = find.byKey(const Key('industryDropdown'));
    if (industryDropdown.evaluate().isNotEmpty) {
      await tester.ensureVisible(industryDropdown);
      await tester.tap(industryDropdown);
      await tester.pump(const Duration(milliseconds: 500));
      await tester.tap(find.text('Technology').last);
      await tester.pump(const Duration(milliseconds: 500));
    }

    final signupBtn = find.byKey(const Key('signupBtn'));
    await tester.ensureVisible(signupBtn);
    await tester.tap(signupBtn);
    await tester.pump(const Duration(milliseconds: 500));

    // 2. Product Screen
    expect(find.text('Add your first product or service'), findsOneWidget);
    await tester.enterText(find.byKey(const Key('productNameField')), 'Acme Product');
    await tester.tap(find.byType(ElevatedButton).last);
    await tester.pump(const Duration(milliseconds: 500));

    // 3. Review & Launch Screen
    expect(find.text('Review & Launch'), findsOneWidget);
    expect(find.text('Acme Product'), findsOneWidget);

    final launchBtn = find.byKey(const Key('launchAIBtn'));
    await tester.ensureVisible(launchBtn);
    await tester.tap(launchBtn);
    await tester.pump();

    // Wait for the simulated API call (2 seconds)
    await tester.pump(const Duration(seconds: 2));
    await tester.pump(const Duration(seconds: 1));

    // 4. Checklist
    expect(find.text("You're set up!"), findsOneWidget);
    final gotoDashboardBtn = find.text('Go to Dashboard');
    await tester.ensureVisible(gotoDashboardBtn);
    await tester.tap(gotoDashboardBtn);
    await tester.pump(const Duration(milliseconds: 500));

    // Wait for route transition
    await tester.pump(const Duration(seconds: 1));

    // 5. Dashboard Screen
    expect(find.text("Dashboard"), findsOneWidget);
    expect(find.text("Welcome Checklist"), findsOneWidget);
    expect(find.text("Business live"), findsOneWidget);
    expect(find.text("Add 3 more products"), findsOneWidget);
    expect(find.text("Connect Instagram"), findsOneWidget);
    expect(find.text("Share your link with a friend"), findsOneWidget);

    // Check for the milestone notification before the Pending Agent Approvals
    expect(find.text("🎉 You just got your 10th order!"), findsOneWidget);

    // We scroll down to find the remaining widgets that might be off screen
    await tester.drag(find.byType(ListView).first, const Offset(0, -500));
    await tester.pump();

    expect(find.text("Pending Agent Approvals"), findsOneWidget);
  });
}
