load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "simulator_lib",
    srcs = ["main.go"],
    importpath = "github.com/onehumancorp/mono/apps/growth/simulator",
    visibility = ["//visibility:private"],
    deps = [
        "//services/growth/referrals",
        "@org_modernc_sqlite//:sqlite",
    ],
)

go_binary(
    name = "simulator",
    embed = [":simulator_lib"],
    visibility = ["//visibility:public"],
)
