# Copyright 2026 Author(s) of OHC
# SPDX-License-Identifier: Apache-2.0

load("//srcs/tests/e2e:playwright_tests.bzl", "define_playwright_tests")

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "*.ts",
            "*.d.ts",
            "*.json",
        ],
        exclude = ["*.spec.ts"],
    ),
    visibility = ["//visibility:public"],
)

define_playwright_tests()
