load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "statemachine",
    srcs = ["machine.go"],
    importpath = "github.com/onehumancorp/mono/src/server/orchestration/statemachine",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
        "//src/server/orchestration/kairos",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_redis_rueidis//:rueidis",
    ],
)

go_test(
    name = "statemachine_test",
    srcs = ["machine_test.go"],
    embed = [":statemachine"],
    deps = [
        "//src/server/db",
        "@org_modernc_sqlite//:sqlite",
    ],
)
