load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sandbox",
    srcs = ["scrubber.go"],
    importpath = "github.com/onehumancorp/mono/src/server/harness/sandbox",
    visibility = ["//visibility:public"],
    deps = ["//src/server/harness"],
)

go_test(
    name = "sandbox_test",
    srcs = ["scrubber_test.go"],
    embed = [":sandbox"],
    deps = ["//src/server/harness"],
)
