// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/app.proto

package apiv1

import (
	agent "github.com/onehumancorp/mono/srcs/proto/ohc/agent"
	billing "github.com/onehumancorp/mono/srcs/proto/ohc/billing"
	organization "github.com/onehumancorp/mono/srcs/proto/ohc/organization"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeetingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Participants  []string               `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	Transcript    []*agent.AgentMessage  `protobuf:"bytes,3,rep,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoom) Reset() {
	*x = MeetingRoom{}
	mi := &file_proto_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoom) ProtoMessage() {}

func (x *MeetingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoom.ProtoReflect.Descriptor instead.
func (*MeetingRoom) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{0}
}

func (x *MeetingRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeetingRoom) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *MeetingRoom) GetTranscript() []*agent.AgentMessage {
	if x != nil {
		return x.Transcript
	}
	return nil
}

type StatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCount) Reset() {
	*x = StatusCount{}
	mi := &file_proto_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCount) ProtoMessage() {}

func (x *StatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCount.ProtoReflect.Descriptor instead.
func (*StatusCount) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{1}
}

func (x *StatusCount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DashboardSnapshot struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Organization  *organization.Organization `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Agents        []*agent.Agent             `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	Meetings      []*MeetingRoom             `protobuf:"bytes,3,rep,name=meetings,proto3" json:"meetings,omitempty"`
	CostSummary   *billing.CostSummary       `protobuf:"bytes,4,opt,name=cost_summary,json=costSummary,proto3" json:"cost_summary,omitempty"`
	Statuses      []*StatusCount             `protobuf:"bytes,5,rep,name=statuses,proto3" json:"statuses,omitempty"`
	UpdatedAt     string                     `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSnapshot) Reset() {
	*x = DashboardSnapshot{}
	mi := &file_proto_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSnapshot) ProtoMessage() {}

func (x *DashboardSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSnapshot.ProtoReflect.Descriptor instead.
func (*DashboardSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardSnapshot) GetOrganization() *organization.Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *DashboardSnapshot) GetAgents() []*agent.Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *DashboardSnapshot) GetMeetings() []*MeetingRoom {
	if x != nil {
		return x.Meetings
	}
	return nil
}

func (x *DashboardSnapshot) GetCostSummary() *billing.CostSummary {
	if x != nil {
		return x.CostSummary
	}
	return nil
}

func (x *DashboardSnapshot) GetStatuses() []*StatusCount {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *DashboardSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDashboardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_proto_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{3}
}

func (x *GetDashboardRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *agent.AgentMessage    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{4}
}

func (x *PostMessageRequest) GetMessage() *agent.AgentMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type PostMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *DashboardSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_proto_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{5}
}

func (x *PostMessageResponse) GetSnapshot() *DashboardSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SeedDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      string                 `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedDashboardRequest) Reset() {
	*x = SeedDashboardRequest{}
	mi := &file_proto_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedDashboardRequest) ProtoMessage() {}

func (x *SeedDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedDashboardRequest.ProtoReflect.Descriptor instead.
func (*SeedDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{6}
}

func (x *SeedDashboardRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

type SeedDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *DashboardSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedDashboardResponse) Reset() {
	*x = SeedDashboardResponse{}
	mi := &file_proto_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedDashboardResponse) ProtoMessage() {}

func (x *SeedDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedDashboardResponse.ProtoReflect.Descriptor instead.
func (*SeedDashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{7}
}

func (x *SeedDashboardResponse) GetSnapshot() *DashboardSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// B2B Collaboration messages
type TrustAgreement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PartnerOrg     string                 `protobuf:"bytes,2,opt,name=partner_org,json=partnerOrg,proto3" json:"partner_org,omitempty"`
	PartnerJwksUrl string                 `protobuf:"bytes,3,opt,name=partner_jwks_url,json=partnerJwksUrl,proto3" json:"partner_jwks_url,omitempty"`
	AllowedRoles   []string               `protobuf:"bytes,4,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // PENDING, ACTIVE, REVOKED
	CreatedAtUnix  int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrustAgreement) Reset() {
	*x = TrustAgreement{}
	mi := &file_proto_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAgreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAgreement) ProtoMessage() {}

func (x *TrustAgreement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAgreement.ProtoReflect.Descriptor instead.
func (*TrustAgreement) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{8}
}

func (x *TrustAgreement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrustAgreement) GetPartnerOrg() string {
	if x != nil {
		return x.PartnerOrg
	}
	return ""
}

func (x *TrustAgreement) GetPartnerJwksUrl() string {
	if x != nil {
		return x.PartnerJwksUrl
	}
	return ""
}

func (x *TrustAgreement) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

func (x *TrustAgreement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrustAgreement) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type B2BHandshakeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartnerOrg     string                 `protobuf:"bytes,1,opt,name=partner_org,json=partnerOrg,proto3" json:"partner_org,omitempty"`
	PartnerJwksUrl string                 `protobuf:"bytes,2,opt,name=partner_jwks_url,json=partnerJwksUrl,proto3" json:"partner_jwks_url,omitempty"`
	AllowedRoles   []string               `protobuf:"bytes,3,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *B2BHandshakeRequest) Reset() {
	*x = B2BHandshakeRequest{}
	mi := &file_proto_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B2BHandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2BHandshakeRequest) ProtoMessage() {}

func (x *B2BHandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2BHandshakeRequest.ProtoReflect.Descriptor instead.
func (*B2BHandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{9}
}

func (x *B2BHandshakeRequest) GetPartnerOrg() string {
	if x != nil {
		return x.PartnerOrg
	}
	return ""
}

func (x *B2BHandshakeRequest) GetPartnerJwksUrl() string {
	if x != nil {
		return x.PartnerJwksUrl
	}
	return ""
}

func (x *B2BHandshakeRequest) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

// Incident / SRE messages
type Incident struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity          string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // P0, P1, P2
	Summary           string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	RootCauseAnalysis string                 `protobuf:"bytes,4,opt,name=root_cause_analysis,json=rootCauseAnalysis,proto3" json:"root_cause_analysis,omitempty"`
	ResolutionPlanId  string                 `protobuf:"bytes,5,opt,name=resolution_plan_id,json=resolutionPlanId,proto3" json:"resolution_plan_id,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // INVESTIGATING, PROPOSED, RESOLVED
	CreatedAtUnix     int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_proto_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{10}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Incident) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Incident) GetRootCauseAnalysis() string {
	if x != nil {
		return x.RootCauseAnalysis
	}
	return ""
}

func (x *Incident) GetResolutionPlanId() string {
	if x != nil {
		return x.ResolutionPlanId
	}
	return ""
}

func (x *Incident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Incident) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type IncidentStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncidentId       string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResolutionPlanId string                 `protobuf:"bytes,3,opt,name=resolution_plan_id,json=resolutionPlanId,proto3" json:"resolution_plan_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IncidentStatusRequest) Reset() {
	*x = IncidentStatusRequest{}
	mi := &file_proto_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentStatusRequest) ProtoMessage() {}

func (x *IncidentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentStatusRequest.ProtoReflect.Descriptor instead.
func (*IncidentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{11}
}

func (x *IncidentStatusRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IncidentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IncidentStatusRequest) GetResolutionPlanId() string {
	if x != nil {
		return x.ResolutionPlanId
	}
	return ""
}

// Compute Optimization messages
type ComputeProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoleId             string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MinVramGb          int32                  `protobuf:"varint,2,opt,name=min_vram_gb,json=minVramGb,proto3" json:"min_vram_gb,omitempty"`
	PreferredGpuType   string                 `protobuf:"bytes,3,opt,name=preferred_gpu_type,json=preferredGpuType,proto3" json:"preferred_gpu_type,omitempty"` // "h100", "a10g"
	SchedulingPriority int32                  `protobuf:"varint,4,opt,name=scheduling_priority,json=schedulingPriority,proto3" json:"scheduling_priority,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComputeProfile) Reset() {
	*x = ComputeProfile{}
	mi := &file_proto_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeProfile) ProtoMessage() {}

func (x *ComputeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeProfile.ProtoReflect.Descriptor instead.
func (*ComputeProfile) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{12}
}

func (x *ComputeProfile) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ComputeProfile) GetMinVramGb() int32 {
	if x != nil {
		return x.MinVramGb
	}
	return 0
}

func (x *ComputeProfile) GetPreferredGpuType() string {
	if x != nil {
		return x.PreferredGpuType
	}
	return ""
}

func (x *ComputeProfile) GetSchedulingPriority() int32 {
	if x != nil {
		return x.SchedulingPriority
	}
	return 0
}

type ClusterStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, offline
	LatencyMs      int32                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	AvailableNodes int32                  `protobuf:"varint,4,opt,name=available_nodes,json=availableNodes,proto3" json:"available_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_proto_app_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{13}
}

func (x *ClusterStatus) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterStatus) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ClusterStatus) GetAvailableNodes() int32 {
	if x != nil {
		return x.AvailableNodes
	}
	return 0
}

// Pipeline / SDLC messages
type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // PENDING, IMPLEMENTING, TESTING, STAGING, PROMOTED, FAILED
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	StagingUrl    string                 `protobuf:"bytes,5,opt,name=staging_url,json=stagingUrl,proto3" json:"staging_url,omitempty"`
	InitiatedBy   string                 `protobuf:"bytes,6,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,8,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_proto_app_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{14}
}

func (x *Pipeline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pipeline) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Pipeline) GetStagingUrl() string {
	if x != nil {
		return x.StagingUrl
	}
	return ""
}

func (x *Pipeline) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *Pipeline) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Pipeline) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type PipelinePromoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelinePromoteRequest) Reset() {
	*x = PipelinePromoteRequest{}
	mi := &file_proto_app_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelinePromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelinePromoteRequest) ProtoMessage() {}

func (x *PipelinePromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelinePromoteRequest.ProtoReflect.Descriptor instead.
func (*PipelinePromoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{15}
}

func (x *PipelinePromoteRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelinePromoteRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

var File_proto_app_proto protoreflect.FileDescriptor

const file_proto_app_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/app.proto\x12\n" +
	"ohc.api.v1\x1a\x11proto/agent.proto\x1a\x13proto/billing.proto\x1a\x18proto/organization.proto\"z\n" +
	"\vMeetingRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fparticipants\x18\x02 \x03(\tR\fparticipants\x127\n" +
	"\n" +
	"transcript\x18\x03 \x03(\v2\x17.ohc.agent.AgentMessageR\n" +
	"transcript\";\n" +
	"\vStatusCount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xc7\x02\n" +
	"\x11DashboardSnapshot\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.ohc.organization.OrganizationR\forganization\x12(\n" +
	"\x06agents\x18\x02 \x03(\v2\x10.ohc.agent.AgentR\x06agents\x123\n" +
	"\bmeetings\x18\x03 \x03(\v2\x17.ohc.api.v1.MeetingRoomR\bmeetings\x12;\n" +
	"\fcost_summary\x18\x04 \x01(\v2\x18.ohc.billing.CostSummaryR\vcostSummary\x123\n" +
	"\bstatuses\x18\x05 \x03(\v2\x17.ohc.api.v1.StatusCountR\bstatuses\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\">\n" +
	"\x13GetDashboardRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"G\n" +
	"\x12PostMessageRequest\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.ohc.agent.AgentMessageR\amessage\"P\n" +
	"\x13PostMessageResponse\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1d.ohc.api.v1.DashboardSnapshotR\bsnapshot\"2\n" +
	"\x14SeedDashboardRequest\x12\x1a\n" +
	"\bscenario\x18\x01 \x01(\tR\bscenario\"R\n" +
	"\x15SeedDashboardResponse\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1d.ohc.api.v1.DashboardSnapshotR\bsnapshot\"\xd0\x01\n" +
	"\x0eTrustAgreement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpartner_org\x18\x02 \x01(\tR\n" +
	"partnerOrg\x12(\n" +
	"\x10partner_jwks_url\x18\x03 \x01(\tR\x0epartnerJwksUrl\x12#\n" +
	"\rallowed_roles\x18\x04 \x03(\tR\fallowedRoles\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\"\x85\x01\n" +
	"\x13B2BHandshakeRequest\x12\x1f\n" +
	"\vpartner_org\x18\x01 \x01(\tR\n" +
	"partnerOrg\x12(\n" +
	"\x10partner_jwks_url\x18\x02 \x01(\tR\x0epartnerJwksUrl\x12#\n" +
	"\rallowed_roles\x18\x03 \x03(\tR\fallowedRoles\"\xee\x01\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12.\n" +
	"\x13root_cause_analysis\x18\x04 \x01(\tR\x11rootCauseAnalysis\x12,\n" +
	"\x12resolution_plan_id\x18\x05 \x01(\tR\x10resolutionPlanId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\"~\n" +
	"\x15IncidentStatusRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12resolution_plan_id\x18\x03 \x01(\tR\x10resolutionPlanId\"\xa8\x01\n" +
	"\x0eComputeProfile\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1e\n" +
	"\vmin_vram_gb\x18\x02 \x01(\x05R\tminVramGb\x12,\n" +
	"\x12preferred_gpu_type\x18\x03 \x01(\tR\x10preferredGpuType\x12/\n" +
	"\x13scheduling_priority\x18\x04 \x01(\x05R\x12schedulingPriority\"\x87\x01\n" +
	"\rClusterStatus\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x05R\tlatencyMs\x12'\n" +
	"\x0favailable_nodes\x18\x04 \x01(\x05R\x0eavailableNodes\"\xf2\x01\n" +
	"\bPipeline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x1f\n" +
	"\vstaging_url\x18\x05 \x01(\tR\n" +
	"stagingUrl\x12!\n" +
	"\finitiated_by\x18\x06 \x01(\tR\vinitiatedBy\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\b \x01(\x03R\rupdatedAtUnix\"Z\n" +
	"\x16PipelinePromoteRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy2\x88\x02\n" +
	"\x10DashboardService\x12N\n" +
	"\fGetDashboard\x12\x1f.ohc.api.v1.GetDashboardRequest\x1a\x1d.ohc.api.v1.DashboardSnapshot\x12N\n" +
	"\vPostMessage\x12\x1e.ohc.api.v1.PostMessageRequest\x1a\x1f.ohc.api.v1.PostMessageResponse\x12T\n" +
	"\rSeedDashboard\x12 .ohc.api.v1.SeedDashboardRequest\x1a!.ohc.api.v1.SeedDashboardResponseB:Z8github.com/onehumancorp/mono/srcs/proto/ohc/api/v1;apiv1b\x06proto3"

var (
	file_proto_app_proto_rawDescOnce sync.Once
	file_proto_app_proto_rawDescData []byte
)

func file_proto_app_proto_rawDescGZIP() []byte {
	file_proto_app_proto_rawDescOnce.Do(func() {
		file_proto_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_proto_rawDesc), len(file_proto_app_proto_rawDesc)))
	})
	return file_proto_app_proto_rawDescData
}

var file_proto_app_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_app_proto_goTypes = []any{
	(*MeetingRoom)(nil),               // 0: ohc.api.v1.MeetingRoom
	(*StatusCount)(nil),               // 1: ohc.api.v1.StatusCount
	(*DashboardSnapshot)(nil),         // 2: ohc.api.v1.DashboardSnapshot
	(*GetDashboardRequest)(nil),       // 3: ohc.api.v1.GetDashboardRequest
	(*PostMessageRequest)(nil),        // 4: ohc.api.v1.PostMessageRequest
	(*PostMessageResponse)(nil),       // 5: ohc.api.v1.PostMessageResponse
	(*SeedDashboardRequest)(nil),      // 6: ohc.api.v1.SeedDashboardRequest
	(*SeedDashboardResponse)(nil),     // 7: ohc.api.v1.SeedDashboardResponse
	(*TrustAgreement)(nil),            // 8: ohc.api.v1.TrustAgreement
	(*B2BHandshakeRequest)(nil),       // 9: ohc.api.v1.B2BHandshakeRequest
	(*Incident)(nil),                  // 10: ohc.api.v1.Incident
	(*IncidentStatusRequest)(nil),     // 11: ohc.api.v1.IncidentStatusRequest
	(*ComputeProfile)(nil),            // 12: ohc.api.v1.ComputeProfile
	(*ClusterStatus)(nil),             // 13: ohc.api.v1.ClusterStatus
	(*Pipeline)(nil),                  // 14: ohc.api.v1.Pipeline
	(*PipelinePromoteRequest)(nil),    // 15: ohc.api.v1.PipelinePromoteRequest
	(*agent.AgentMessage)(nil),        // 16: ohc.agent.AgentMessage
	(*organization.Organization)(nil), // 17: ohc.organization.Organization
	(*agent.Agent)(nil),               // 18: ohc.agent.Agent
	(*billing.CostSummary)(nil),       // 19: ohc.billing.CostSummary
}
var file_proto_app_proto_depIdxs = []int32{
	16, // 0: ohc.api.v1.MeetingRoom.transcript:type_name -> ohc.agent.AgentMessage
	17, // 1: ohc.api.v1.DashboardSnapshot.organization:type_name -> ohc.organization.Organization
	18, // 2: ohc.api.v1.DashboardSnapshot.agents:type_name -> ohc.agent.Agent
	0,  // 3: ohc.api.v1.DashboardSnapshot.meetings:type_name -> ohc.api.v1.MeetingRoom
	19, // 4: ohc.api.v1.DashboardSnapshot.cost_summary:type_name -> ohc.billing.CostSummary
	1,  // 5: ohc.api.v1.DashboardSnapshot.statuses:type_name -> ohc.api.v1.StatusCount
	16, // 6: ohc.api.v1.PostMessageRequest.message:type_name -> ohc.agent.AgentMessage
	2,  // 7: ohc.api.v1.PostMessageResponse.snapshot:type_name -> ohc.api.v1.DashboardSnapshot
	2,  // 8: ohc.api.v1.SeedDashboardResponse.snapshot:type_name -> ohc.api.v1.DashboardSnapshot
	3,  // 9: ohc.api.v1.DashboardService.GetDashboard:input_type -> ohc.api.v1.GetDashboardRequest
	4,  // 10: ohc.api.v1.DashboardService.PostMessage:input_type -> ohc.api.v1.PostMessageRequest
	6,  // 11: ohc.api.v1.DashboardService.SeedDashboard:input_type -> ohc.api.v1.SeedDashboardRequest
	2,  // 12: ohc.api.v1.DashboardService.GetDashboard:output_type -> ohc.api.v1.DashboardSnapshot
	5,  // 13: ohc.api.v1.DashboardService.PostMessage:output_type -> ohc.api.v1.PostMessageResponse
	7,  // 14: ohc.api.v1.DashboardService.SeedDashboard:output_type -> ohc.api.v1.SeedDashboardResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_app_proto_init() }
func file_proto_app_proto_init() {
	if File_proto_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_proto_rawDesc), len(file_proto_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_proto_goTypes,
		DependencyIndexes: file_proto_app_proto_depIdxs,
		MessageInfos:      file_proto_app_proto_msgTypes,
	}.Build()
	File_proto_app_proto = out.File
	file_proto_app_proto_goTypes = nil
	file_proto_app_proto_depIdxs = nil
}
