load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library")

js_library(
    name = "lib",
    srcs = [
        "src/App.test.tsx",
        "src/App.tsx",
        "src/index.tsx",
        "package.json",
        "tsconfig.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/cli/src/components",
        "//src/cli/src/hooks",
    ],
)

js_binary(
    name = "cli",
    data = [
        ":lib",
        "//:node_modules",
    ],
    entry_point = "src/index.tsx",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
