// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/skills.proto

package skillspb

import (
	common "github.com/onehumancorp/mono/srcs/proto/ohc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Phase represents a single execution step in a multi-phase agent prompt.
type Phase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProtocolDetails string                 `protobuf:"bytes,3,opt,name=protocol_details,json=protocolDetails,proto3" json:"protocol_details,omitempty"` // Detailed instructions for this phase.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Phase) Reset() {
	*x = Phase{}
	mi := &file_proto_skills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phase) ProtoMessage() {}

func (x *Phase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phase.ProtoReflect.Descriptor instead.
func (*Phase) Descriptor() ([]byte, []int) {
	return file_proto_skills_proto_rawDescGZIP(), []int{0}
}

func (x *Phase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Phase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Phase) GetProtocolDetails() string {
	if x != nil {
		return x.ProtocolDetails
	}
	return ""
}

// A RoleBlueprint defines the identity and prompt structure for a specialized agent.
type RoleBlueprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoleArchetype common.Role            `protobuf:"varint,3,opt,name=role_archetype,json=roleArchetype,proto3,enum=ohc.common.Role" json:"role_archetype,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"` // e.g., "L7", "Senior"
	Objective     string                 `protobuf:"bytes,5,opt,name=objective,proto3" json:"objective,omitempty"`
	Phases        []*Phase               `protobuf:"bytes,6,rep,name=phases,proto3" json:"phases,omitempty"`
	Constraints   []string               `protobuf:"bytes,7,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBlueprint) Reset() {
	*x = RoleBlueprint{}
	mi := &file_proto_skills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBlueprint) ProtoMessage() {}

func (x *RoleBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBlueprint.ProtoReflect.Descriptor instead.
func (*RoleBlueprint) Descriptor() ([]byte, []int) {
	return file_proto_skills_proto_rawDescGZIP(), []int{1}
}

func (x *RoleBlueprint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleBlueprint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleBlueprint) GetRoleArchetype() common.Role {
	if x != nil {
		return x.RoleArchetype
	}
	return common.Role(0)
}

func (x *RoleBlueprint) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *RoleBlueprint) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *RoleBlueprint) GetPhases() []*Phase {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *RoleBlueprint) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// A SystemPromptBlueprint defines how the global goal and project context are injected.
type SystemPromptBlueprint struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CoreDirective            string                 `protobuf:"bytes,1,opt,name=core_directive,json=coreDirective,proto3" json:"core_directive,omitempty"`
	RequiredContextVariables []string               `protobuf:"bytes,2,rep,name=required_context_variables,json=requiredContextVariables,proto3" json:"required_context_variables,omitempty"` // e.g., ["PROJECT_NAME", "STRATEGIC_DIRECTIVE"]
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SystemPromptBlueprint) Reset() {
	*x = SystemPromptBlueprint{}
	mi := &file_proto_skills_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemPromptBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemPromptBlueprint) ProtoMessage() {}

func (x *SystemPromptBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skills_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemPromptBlueprint.ProtoReflect.Descriptor instead.
func (*SystemPromptBlueprint) Descriptor() ([]byte, []int) {
	return file_proto_skills_proto_rawDescGZIP(), []int{2}
}

func (x *SystemPromptBlueprint) GetCoreDirective() string {
	if x != nil {
		return x.CoreDirective
	}
	return ""
}

func (x *SystemPromptBlueprint) GetRequiredContextVariables() []string {
	if x != nil {
		return x.RequiredContextVariables
	}
	return nil
}

// A TeamBlueprint is a collection of roles that form a functional department.
type TeamBlueprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamName      string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	SystemPrompt  *SystemPromptBlueprint `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Roles         []*RoleBlueprint       `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamBlueprint) Reset() {
	*x = TeamBlueprint{}
	mi := &file_proto_skills_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamBlueprint) ProtoMessage() {}

func (x *TeamBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skills_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamBlueprint.ProtoReflect.Descriptor instead.
func (*TeamBlueprint) Descriptor() ([]byte, []int) {
	return file_proto_skills_proto_rawDescGZIP(), []int{3}
}

func (x *TeamBlueprint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamBlueprint) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TeamBlueprint) GetSystemPrompt() *SystemPromptBlueprint {
	if x != nil {
		return x.SystemPrompt
	}
	return nil
}

func (x *TeamBlueprint) GetRoles() []*RoleBlueprint {
	if x != nil {
		return x.Roles
	}
	return nil
}

// SkillSet represents a library of reusable capabilities.
type SkillSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeamTemplates []*TeamBlueprint       `protobuf:"bytes,3,rep,name=team_templates,json=teamTemplates,proto3" json:"team_templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillSet) Reset() {
	*x = SkillSet{}
	mi := &file_proto_skills_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillSet) ProtoMessage() {}

func (x *SkillSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skills_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillSet.ProtoReflect.Descriptor instead.
func (*SkillSet) Descriptor() ([]byte, []int) {
	return file_proto_skills_proto_rawDescGZIP(), []int{4}
}

func (x *SkillSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillSet) GetTeamTemplates() []*TeamBlueprint {
	if x != nil {
		return x.TeamTemplates
	}
	return nil
}

var File_proto_skills_proto protoreflect.FileDescriptor

const file_proto_skills_proto_rawDesc = "" +
	"\n" +
	"\x12proto/skills.proto\x12\n" +
	"ohc.skills\x1a\x12proto/common.proto\"h\n" +
	"\x05Phase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10protocol_details\x18\x03 \x01(\tR\x0fprotocolDetails\"\xed\x01\n" +
	"\rRoleBlueprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\x0erole_archetype\x18\x03 \x01(\x0e2\x10.ohc.common.RoleR\rroleArchetype\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x1c\n" +
	"\tobjective\x18\x05 \x01(\tR\tobjective\x12)\n" +
	"\x06phases\x18\x06 \x03(\v2\x11.ohc.skills.PhaseR\x06phases\x12 \n" +
	"\vconstraints\x18\a \x03(\tR\vconstraints\"|\n" +
	"\x15SystemPromptBlueprint\x12%\n" +
	"\x0ecore_directive\x18\x01 \x01(\tR\rcoreDirective\x12<\n" +
	"\x1arequired_context_variables\x18\x02 \x03(\tR\x18requiredContextVariables\"\xb5\x01\n" +
	"\rTeamBlueprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12F\n" +
	"\rsystem_prompt\x18\x03 \x01(\v2!.ohc.skills.SystemPromptBlueprintR\fsystemPrompt\x12/\n" +
	"\x05roles\x18\x04 \x03(\v2\x19.ohc.skills.RoleBlueprintR\x05roles\"p\n" +
	"\bSkillSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12@\n" +
	"\x0eteam_templates\x18\x03 \x03(\v2\x19.ohc.skills.TeamBlueprintR\rteamTemplatesB=Z;github.com/onehumancorp/mono/srcs/proto/ohc/skills;skillspbb\x06proto3"

var (
	file_proto_skills_proto_rawDescOnce sync.Once
	file_proto_skills_proto_rawDescData []byte
)

func file_proto_skills_proto_rawDescGZIP() []byte {
	file_proto_skills_proto_rawDescOnce.Do(func() {
		file_proto_skills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_skills_proto_rawDesc), len(file_proto_skills_proto_rawDesc)))
	})
	return file_proto_skills_proto_rawDescData
}

var file_proto_skills_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_skills_proto_goTypes = []any{
	(*Phase)(nil),                 // 0: ohc.skills.Phase
	(*RoleBlueprint)(nil),         // 1: ohc.skills.RoleBlueprint
	(*SystemPromptBlueprint)(nil), // 2: ohc.skills.SystemPromptBlueprint
	(*TeamBlueprint)(nil),         // 3: ohc.skills.TeamBlueprint
	(*SkillSet)(nil),              // 4: ohc.skills.SkillSet
	(common.Role)(0),              // 5: ohc.common.Role
}
var file_proto_skills_proto_depIdxs = []int32{
	5, // 0: ohc.skills.RoleBlueprint.role_archetype:type_name -> ohc.common.Role
	0, // 1: ohc.skills.RoleBlueprint.phases:type_name -> ohc.skills.Phase
	2, // 2: ohc.skills.TeamBlueprint.system_prompt:type_name -> ohc.skills.SystemPromptBlueprint
	1, // 3: ohc.skills.TeamBlueprint.roles:type_name -> ohc.skills.RoleBlueprint
	3, // 4: ohc.skills.SkillSet.team_templates:type_name -> ohc.skills.TeamBlueprint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_skills_proto_init() }
func file_proto_skills_proto_init() {
	if File_proto_skills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_skills_proto_rawDesc), len(file_proto_skills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_skills_proto_goTypes,
		DependencyIndexes: file_proto_skills_proto_depIdxs,
		MessageInfos:      file_proto_skills_proto_msgTypes,
	}.Build()
	File_proto_skills_proto = out.File
	file_proto_skills_proto_goTypes = nil
	file_proto_skills_proto_depIdxs = nil
}
