load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync",
    srcs = ["sync_handler.go"],
    importpath = "onehumancorp/srcs/server/api/sync",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/orchestration:orchestration",
        "//srcs/server/repository:repository",
    ],
)

go_test(
    name = "sync_test",
    srcs = ["sync_handler_test.go"],
    embed = [":sync"],
    deps = [
        "//srcs/server/orchestration:orchestration",
        "//srcs/server/repository:repository",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
