exports_files(["Cargo.toml"])

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "chat",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/common:server_common",
        "@crates//:tokio",
        "@crates//:axum",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:uuid",
        "@crates//:chrono",
        "@crates//:futures-util",
        "@crates//:tokio-stream",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    compile_data = [
        "//src/server/migrations",
    ],
    rustc_env_files = [
        ":cargo_toml_env_vars",
    ],
    rustc_env = {
        "SQLX_OFFLINE": "true",
    }
)

rust_test(
    name = "chat_test",
    crate = ":chat",
    deps = [
        "@crates//:tokio-test",
    ],
    compile_data = [
        "//src/server/migrations",
    ],
    rustc_env_files = [
        ":cargo_toml_env_vars",
    ],
    rustc_env = {
        "SQLX_OFFLINE": "true",
    }
)

genrule(
    name = "cargo_toml_env_vars",
    outs = ["cargo_toml_env_vars.env"],
    cmd = "echo CARGO=cargo > $@",
)
