{{- if .Values.fluentBit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ohc.fullname" . }}-fluent-bit-config
  labels:
    {{- include "ohc.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     {{ .Values.fluentBit.logLevel }}
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Retry_Limit     False
{{- end }}
