{{- if and .Values.ohcCore.enabled .Values.ohcCore.vpa.enabled (not .Values.legacyAutoscaling) }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-ohc-core-vpa
  labels:
    app: {{ .Release.Name }}-ohc-core
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ .Release.Name }}-ohc-core
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: ohc-core
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: {{ .Values.ohcCore.resources.requests.cpu | quote }}
          memory: {{ .Values.ohcCore.resources.requests.memory | quote }}
        maxAllowed:
          cpu: {{ .Values.ohcCore.resources.limits.cpu | quote }}
          memory: {{ .Values.ohcCore.resources.limits.memory | quote }}
{{- end }}
