{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "ohc.fullname" . }}-resource-quota
  labels:
    {{- include "ohc.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requests.memory | quote }}
    requests.ephemeral-storage: {{ .Values.resourceQuota.requests.ephemeralStorage | quote }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limits.memory | quote }}
    limits.ephemeral-storage: {{ .Values.resourceQuota.limits.ephemeralStorage | quote }}
    pods: {{ .Values.resourceQuota.limits.pods | quote }}
    services: "50"
{{- end }}
