{{- range $name, $component := dict "backend" .Values.backend "core" .Values.ohcCore "chatwoot" .Values.chatwoot "powersync" .Values.powersync }}
{{- if and (or (not (hasKey $component "enabled")) $component.enabled) (and (hasKey $component "vpa") $component.vpa.enabled) }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "ohc.fullname" $ }}-{{ if eq $name "core" }}core{{ else }}{{ $name }}{{ end }}-vpa
  labels:
    {{- include "ohc.labels" $ | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ohc.fullname" $ }}-{{ if eq $name "core" }}core{{ else }}{{ $name }}{{ end }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ if eq $name "core" }}ohc-core{{ else }}{{ $name }}{{ end }}
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: {{ $component.resources.requests.cpu | quote }}
          memory: {{ $component.resources.requests.memory | quote }}
        maxAllowed:
          cpu: {{ $component.resources.limits.cpu | quote }}
          memory: {{ $component.resources.limits.memory | quote }}
{{- end }}
{{- end }}
