{{- if .Values.backend.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "ohc.fullname" . }}-backend-vpa
  labels:
    {{- include "ohc.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ohc.fullname" . }}-backend
  updatePolicy:
    updateMode: {{ if .Values.multiTenant.enabled }}"Initial"{{ else }}"Off"{{ end }}
  resourcePolicy:
    containerPolicies:
      - containerName: backend
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: {{ if .Values.multiTenant.enabled }}"500m"{{ else }}{{ .Values.backend.resources.requests.cpu | quote }}{{ end }}
          memory: {{ if .Values.multiTenant.enabled }}"1Gi"{{ else }}{{ .Values.backend.resources.requests.memory | quote }}{{ end }}
        maxAllowed:
          cpu: {{ if .Values.multiTenant.enabled }}"4000m"{{ else }}{{ .Values.backend.resources.limits.cpu | quote }}{{ end }}
          memory: {{ if .Values.multiTenant.enabled }}"8Gi"{{ else }}{{ .Values.backend.resources.limits.memory | quote }}{{ end }}
{{- end }}
---
{{- if .Values.ohcCore.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "ohc.fullname" . }}-core-vpa
  labels:
    {{- include "ohc.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ohc.fullname" . }}-core
  updatePolicy:
    updateMode: "Off"
{{- end }}
