load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "srcs",
    srcs = [
        "mod.rs",
        "service.rs",
        "test_inbox.rs"
    ],
    crate_root = "mod.rs",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:sqlx",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:uuid",
        "@crates//:chrono",
        "@crates//:tracing",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "test",
    crate = ":srcs",
    deps = [
        "@crates//:tokio",
    ],
)
