load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_api_inbox",
    srcs = [
        "handlers.rs",
        "lib.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/domain/inbox:server_domain_inbox",
        "@crates//:axum",
    ],
)
