// Proto types for the OHC agent service.
// Generated by Bazel rust_prost_library from //src/proto:agent_service_proto.
pub mod agent_service {
    #![allow(clippy::all)]
    pub use agent_service_proto::ohc::agent::service::*;
}
pub use agent_service::*;

pub mod interop {
    #![allow(clippy::all)]
    pub use interop_proto::ohc::interop::*;
}

pub mod hub {
    #![allow(clippy::all)]
    pub use hub_proto::ohc::orchestration::*;
}
