load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "events",
    srcs = ["service.go"],
    importpath = "github.com/onehumancorp/ohc/src/server/events",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto/events:events_go_proto",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@com_github_google_uuid//:uuid",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)

go_test(
    name = "events_test",
    srcs = ["service_test.go"],
    embed = [":events"],
    deps = [
        "//src/proto/events:events_go_proto",
        "@com_github_data_dog_go_sqlmock//:go-sqlmock",
        "@com_github_stretchr_testify//assert",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
