// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: srcs/proto/autodream.proto

package autodreampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutoDreamService_StoreFinding_FullMethodName   = "/ohc.autodream.AutoDreamService/StoreFinding"
	AutoDreamService_SearchFindings_FullMethodName = "/ohc.autodream.AutoDreamService/SearchFindings"
)

// AutoDreamServiceClient is the client API for AutoDreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoDreamServiceClient interface {
	StoreFinding(ctx context.Context, in *StoreFindingRequest, opts ...grpc.CallOption) (*StoreFindingResponse, error)
	SearchFindings(ctx context.Context, in *SearchFindingsRequest, opts ...grpc.CallOption) (*SearchFindingsResponse, error)
}

type autoDreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoDreamServiceClient(cc grpc.ClientConnInterface) AutoDreamServiceClient {
	return &autoDreamServiceClient{cc}
}

func (c *autoDreamServiceClient) StoreFinding(ctx context.Context, in *StoreFindingRequest, opts ...grpc.CallOption) (*StoreFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreFindingResponse)
	err := c.cc.Invoke(ctx, AutoDreamService_StoreFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoDreamServiceClient) SearchFindings(ctx context.Context, in *SearchFindingsRequest, opts ...grpc.CallOption) (*SearchFindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFindingsResponse)
	err := c.cc.Invoke(ctx, AutoDreamService_SearchFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoDreamServiceServer is the server API for AutoDreamService service.
// All implementations must embed UnimplementedAutoDreamServiceServer
// for forward compatibility.
type AutoDreamServiceServer interface {
	StoreFinding(context.Context, *StoreFindingRequest) (*StoreFindingResponse, error)
	SearchFindings(context.Context, *SearchFindingsRequest) (*SearchFindingsResponse, error)
	mustEmbedUnimplementedAutoDreamServiceServer()
}

// UnimplementedAutoDreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoDreamServiceServer struct{}

func (UnimplementedAutoDreamServiceServer) StoreFinding(context.Context, *StoreFindingRequest) (*StoreFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreFinding not implemented")
}
func (UnimplementedAutoDreamServiceServer) SearchFindings(context.Context, *SearchFindingsRequest) (*SearchFindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFindings not implemented")
}
func (UnimplementedAutoDreamServiceServer) mustEmbedUnimplementedAutoDreamServiceServer() {}
func (UnimplementedAutoDreamServiceServer) testEmbeddedByValue()                          {}

// UnsafeAutoDreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoDreamServiceServer will
// result in compilation errors.
type UnsafeAutoDreamServiceServer interface {
	mustEmbedUnimplementedAutoDreamServiceServer()
}

func RegisterAutoDreamServiceServer(s grpc.ServiceRegistrar, srv AutoDreamServiceServer) {
	// If the following call panics, it indicates UnimplementedAutoDreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutoDreamService_ServiceDesc, srv)
}

func _AutoDreamService_StoreFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoDreamServiceServer).StoreFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoDreamService_StoreFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoDreamServiceServer).StoreFinding(ctx, req.(*StoreFindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoDreamService_SearchFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoDreamServiceServer).SearchFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoDreamService_SearchFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoDreamServiceServer).SearchFindings(ctx, req.(*SearchFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutoDreamService_ServiceDesc is the grpc.ServiceDesc for AutoDreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoDreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ohc.autodream.AutoDreamService",
	HandlerType: (*AutoDreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreFinding",
			Handler:    _AutoDreamService_StoreFinding_Handler,
		},
		{
			MethodName: "SearchFindings",
			Handler:    _AutoDreamService_SearchFindings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srcs/proto/autodream.proto",
}
