// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: srcs/proto/autodream.proto

package autodreampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO8601 string for simplicity if timestamp.proto is missing
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_srcs_proto_autodream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_srcs_proto_autodream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_srcs_proto_autodream_proto_rawDescGZIP(), []int{0}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Finding) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Finding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type StoreFindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finding       *Finding               `protobuf:"bytes,1,opt,name=finding,proto3" json:"finding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFindingRequest) Reset() {
	*x = StoreFindingRequest{}
	mi := &file_srcs_proto_autodream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFindingRequest) ProtoMessage() {}

func (x *StoreFindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_srcs_proto_autodream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFindingRequest.ProtoReflect.Descriptor instead.
func (*StoreFindingRequest) Descriptor() ([]byte, []int) {
	return file_srcs_proto_autodream_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFindingRequest) GetFinding() *Finding {
	if x != nil {
		return x.Finding
	}
	return nil
}

type StoreFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFindingResponse) Reset() {
	*x = StoreFindingResponse{}
	mi := &file_srcs_proto_autodream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFindingResponse) ProtoMessage() {}

func (x *StoreFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_srcs_proto_autodream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFindingResponse.ProtoReflect.Descriptor instead.
func (*StoreFindingResponse) Descriptor() ([]byte, []int) {
	return file_srcs_proto_autodream_proto_rawDescGZIP(), []int{2}
}

func (x *StoreFindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchFindingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryEmbedding []float32              `protobuf:"fixed32,1,rep,packed,name=query_embedding,json=queryEmbedding,proto3" json:"query_embedding,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchFindingsRequest) Reset() {
	*x = SearchFindingsRequest{}
	mi := &file_srcs_proto_autodream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFindingsRequest) ProtoMessage() {}

func (x *SearchFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_srcs_proto_autodream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFindingsRequest.ProtoReflect.Descriptor instead.
func (*SearchFindingsRequest) Descriptor() ([]byte, []int) {
	return file_srcs_proto_autodream_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFindingsRequest) GetQueryEmbedding() []float32 {
	if x != nil {
		return x.QueryEmbedding
	}
	return nil
}

func (x *SearchFindingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFindingsResponse) Reset() {
	*x = SearchFindingsResponse{}
	mi := &file_srcs_proto_autodream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFindingsResponse) ProtoMessage() {}

func (x *SearchFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_srcs_proto_autodream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFindingsResponse.ProtoReflect.Descriptor instead.
func (*SearchFindingsResponse) Descriptor() ([]byte, []int) {
	return file_srcs_proto_autodream_proto_rawDescGZIP(), []int{4}
}

func (x *SearchFindingsResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

var File_srcs_proto_autodream_proto protoreflect.FileDescriptor

const file_srcs_proto_autodream_proto_rawDesc = "" +
	"\n" +
	"\x1asrcs/proto/autodream.proto\x12\rohc.autodream\"o\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\"G\n" +
	"\x13StoreFindingRequest\x120\n" +
	"\afinding\x18\x01 \x01(\v2\x16.ohc.autodream.FindingR\afinding\"0\n" +
	"\x14StoreFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x15SearchFindingsRequest\x12'\n" +
	"\x0fquery_embedding\x18\x01 \x03(\x02R\x0equeryEmbedding\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x16SearchFindingsResponse\x122\n" +
	"\bfindings\x18\x01 \x03(\v2\x16.ohc.autodream.FindingR\bfindings2\xca\x01\n" +
	"\x10AutoDreamService\x12W\n" +
	"\fStoreFinding\x12\".ohc.autodream.StoreFindingRequest\x1a#.ohc.autodream.StoreFindingResponse\x12]\n" +
	"\x0eSearchFindings\x12$.ohc.autodream.SearchFindingsRequest\x1a%.ohc.autodream.SearchFindingsResponseB?Z=github.com/onehumancorp/mono/srcs/proto/autodream;autodreampbb\x06proto3"

var (
	file_srcs_proto_autodream_proto_rawDescOnce sync.Once
	file_srcs_proto_autodream_proto_rawDescData []byte
)

func file_srcs_proto_autodream_proto_rawDescGZIP() []byte {
	file_srcs_proto_autodream_proto_rawDescOnce.Do(func() {
		file_srcs_proto_autodream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_srcs_proto_autodream_proto_rawDesc), len(file_srcs_proto_autodream_proto_rawDesc)))
	})
	return file_srcs_proto_autodream_proto_rawDescData
}

var file_srcs_proto_autodream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_srcs_proto_autodream_proto_goTypes = []any{
	(*Finding)(nil),                // 0: ohc.autodream.Finding
	(*StoreFindingRequest)(nil),    // 1: ohc.autodream.StoreFindingRequest
	(*StoreFindingResponse)(nil),   // 2: ohc.autodream.StoreFindingResponse
	(*SearchFindingsRequest)(nil),  // 3: ohc.autodream.SearchFindingsRequest
	(*SearchFindingsResponse)(nil), // 4: ohc.autodream.SearchFindingsResponse
}
var file_srcs_proto_autodream_proto_depIdxs = []int32{
	0, // 0: ohc.autodream.StoreFindingRequest.finding:type_name -> ohc.autodream.Finding
	0, // 1: ohc.autodream.SearchFindingsResponse.findings:type_name -> ohc.autodream.Finding
	1, // 2: ohc.autodream.AutoDreamService.StoreFinding:input_type -> ohc.autodream.StoreFindingRequest
	3, // 3: ohc.autodream.AutoDreamService.SearchFindings:input_type -> ohc.autodream.SearchFindingsRequest
	2, // 4: ohc.autodream.AutoDreamService.StoreFinding:output_type -> ohc.autodream.StoreFindingResponse
	4, // 5: ohc.autodream.AutoDreamService.SearchFindings:output_type -> ohc.autodream.SearchFindingsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_srcs_proto_autodream_proto_init() }
func file_srcs_proto_autodream_proto_init() {
	if File_srcs_proto_autodream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_srcs_proto_autodream_proto_rawDesc), len(file_srcs_proto_autodream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_srcs_proto_autodream_proto_goTypes,
		DependencyIndexes: file_srcs_proto_autodream_proto_depIdxs,
		MessageInfos:      file_srcs_proto_autodream_proto_msgTypes,
	}.Build()
	File_srcs_proto_autodream_proto = out.File
	file_srcs_proto_autodream_proto_goTypes = nil
	file_srcs_proto_autodream_proto_depIdxs = nil
}
