load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_domain_inbox",
    srcs = [
        "mod.rs",
        "models.rs",
        "tests.rs",
    ],
    crate_root = "mod.rs",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:serde",
        "@crates//:serde_json",
    ],
)

rust_test(
    name = "server_domain_inbox_test",
    crate = ":server_domain_inbox",
)
