load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repositories",
    srcs = ["tasks.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/db/repositories",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
        "//srcs/server/db/dbtest",
        "//srcs/server/db/models",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "repositories_test",
    srcs = ["tasks_test.go"],
    embed = [":repositories"],
    deps = [
        "//srcs/server/db",
        "//srcs/server/db/dbtest",
        "//srcs/server/db/models",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
