load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "billing_lib",
    srcs = ["main.go"],
    importpath = "github.com/onehumancorp/mono/apps/billing",
    visibility = ["//visibility:private"],
    deps = ["//services/billing"],
)

go_binary(
    name = "billing",
    embed = [":billing_lib"],
    visibility = ["//visibility:public"],
)
