load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "impl",
    srcs = [
        "file_read.go",
        "shell.go",
    ],
    importpath = "onehumancorp/srcs/backend/tools/impl",
    visibility = ["//visibility:public"],
)

go_test(
    name = "impl_test",
    srcs = [
        "file_read_test.go",
        "shell_test.go",
    ],
    embed = [":impl"],
)
