load("@rules_go//go:def.bzl", "go_test")

# Split integration tests into smaller targets for parallel execution and caching.

go_test(
    name = "ping_test",
    srcs = [
        "helpers_test.go",
        "ping_test.go",
    ],
    data = ["//src/server_old/agents/local"],
    tags = ["integration"],
    deps = [
        "//src/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)

go_test(
    name = "runtask_test",
    srcs = [
        "helpers_test.go",
        "runtask_test.go",
    ],
    data = ["//src/server_old/agents/local"],
    tags = ["integration"],
    deps = [
        "//src/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)

go_test(
    name = "subagent_test",
    srcs = [
        "helpers_test.go",
        "subagent_test.go",
    ],
    data = ["//src/server_old/agents/local"],
    tags = ["integration"],
    deps = [
        "//src/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
