load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "nats",
    srcs = ["nats.go"],
    importpath = "github.com/onehumancorp/mono/src/server/integrations/nats",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:hub_go_proto",
        "//src/server/integrations",
        "@org_golang_google_protobuf//proto:go_default_library",
    ],
)

go_test(
    name = "nats_test",
    srcs = ["nats_test.go"],
    embed = [":nats"],
    deps = [
        "//src/server/integrations",
    ],
)
