load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repository",
    srcs = ["task_repo.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/repository",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/auth",
        "//srcs/server/db",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "repository_test",
    srcs = ["task_repo_test.go"],
    embed = [":repository"],
    deps = [
        "//srcs/server/auth",
        "//srcs/server/db",
        "//srcs/server/telemetry",
        "@org_modernc_sqlite//:sqlite",
    ],
)
