load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repository",
    srcs = [
        "models.go",
        "task_repo.go",
    ],
    importpath = "github.com/onehumancorp/kairos/srcs/server/repository",
    visibility = ["//visibility:public"],
)

go_test(
    name = "repository_test",
    srcs = ["task_repo_test.go"],
    embed = [":repository"],
    deps = [
        "@com_github_mattn_go_sqlite3//:go_default_library",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
