load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loyalty",
    srcs = glob(["**/*.rs"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/domain",
        "@crates//:sqlx",
        "@crates//:uuid",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:chrono",
        "@crates//:axum",
        "@crates//:tokio",
    ],
)
