load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "loyalty",
    srcs = [
        "mod.rs",
        "service.rs",
    ],
    deps = [
        "//src/proto:loyalty",
        "@crates//:async-trait",
        "@crates//:chrono",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:tonic",
        "@crates//:tracing",
        "@crates//:uuid",
    ],
    visibility = ["//visibility:public"],
)
