load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sandbox",
    srcs = [
        "linux.go",
        "macos.go",
        "proxy.go",
        "sandbox.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/backend/sandbox",
    visibility = ["//visibility:public"],
)

go_test(
    name = "sandbox_test",
    srcs = ["sandbox_test.go"],
    embed = [":sandbox"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
