import { VerticalBox, LineEdit, ScrollView, HorizontalBox, Button } from "std-widgets.slint";

export component Tooltip inherits Rectangle {
    background: rgba(255, 255, 255, 0.2);
    border-radius: 8px;
    drop-shadow-blur: 20px;
    drop-shadow-color: rgba(0, 0, 0, 0.1);
    in property <string> text;

    Text {
        text: root.text;
        color: black;
        font-size: 14px;
        wrap: word-wrap;
    }
}
