load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "hub",
    srcs = [
        "rag_sync.go",
        "rag_sync_impl.go",
        "autodream_sync.go"
    ],
    importpath = "github.com/onehumancorp/mono/src/server/hub",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server_old/db",
	"//src/server_old/telemetry",
    ],
)

go_test(
    name = "hub_test",
    srcs = [
        "rag_sync_test.go",
        "autodream_sync_test.go"
    ],
    embed = [":hub"],
)
