load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tasks",
    srcs = [
        "queue.go",
        "router.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/api/tasks",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_prometheus_client_golang//prometheus",
    ],
)

go_test(
    name = "tasks_test",
    srcs = ["queue_test.go"],
    embed = [":tasks"],
)
