#!/bin/bash
# Script to rebuild and start Docker Compose services locally via Bazel.
# This script is called via "bazel run //:deploy_dev".

set -e

# --- Runfiles setup ---
# Copy-pasted from the Bazel Bash runfiles library v2.
# https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash
if [[ ! -d "${RUNFILES_DIR:-/dev/null}" && ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
  if [[ -f "$0.runfiles_manifest" ]]; then
    export RUNFILES_MANIFEST_FILE="$0.runfiles_manifest"
  elif [[ -f "$0.runfiles/MANIFEST" ]]; then
    export RUNFILES_MANIFEST_FILE="$0.runfiles/MANIFEST"
  elif [[ -f "$0.runfiles/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
    export RUNFILES_DIR="$0.runfiles"
  fi
fi
if [[ -f "${RUNFILES_DIR:-/dev/null}/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
  source "${RUNFILES_DIR}/bazel_tools/tools/bash/runfiles/runfiles.bash"
elif [[ -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
  source "$(grep -m1 "^bazel_tools/tools/bash/runfiles/runfiles.bash " \
            "$RUNFILES_MANIFEST_FILE" | cut -d ' ' -f 2-)"
else
  echo >&2 "ERROR: cannot find @bazel_tools//tools/bash/runfiles:runfiles.bash"
  ex""" + """it 1
fi
# --- end runfiles setup ---


# Support both "docker compose" and "docker-compose"
DOCKER_COMPOSE_CMD="docker compose"
if ! command -v docker &> /dev/null || ! docker compose version &> /dev/null; then
  if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
  else
    echo "Error: docker compose or docker-compose not found. Please install Docker Compose."
    exit 1
  fi
fi

# Determine the project root.
if [[ -n "$BUILD_WORKSPACE_DIRECTORY" ]]; then
  PROJECT_ROOT="$BUILD_WORKSPACE_DIRECTORY"
else
  PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

echo "--- Setting up Local Kubernetes Context ---"
if [[ -f "$PROJECT_ROOT/deploy/setup_k8s.sh" ]]; then
  bash "$PROJECT_ROOT/deploy/setup_k8s.sh" || true
else
  # Fallback for bazel runfiles
  SETUP_SCRIPT=$(find . -name setup_k8s.sh | head -n 1)
  if [[ -n "$SETUP_SCRIPT" ]]; then
    bash "$SETUP_SCRIPT" || true
  fi
fi

echo "--- Loading Bazel-built images ---"
# When running via "bazel run", bazel built tarballs are output to runfiles.
# To load them properly we invoke the executable generated by oci_load.
# We must find it in the runfiles.

load_image() {
  local IMAGE_NAME=$1
  if [[ -n "$RUNFILES_DIR" ]]; then
    # Find load script inside runfiles
    LOAD_SCRIPT=$(find "$RUNFILES_DIR" -name "${IMAGE_NAME}.sh" | head -n 1)
    if [[ -n "$LOAD_SCRIPT" ]]; then
      echo "Running $LOAD_SCRIPT"
      (
        export RUNFILES_DIR="${RUNFILES_DIR}"
        export RUNFILES_MANIFEST_FILE="${RUNFILES_MANIFEST_FILE:-}"
        "$LOAD_SCRIPT"
      )
    else
      echo "Error: ${IMAGE_NAME}.sh not found in runfiles."
      exit 1
    fi
  else
    # Try finding it relative to current path if not under bazel run
    LOAD_SCRIPT=$(find . -name "${IMAGE_NAME}.sh" | head -n 1)
    if [[ -n "$LOAD_SCRIPT" ]]; then
      echo "Running $LOAD_SCRIPT"
      bash "$LOAD_SCRIPT"
    else
      echo "Error: ${IMAGE_NAME}.sh not found. Run this via bazel run //:deploy_dev"
      exit 1
    fi
  fi
}

load_image "server_load"
load_image "mono_core_load"
load_image "agent_load"
load_image "default_agent_load"

cd "$PROJECT_ROOT"
echo "--- Starting services from $PROJECT_ROOT ---"
# Run docker-compose without --build because we just loaded the images.
$DOCKER_COMPOSE_CMD -f deploy/docker-compose.yml up "$@"
