services:
  ohc-core:
    pull_policy: never
    image: onehumancorp/mono-core:latest

  server:
    pull_policy: never
    image: onehumancorp/server:latest

  postgres:
    image: bitnami/postgresql:16
    pull_policy: missing
    command: ["postgres", "-c", "wal_level=logical"]

  valkey:
    image: valkey/valkey:8-alpine@sha256:94365b275456ae14621001c03556c732b1d93a0cdeacc317d1bdd52eba680885
    pull_policy: missing
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
