load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "authz",
    srcs = [
        "authorizer.go",
        "interceptor.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/harness/authz",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
    ],
)

go_test(
    name = "authz_test",
    srcs = [
        "authorizer_test.go",
        "interceptor_test.go",
    ],
    embed = [":authz"],
    deps = [
        "//srcs/server/db",
    ],
)
