load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rate_limiter",
    srcs = ["rate_limiter.go"],
    importpath = "onehumancorp/srcs/server/lib/integrations/rate_limiter",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_go_redis_redis_v8//:redis",
    ],
)

go_test(
    name = "rate_limiter_test",
    srcs = ["rate_limiter_test.go"],
    embed = [":rate_limiter"],
)
