#!/bin/bash
set -e
RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
BLUE="\033[38;5;39m"
CYAN="\033[38;5;87m"
GREEN="\033[38;5;120m"
PURPLE="\033[38;5;141m"
echo -e "${BOLD}${BLUE}======================================================${RESET}"
echo -e "${BOLD}${CYAN}          OHC: The Hybrid Agentic OS - Welcome        ${RESET}"
echo -e "${BOLD}${BLUE}======================================================${RESET}"
echo ""
echo -e "${DIM}Welcome to Day One at One Human Corp.${RESET}"
echo ""
echo -e "Please use the CLI options to set up your environment."
echo -e "If you are new, start with the ${PURPLE}Environment Wizard${RESET}."
echo -e "To provision a new agent, use the ${PURPLE}Agent Provisioning Wizard${RESET}."
echo ""
