load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_api",
    srcs = glob(
        ["**/*.rs"],
        exclude = ["**/*_test.rs"],
    ),
    crate_name = "server_api",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/domain:server_domain",
        "@crates//:sqlx",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "server_api_unit_test",
    srcs = glob(["**/*_test.rs"]),
    crate = ":server_api",
    deps = [
        "//src/server/domain:server_domain",
        "@crates//:sqlx",
        "@crates//:tokio",
    ],
)
