// In-App Help Center Implementation
pub struct HelpArticle {
    pub id: String,
    pub title: String,
    pub content: String,
    pub topic: String,
}
pub fn get_help_articles() -> Vec<HelpArticle> {
    vec![
        HelpArticle {
            id: "article_1".to_string(),
            title: "Help Article 1 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 1 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_2".to_string(),
            title: "Help Article 2 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 2 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_3".to_string(),
            title: "Help Article 3 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 3 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_4".to_string(),
            title: "Help Article 4 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 4 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_5".to_string(),
            title: "Help Article 5 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 5 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_6".to_string(),
            title: "Help Article 6 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 6 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_7".to_string(),
            title: "Help Article 7 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 7 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_8".to_string(),
            title: "Help Article 8 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 8 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_9".to_string(),
            title: "Help Article 9 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 9 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_10".to_string(),
            title: "Help Article 10 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 10 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_11".to_string(),
            title: "Help Article 11 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 11 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_12".to_string(),
            title: "Help Article 12 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 12 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_13".to_string(),
            title: "Help Article 13 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 13 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_14".to_string(),
            title: "Help Article 14 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 14 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_15".to_string(),
            title: "Help Article 15 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 15 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_16".to_string(),
            title: "Help Article 16 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 16 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_17".to_string(),
            title: "Help Article 17 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 17 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_18".to_string(),
            title: "Help Article 18 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 18 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_19".to_string(),
            title: "Help Article 19 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 19 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_20".to_string(),
            title: "Help Article 20 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 20 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_21".to_string(),
            title: "Help Article 21 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 21 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_22".to_string(),
            title: "Help Article 22 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 22 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_23".to_string(),
            title: "Help Article 23 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 23 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_24".to_string(),
            title: "Help Article 24 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 24 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_25".to_string(),
            title: "Help Article 25 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 25 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_26".to_string(),
            title: "Help Article 26 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 26 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_27".to_string(),
            title: "Help Article 27 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 27 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_28".to_string(),
            title: "Help Article 28 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 28 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_29".to_string(),
            title: "Help Article 29 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 29 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_30".to_string(),
            title: "Help Article 30 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 30 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_31".to_string(),
            title: "Help Article 31 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 31 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_32".to_string(),
            title: "Help Article 32 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 32 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_33".to_string(),
            title: "Help Article 33 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 33 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_34".to_string(),
            title: "Help Article 34 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 34 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_35".to_string(),
            title: "Help Article 35 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 35 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_36".to_string(),
            title: "Help Article 36 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 36 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_37".to_string(),
            title: "Help Article 37 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 37 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_38".to_string(),
            title: "Help Article 38 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 38 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_39".to_string(),
            title: "Help Article 39 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 39 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_40".to_string(),
            title: "Help Article 40 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 40 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_41".to_string(),
            title: "Help Article 41 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 41 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_42".to_string(),
            title: "Help Article 42 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 42 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_43".to_string(),
            title: "Help Article 43 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 43 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_44".to_string(),
            title: "Help Article 44 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 44 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_45".to_string(),
            title: "Help Article 45 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 45 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_46".to_string(),
            title: "Help Article 46 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 46 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_47".to_string(),
            title: "Help Article 47 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 47 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_48".to_string(),
            title: "Help Article 48 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 48 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_49".to_string(),
            title: "Help Article 49 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 49 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_50".to_string(),
            title: "Help Article 50 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 50 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_51".to_string(),
            title: "Help Article 51 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 51 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_52".to_string(),
            title: "Help Article 52 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 52 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_53".to_string(),
            title: "Help Article 53 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 53 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_54".to_string(),
            title: "Help Article 54 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 54 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_55".to_string(),
            title: "Help Article 55 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 55 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_56".to_string(),
            title: "Help Article 56 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 56 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_57".to_string(),
            title: "Help Article 57 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 57 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_58".to_string(),
            title: "Help Article 58 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 58 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_59".to_string(),
            title: "Help Article 59 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 59 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_60".to_string(),
            title: "Help Article 60 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 60 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_61".to_string(),
            title: "Help Article 61 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 61 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_62".to_string(),
            title: "Help Article 62 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 62 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_63".to_string(),
            title: "Help Article 63 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 63 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_64".to_string(),
            title: "Help Article 64 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 64 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_65".to_string(),
            title: "Help Article 65 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 65 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_66".to_string(),
            title: "Help Article 66 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 66 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_67".to_string(),
            title: "Help Article 67 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 67 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_68".to_string(),
            title: "Help Article 68 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 68 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_69".to_string(),
            title: "Help Article 69 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 69 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_70".to_string(),
            title: "Help Article 70 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 70 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_71".to_string(),
            title: "Help Article 71 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 71 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_72".to_string(),
            title: "Help Article 72 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 72 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_73".to_string(),
            title: "Help Article 73 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 73 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_74".to_string(),
            title: "Help Article 74 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 74 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_75".to_string(),
            title: "Help Article 75 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 75 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_76".to_string(),
            title: "Help Article 76 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 76 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_77".to_string(),
            title: "Help Article 77 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 77 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_78".to_string(),
            title: "Help Article 78 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 78 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_79".to_string(),
            title: "Help Article 79 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 79 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_80".to_string(),
            title: "Help Article 80 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 80 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_81".to_string(),
            title: "Help Article 81 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 81 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_82".to_string(),
            title: "Help Article 82 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 82 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_83".to_string(),
            title: "Help Article 83 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 83 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_84".to_string(),
            title: "Help Article 84 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 84 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_85".to_string(),
            title: "Help Article 85 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 85 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_86".to_string(),
            title: "Help Article 86 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 86 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_87".to_string(),
            title: "Help Article 87 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 87 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_88".to_string(),
            title: "Help Article 88 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 88 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_89".to_string(),
            title: "Help Article 89 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 89 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_90".to_string(),
            title: "Help Article 90 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 90 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_91".to_string(),
            title: "Help Article 91 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 91 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_92".to_string(),
            title: "Help Article 92 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 92 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_93".to_string(),
            title: "Help Article 93 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 93 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_94".to_string(),
            title: "Help Article 94 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 94 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_95".to_string(),
            title: "Help Article 95 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 95 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_96".to_string(),
            title: "Help Article 96 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 96 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_97".to_string(),
            title: "Help Article 97 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 97 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_98".to_string(),
            title: "Help Article 98 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 98 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_99".to_string(),
            title: "Help Article 99 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 99 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_100".to_string(),
            title: "Help Article 100 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 100 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_101".to_string(),
            title: "Help Article 101 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 101 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_102".to_string(),
            title: "Help Article 102 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 102 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_103".to_string(),
            title: "Help Article 103 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 103 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_104".to_string(),
            title: "Help Article 104 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 104 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_105".to_string(),
            title: "Help Article 105 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 105 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_106".to_string(),
            title: "Help Article 106 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 106 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_107".to_string(),
            title: "Help Article 107 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 107 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_108".to_string(),
            title: "Help Article 108 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 108 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_109".to_string(),
            title: "Help Article 109 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 109 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_110".to_string(),
            title: "Help Article 110 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 110 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_111".to_string(),
            title: "Help Article 111 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 111 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_112".to_string(),
            title: "Help Article 112 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 112 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_113".to_string(),
            title: "Help Article 113 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 113 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_114".to_string(),
            title: "Help Article 114 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 114 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_115".to_string(),
            title: "Help Article 115 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 115 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_116".to_string(),
            title: "Help Article 116 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 116 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_117".to_string(),
            title: "Help Article 117 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 117 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_118".to_string(),
            title: "Help Article 118 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 118 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_119".to_string(),
            title: "Help Article 119 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 119 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_120".to_string(),
            title: "Help Article 120 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 120 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_121".to_string(),
            title: "Help Article 121 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 121 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_122".to_string(),
            title: "Help Article 122 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 122 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_123".to_string(),
            title: "Help Article 123 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 123 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_124".to_string(),
            title: "Help Article 124 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 124 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_125".to_string(),
            title: "Help Article 125 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 125 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_126".to_string(),
            title: "Help Article 126 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 126 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_127".to_string(),
            title: "Help Article 127 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 127 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_128".to_string(),
            title: "Help Article 128 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 128 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_129".to_string(),
            title: "Help Article 129 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 129 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_130".to_string(),
            title: "Help Article 130 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 130 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_131".to_string(),
            title: "Help Article 131 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 131 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_132".to_string(),
            title: "Help Article 132 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 132 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_133".to_string(),
            title: "Help Article 133 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 133 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_134".to_string(),
            title: "Help Article 134 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 134 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_135".to_string(),
            title: "Help Article 135 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 135 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_136".to_string(),
            title: "Help Article 136 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 136 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_137".to_string(),
            title: "Help Article 137 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 137 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_138".to_string(),
            title: "Help Article 138 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 138 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_139".to_string(),
            title: "Help Article 139 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 139 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_140".to_string(),
            title: "Help Article 140 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 140 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_141".to_string(),
            title: "Help Article 141 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 141 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_142".to_string(),
            title: "Help Article 142 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 142 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_143".to_string(),
            title: "Help Article 143 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 143 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_144".to_string(),
            title: "Help Article 144 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 144 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_145".to_string(),
            title: "Help Article 145 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 145 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_146".to_string(),
            title: "Help Article 146 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 146 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_147".to_string(),
            title: "Help Article 147 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 147 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_148".to_string(),
            title: "Help Article 148 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 148 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_149".to_string(),
            title: "Help Article 149 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 149 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_150".to_string(),
            title: "Help Article 150 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 150 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_151".to_string(),
            title: "Help Article 151 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 151 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_152".to_string(),
            title: "Help Article 152 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 152 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_153".to_string(),
            title: "Help Article 153 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 153 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_154".to_string(),
            title: "Help Article 154 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 154 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_155".to_string(),
            title: "Help Article 155 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 155 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_156".to_string(),
            title: "Help Article 156 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 156 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_157".to_string(),
            title: "Help Article 157 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 157 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_158".to_string(),
            title: "Help Article 158 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 158 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_159".to_string(),
            title: "Help Article 159 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 159 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_160".to_string(),
            title: "Help Article 160 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 160 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_161".to_string(),
            title: "Help Article 161 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 161 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_162".to_string(),
            title: "Help Article 162 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 162 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_163".to_string(),
            title: "Help Article 163 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 163 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_164".to_string(),
            title: "Help Article 164 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 164 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_165".to_string(),
            title: "Help Article 165 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 165 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_166".to_string(),
            title: "Help Article 166 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 166 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_167".to_string(),
            title: "Help Article 167 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 167 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_168".to_string(),
            title: "Help Article 168 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 168 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_169".to_string(),
            title: "Help Article 169 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 169 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_170".to_string(),
            title: "Help Article 170 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 170 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_171".to_string(),
            title: "Help Article 171 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 171 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_172".to_string(),
            title: "Help Article 172 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 172 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_173".to_string(),
            title: "Help Article 173 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 173 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_174".to_string(),
            title: "Help Article 174 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 174 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_175".to_string(),
            title: "Help Article 175 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 175 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_176".to_string(),
            title: "Help Article 176 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 176 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_177".to_string(),
            title: "Help Article 177 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 177 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_178".to_string(),
            title: "Help Article 178 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 178 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_179".to_string(),
            title: "Help Article 179 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 179 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_180".to_string(),
            title: "Help Article 180 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 180 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_181".to_string(),
            title: "Help Article 181 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 181 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_182".to_string(),
            title: "Help Article 182 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 182 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_183".to_string(),
            title: "Help Article 183 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 183 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_184".to_string(),
            title: "Help Article 184 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 184 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_185".to_string(),
            title: "Help Article 185 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 185 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_186".to_string(),
            title: "Help Article 186 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 186 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_187".to_string(),
            title: "Help Article 187 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 187 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_188".to_string(),
            title: "Help Article 188 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 188 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_189".to_string(),
            title: "Help Article 189 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 189 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_190".to_string(),
            title: "Help Article 190 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 190 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_191".to_string(),
            title: "Help Article 191 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 191 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_192".to_string(),
            title: "Help Article 192 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 192 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_193".to_string(),
            title: "Help Article 193 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 193 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_194".to_string(),
            title: "Help Article 194 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 194 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_195".to_string(),
            title: "Help Article 195 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 195 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_196".to_string(),
            title: "Help Article 196 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 196 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_197".to_string(),
            title: "Help Article 197 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 197 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_198".to_string(),
            title: "Help Article 198 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 198 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_199".to_string(),
            title: "Help Article 199 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 199 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
        HelpArticle {
            id: "article_200".to_string(),
            title: "Help Article 200 - Getting Started".to_string(),
            content: "This is a plain language help article for business owners. It explains how to do step 200 without technical jargon. Very easy to understand.".to_string(),
            topic: "Getting Started".to_string(),
        },
    ]
}
