load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "statemachine",
    srcs = ["machine.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/statemachine",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
    ],
)

go_test(
    name = "statemachine_test",
    srcs = ["machine_test.go"],
    embed = [":statemachine"],
    deps = [
        "//srcs/server/db",
        "@org_modernc_sqlite//:sqlite",
    ],
)
