load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "wizard_lib",
    srcs = ["main.go"],
    importpath = "github.com/onehumancorp/mono/apps/wizard",
    visibility = ["//visibility:private"],
    deps = [
        "//services/wizard",
    ],
)

go_binary(
    name = "wizard",
    embed = [":wizard_lib"],
    visibility = ["//visibility:public"],
)
