load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repositories",
    srcs = [
        "mesh_repo.go",
        "tasks.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/db/repositories",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
        "//src/server/db/models",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "repositories_test",
    srcs = [
        "mesh_repo_test.go",
        "tasks_test.go",
    ],
    embed = [":repositories"],
    deps = [
        "//src/server/db",
        "//src/server/db/models",
        "@org_modernc_sqlite//:sqlite",
    ],
)
