load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "domain",
    srcs = ["tasks.go"],
    importpath = "onehumancorp/srcs/server/domain",
    visibility = ["//visibility:public"],
)

go_test(
    name = "domain_test",
    srcs = ["tasks_test.go"],
    embed = [":domain"],
)
