load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "integrations",
    srcs = [
        "catalog.go",
        "providers.go",
        "registry.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/integrations",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/integrations/litefs",
        "//srcs/server/integrations/powersync",
        "//srcs/proto:hub_go_proto",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "integrations_test",
    srcs = ["registry_test.go"],
    embed = [":integrations"],
)
