load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "memory",
    srcs = ["vector_repository.go"],
    importpath = "github.com/onehumancorp/mono/src/server/memory",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
    ],
)

go_test(
    name = "memory_test",
    srcs = ["vector_repository_test.go"],
    embed = [":memory"],
    tags = ["local"],
    deps = [
        "//src/server/db",
    ],
)
