load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_ohc",
    srcs = ["mod.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:agent_prost",
        "//src/proto:agent_service_prost",
        "//src/proto:agent_service_tonic",
        "//src/proto:app_prost",
        "//src/proto:app_tonic",
        "//src/proto:billing_prost",
        "//src/proto:billing_tonic",
        "//src/proto:common_prost",
        "//src/proto:docs_prost",
        "//src/proto:hub_prost",
        "//src/proto:interop_prost",
        "//src/proto:model_prost",
        "//src/proto:organization_prost",
        "//src/proto:finance_prost",
        "//src/proto:finance_tonic",
        "//src/proto:skills_prost",
    ],
)
