exports_files(["Cargo.toml"])

load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_ohc",
    srcs = ["mod.rs"],
    edition = "2024",
    rustc_flags = ["--cfg=ohc_bazel"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:agent_prost",
        "//src/proto:agent_service_tonic",
        "//src/proto:app_tonic",
        "//src/proto:inventory_tonic",
        "//src/proto:inbox_prost",
        "//src/proto:billing_tonic",
        "//src/proto:campaign_tonic",
        "//src/proto:collective_tonic",
        "//src/proto:common_prost",
        "//src/proto:hub_tonic",
        "//src/proto:interop_prost",
        "//src/proto:mcp_proxy_tonic",
        "//src/proto:organization_prost",
        "//src/proto:invoice_tonic",
        "@crates//:tonic",
    ],
)
