[package]
name = "server_ohc"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
sqlx = { version = "0.8", features = ["postgres", "chrono", "uuid", "macros"] }
axum = { version = "0.8.1", features = ["ws"] }
serde_json = { workspace = true }

[build-dependencies]
tonic-build = "0.12"

[lib]
name = "server_ohc"
path = "mod.rs"
