load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "orchestration",
    srcs = ["tasks_db.go", "sync_daemon.go", "sanitizer.go"],
    importpath = "onehumancorp/srcs/server/orchestration",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/telemetry",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "orchestration_test",
    srcs = ["tasks_db_test.go", "sync_daemon_test.go", "sanitizer_test.go"],
    embed = [":orchestration"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_mattn_go_sqlite3//:go_sqlite3",
        "@com_github_data_dog_go_sqlmock//:go-sqlmock",
    ],
)
