load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "chat",
    srcs = [
        "mem_store.go",
        "redis_stream_store.go",
        "slack_client.go",
        "types.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/integrations/chat",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_slack_go_slack//:slack",
    ],
)

go_test(
    name = "chat_test",
    srcs = ["chat_test.go"],
    deps = [":chat"],
)
