load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pricing",
    srcs = ["token_auditor.go"],
    importpath = "ohc/lib/pricing",
    visibility = ["//visibility:public"],
)

go_test(
    name = "pricing_test",
    srcs = ["token_auditor_test.go"],
    embed = [":pricing"],
)
