load("@rules_go//go:def.bzl", "go_library", "go_test")
go_library(
    name = "token_calculator",
    srcs = [
        "token_calculator/calculator.go",
    ],
    importpath = "ohc/lib/pricing/token_calculator",
    visibility = ["//visibility:public"],
)
go_test(
    name = "token_calculator_test",
    srcs = [
        "token_calculator/calculator_test.go",
    ],
    embed = [":token_calculator"],
)
