load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

write_file(
    name = "write_index",
    out = "index.js",
    content = ["require('@modelcontextprotocol/server-github/dist/index.js');"],
)

js_binary(
    name = "github",
    data = [
        "//:node_modules/@modelcontextprotocol/server-github",
        "//:node_modules/zod",
    ],
    entry_point = "index.js",
    visibility = ["//visibility:public"],
)
