load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync",
    srcs = ["escalator.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/services/sync",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/auth",
        "//srcs/server/telemetry",
        "//srcs/server/orchestration",
        "@io_opentelemetry_go_otel//:otel",
    ],
)

go_test(
    name = "sync_test",
    srcs = ["escalator_test.go"],
    embed = [":sync"],
    deps = [
        "//srcs/server/telemetry",
    ],
)
