// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent_service.proto

package agentservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RunTask_FullMethodName            = "/ohc.agent.service.AgentService/RunTask"
	AgentService_Ping_FullMethodName               = "/ohc.agent.service.AgentService/Ping"
	AgentService_DispatchToSubAgent_FullMethodName = "/ohc.agent.service.AgentService/DispatchToSubAgent"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is exposed by every agent process.
// The main Go server connects as a client; agents connect to sub-agent
// processes as clients as well.
type AgentServiceClient interface {
	// RunTask streams progress events back to the caller.
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunTaskEvent], error)
	// Ping is used for health-checking and service discovery.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// DispatchToSubAgent delegates work to a sub-agent and awaits its result.
	// When sub_agent_address is empty the agent runs the work in-process via
	// a goroutine and communicates with it over a channel.
	DispatchToSubAgent(ctx context.Context, in *SubAgentRequest, opts ...grpc.CallOption) (*SubAgentResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunTaskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_RunTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunTaskRequest, RunTaskEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RunTaskClient = grpc.ServerStreamingClient[RunTaskEvent]

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DispatchToSubAgent(ctx context.Context, in *SubAgentRequest, opts ...grpc.CallOption) (*SubAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_DispatchToSubAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is exposed by every agent process.
// The main Go server connects as a client; agents connect to sub-agent
// processes as clients as well.
type AgentServiceServer interface {
	// RunTask streams progress events back to the caller.
	RunTask(*RunTaskRequest, grpc.ServerStreamingServer[RunTaskEvent]) error
	// Ping is used for health-checking and service discovery.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// DispatchToSubAgent delegates work to a sub-agent and awaits its result.
	// When sub_agent_address is empty the agent runs the work in-process via
	// a goroutine and communicates with it over a channel.
	DispatchToSubAgent(context.Context, *SubAgentRequest) (*SubAgentResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RunTask(*RunTaskRequest, grpc.ServerStreamingServer[RunTaskEvent]) error {
	return status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) DispatchToSubAgent(context.Context, *SubAgentRequest) (*SubAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchToSubAgent not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RunTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).RunTask(m, &grpc.GenericServerStream[RunTaskRequest, RunTaskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RunTaskServer = grpc.ServerStreamingServer[RunTaskEvent]

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DispatchToSubAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DispatchToSubAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DispatchToSubAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DispatchToSubAgent(ctx, req.(*SubAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ohc.agent.service.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
		{
			MethodName: "DispatchToSubAgent",
			Handler:    _AgentService_DispatchToSubAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTask",
			Handler:       _AgentService_RunTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_service.proto",
}
