// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent_service.proto

package agentservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType classifies a RunTaskEvent.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// A partial text chunk from the assistant.
	EventType_TEXT_CHUNK EventType = 1
	// A tool has been invoked.
	EventType_TOOL_CALL EventType = 2
	// The agent has finished (final response in content).
	EventType_TASK_COMPLETE EventType = 3
	// A fatal error has occurred.
	EventType_TASK_ERROR EventType = 4
	// The agent accepted the task and initialized its runtime state.
	EventType_RUN_STARTED EventType = 5
	// A new ReAct iteration began.
	EventType_ITERATION_STARTED EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "TEXT_CHUNK",
		2: "TOOL_CALL",
		3: "TASK_COMPLETE",
		4: "TASK_ERROR",
		5: "RUN_STARTED",
		6: "ITERATION_STARTED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"TEXT_CHUNK":             1,
		"TOOL_CALL":              2,
		"TASK_COMPLETE":          3,
		"TASK_ERROR":             4,
		"RUN_STARTED":            5,
		"ITERATION_STARTED":      6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_service_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_agent_service_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

// AgentRuntimeConfig is the control surface for agent defaults and
// per-request execution settings.
type AgentRuntimeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LlmProvider        string                 `protobuf:"bytes,1,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	Model              string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	LlmEndpoint        string                 `protobuf:"bytes,3,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	SystemPrompt       string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens          int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature        float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxIterations      int32                  `protobuf:"varint,7,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	MaxContextMessages int32                  `protobuf:"varint,8,opt,name=max_context_messages,json=maxContextMessages,proto3" json:"max_context_messages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRuntimeConfig) Reset() {
	*x = AgentRuntimeConfig{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuntimeConfig) ProtoMessage() {}

func (x *AgentRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuntimeConfig.ProtoReflect.Descriptor instead.
func (*AgentRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRuntimeConfig) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *AgentRuntimeConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRuntimeConfig) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *AgentRuntimeConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentRuntimeConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentRuntimeConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AgentRuntimeConfig) GetMaxContextMessages() int32 {
	if x != nil {
		return x.MaxContextMessages
	}
	return 0
}

// RunTaskRequest is sent from the main server to the agent to start a task.
type RunTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task description / user prompt.
	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// LLM model name (e.g. "gpt-4o", "claude-3-5-sonnet", "llama3").
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// LLM provider: "openai" | "anthropic" | "ollama".
	LlmProvider string `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	// Optional endpoint override (primarily for Ollama).
	LlmEndpoint string `protobuf:"bytes,4,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	// System prompt override. Empty → use built-in default.
	SystemPrompt string `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Maximum tokens for a single LLM response.
	MaxTokens int32 `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// LLM temperature in [0, 2].
	Temperature float32 `protobuf:"fixed32,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Maximum number of messages retained in the context window before trimming.
	MaxContextMessages int32 `protobuf:"varint,8,opt,name=max_context_messages,json=maxContextMessages,proto3" json:"max_context_messages,omitempty"`
	// Preferred configuration surface; when populated these values override
	// the process defaults and supersede the legacy fields above.
	RuntimeConfig *AgentRuntimeConfig `protobuf:"bytes,9,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *RunTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *RunTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunTaskRequest) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *RunTaskRequest) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *RunTaskRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *RunTaskRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *RunTaskRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *RunTaskRequest) GetMaxContextMessages() int32 {
	if x != nil {
		return x.MaxContextMessages
	}
	return 0
}

func (x *RunTaskRequest) GetRuntimeConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

// RunTaskEvent is a single streamed event from the agent back to the server.
type RunTaskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=ohc.agent.service.EventType" json:"type,omitempty"`
	// Present for TEXT_CHUNK and TASK_COMPLETE.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Present for TOOL_CALL.
	ToolName     string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArgsJson string `protobuf:"bytes,4,opt,name=tool_args_json,json=toolArgsJson,proto3" json:"tool_args_json,omitempty"`
	ToolResult   string `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	// Present for TASK_ERROR.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Present for RUN_STARTED and ITERATION_STARTED.
	Iteration     int32 `protobuf:"varint,7,opt,name=iteration,proto3" json:"iteration,omitempty"`
	MessageCount  int32 `protobuf:"varint,8,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskEvent) Reset() {
	*x = RunTaskEvent{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskEvent) ProtoMessage() {}

func (x *RunTaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskEvent.ProtoReflect.Descriptor instead.
func (*RunTaskEvent) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *RunTaskEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RunTaskEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RunTaskEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RunTaskEvent) GetToolArgsJson() string {
	if x != nil {
		return x.ToolArgsJson
	}
	return ""
}

func (x *RunTaskEvent) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *RunTaskEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunTaskEvent) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *RunTaskEvent) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

// PingRequest / PingResponse for health-check.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// SubAgentRequest dispatches work to a sub-agent.
type SubAgentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Task         string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Model        string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	LlmProvider  string                 `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	LlmEndpoint  string                 `protobuf:"bytes,4,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	SystemPrompt string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens    int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature  float32                `protobuf:"fixed32,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Optional remote gRPC endpoint for the sub-agent (host:port).
	// When empty, the receiving agent executes the request in-process via goroutine.
	SubAgentAddress string `protobuf:"bytes,8,opt,name=sub_agent_address,json=subAgentAddress,proto3" json:"sub_agent_address,omitempty"`
	// Preferred configuration surface for sub-agent execution.
	RuntimeConfig *AgentRuntimeConfig `protobuf:"bytes,9,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAgentRequest) Reset() {
	*x = SubAgentRequest{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAgentRequest) ProtoMessage() {}

func (x *SubAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAgentRequest.ProtoReflect.Descriptor instead.
func (*SubAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubAgentRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *SubAgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SubAgentRequest) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *SubAgentRequest) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *SubAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *SubAgentRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SubAgentRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SubAgentRequest) GetSubAgentAddress() string {
	if x != nil {
		return x.SubAgentAddress
	}
	return ""
}

func (x *SubAgentRequest) GetRuntimeConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

// SubAgentResponse carries the sub-agent's final answer.
type SubAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAgentResponse) Reset() {
	*x = SubAgentResponse{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAgentResponse) ProtoMessage() {}

func (x *SubAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAgentResponse.ProtoReflect.Descriptor instead.
func (*SubAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubAgentResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SubAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\x11ohc.agent.service\"\xaf\x02\n" +
	"\x12AgentRuntimeConfig\x12!\n" +
	"\fllm_provider\x18\x01 \x01(\tR\vllmProvider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_endpoint\x18\x03 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12%\n" +
	"\x0emax_iterations\x18\a \x01(\x05R\rmaxIterations\x120\n" +
	"\x14max_context_messages\x18\b \x01(\x05R\x12maxContextMessages\"\xe6\x02\n" +
	"\x0eRunTaskRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12!\n" +
	"\fllm_endpoint\x18\x04 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x02R\vtemperature\x120\n" +
	"\x14max_context_messages\x18\b \x01(\x05R\x12maxContextMessages\x12L\n" +
	"\x0eruntime_config\x18\t \x01(\v2%.ohc.agent.service.AgentRuntimeConfigR\rruntimeConfig\"\x97\x02\n" +
	"\fRunTaskEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.ohc.agent.service.EventTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12$\n" +
	"\x0etool_args_json\x18\x04 \x01(\tR\ftoolArgsJson\x12\x1f\n" +
	"\vtool_result\x18\x05 \x01(\tR\n" +
	"toolResult\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1c\n" +
	"\titeration\x18\a \x01(\x05R\titeration\x12#\n" +
	"\rmessage_count\x18\b \x01(\x05R\fmessageCount\"\r\n" +
	"\vPingRequest\"C\n" +
	"\fPingResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xe1\x02\n" +
	"\x0fSubAgentRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12!\n" +
	"\fllm_endpoint\x18\x04 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x02R\vtemperature\x12*\n" +
	"\x11sub_agent_address\x18\b \x01(\tR\x0fsubAgentAddress\x12L\n" +
	"\x0eruntime_config\x18\t \x01(\v2%.ohc.agent.service.AgentRuntimeConfigR\rruntimeConfig\"@\n" +
	"\x10SubAgentResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x91\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_CHUNK\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\x11\n" +
	"\rTASK_COMPLETE\x10\x03\x12\x0e\n" +
	"\n" +
	"TASK_ERROR\x10\x04\x12\x0f\n" +
	"\vRUN_STARTED\x10\x05\x12\x15\n" +
	"\x11ITERATION_STARTED\x10\x062\x87\x02\n" +
	"\fAgentService\x12O\n" +
	"\aRunTask\x12!.ohc.agent.service.RunTaskRequest\x1a\x1f.ohc.agent.service.RunTaskEvent0\x01\x12G\n" +
	"\x04Ping\x12\x1e.ohc.agent.service.PingRequest\x1a\x1f.ohc.agent.service.PingResponse\x12]\n" +
	"\x12DispatchToSubAgent\x12\".ohc.agent.service.SubAgentRequest\x1a#.ohc.agent.service.SubAgentResponseBEZCgithub.com/onehumancorp/mono/srcs/proto/agentservice;agentservicepbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_service_proto_goTypes = []any{
	(EventType)(0),             // 0: ohc.agent.service.EventType
	(*AgentRuntimeConfig)(nil), // 1: ohc.agent.service.AgentRuntimeConfig
	(*RunTaskRequest)(nil),     // 2: ohc.agent.service.RunTaskRequest
	(*RunTaskEvent)(nil),       // 3: ohc.agent.service.RunTaskEvent
	(*PingRequest)(nil),        // 4: ohc.agent.service.PingRequest
	(*PingResponse)(nil),       // 5: ohc.agent.service.PingResponse
	(*SubAgentRequest)(nil),    // 6: ohc.agent.service.SubAgentRequest
	(*SubAgentResponse)(nil),   // 7: ohc.agent.service.SubAgentResponse
}
var file_agent_service_proto_depIdxs = []int32{
	1, // 0: ohc.agent.service.RunTaskRequest.runtime_config:type_name -> ohc.agent.service.AgentRuntimeConfig
	0, // 1: ohc.agent.service.RunTaskEvent.type:type_name -> ohc.agent.service.EventType
	1, // 2: ohc.agent.service.SubAgentRequest.runtime_config:type_name -> ohc.agent.service.AgentRuntimeConfig
	2, // 3: ohc.agent.service.AgentService.RunTask:input_type -> ohc.agent.service.RunTaskRequest
	4, // 4: ohc.agent.service.AgentService.Ping:input_type -> ohc.agent.service.PingRequest
	6, // 5: ohc.agent.service.AgentService.DispatchToSubAgent:input_type -> ohc.agent.service.SubAgentRequest
	3, // 6: ohc.agent.service.AgentService.RunTask:output_type -> ohc.agent.service.RunTaskEvent
	5, // 7: ohc.agent.service.AgentService.Ping:output_type -> ohc.agent.service.PingResponse
	7, // 8: ohc.agent.service.AgentService.DispatchToSubAgent:output_type -> ohc.agent.service.SubAgentResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		EnumInfos:         file_agent_service_proto_enumTypes,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
