import 'dart:io';

void main(List<String> args) {
  if (args.length < 2) {
    print('Usage: generate_domain_models.dart <input_pb_dart> <output_domain_dart>');
    exit(1);
  }

  final inputPath = args[0];
  final outputPath = args[1];

  final inputFile = File(inputPath);
  if (!inputFile.existsSync()) {
    print('Input file $inputPath not found');
    exit(1);
  }

  final content = inputFile.readAsStringSync();
  final classNameRegex = RegExp(r'class (\w+) extends \$pb\.GeneratedMessage');
  final matches = classNameRegex.allMatches(content);

  final outputBuffer = StringBuffer();
  final fileName = inputPath.split('/').last;
  final pbImport = fileName;

  outputBuffer.writeln("// Generated by generate_domain_models.dart. DO NOT EDIT.");
  outputBuffer.writeln("import 'dart:convert';");
  outputBuffer.writeln("import 'package:fixnum/fixnum.dart' as \$fixnum;");
  outputBuffer.writeln("import 'package:protobuf/protobuf.dart' as \$pb;");
  outputBuffer.writeln("import 'package:yaml/yaml.dart' as \$yaml;");
  outputBuffer.writeln("import '$pbImport' as pb;");
  outputBuffer.writeln("");

  for (final match in matches) {
    final className = match.group(1)!;
    if (className.startsWith('_')) continue;

    // Basic heuristic to find fields (this is limited but works for simple messages)
    // A better approach would use Protobuf descriptors, but this is faster for now.
    
    outputBuffer.writeln("/// Domain model wrapper for $className");
    outputBuffer.writeln("class $className {");
    outputBuffer.writeln("  final pb.$className _proto;");
    outputBuffer.writeln("");
    outputBuffer.writeln("  $className(this._proto);");
    outputBuffer.writeln("  $className.empty() : _proto = pb.$className();");
    outputBuffer.writeln("");
    outputBuffer.writeln("  factory $className.fromProto(pb.$className proto) => $className(proto);");
    outputBuffer.writeln("  pb.$className toProto() => _proto;");
    outputBuffer.writeln("");
    outputBuffer.writeln("  factory $className.fromJson(String json) => $className(pb.$className.fromJson(json));");
    outputBuffer.writeln("  String toJson() => _proto.writeToJson();");
    outputBuffer.writeln("");
    outputBuffer.writeln("  factory $className.fromMap(Map<String, dynamic> map) {");
    outputBuffer.writeln("    final p = pb.$className();");
    outputBuffer.writeln("    p.mergeFromProto3Json(map);");
    outputBuffer.writeln("    return $className(p);");
    outputBuffer.writeln("  }");
    outputBuffer.writeln("  Map<String, dynamic> toMap() => _proto.toProto3Json() as Map<String, dynamic>;");
    outputBuffer.writeln("");
    outputBuffer.writeln("  factory $className.fromYaml(String yaml) {");
    outputBuffer.writeln("    final map = \$yaml.loadYaml(yaml);");
    outputBuffer.writeln("    return $className.fromMap(Map<String, dynamic>.from(map));");
    outputBuffer.writeln("  }");
    outputBuffer.writeln("  String toYaml() => jsonEncode(toMap()); // Simple fallback, or use a proper YAML emitter");
    outputBuffer.writeln("");
    outputBuffer.writeln("  // Forwarding getters/setters and common methods");
    outputBuffer.writeln("  @override");
    outputBuffer.writeln("  bool operator ==(Object other) => other is $className && _proto == other._proto;");
    outputBuffer.writeln("  @override");
    outputBuffer.writeln("  int get hashCode => _proto.hashCode;");
    outputBuffer.writeln("  @override");
    outputBuffer.writeln("  String toString() => _proto.toString();");
    outputBuffer.writeln("");
    outputBuffer.writeln("  pb.$className get proto => _proto;");
    outputBuffer.writeln("}");
    outputBuffer.writeln("");
  }

  File(outputPath).writeAsStringSync(outputBuffer.toString());
}
