load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(
    [
        "mod.rs",
        "client.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_integrations_doordash",
    srcs = [
        "client.rs",
        "mod.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
    ],
)
