[package]
name = "app"
version = "0.4.32"
edition = "2024"

[lib]
path = "main.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
slint = { version = "1.8.0", default-features = false, features = ["backend-winit", "renderer-software", "compat-1-2"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
serde_yaml = { workspace = true }
futures = { workspace = true }
wasm-bindgen = "=0.2.105"
console_error_panic_hook = "0.1"
wasm-bindgen-futures = "=0.4.42"
tracing = "0.1.41"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
copypasta = "0.10.1"
tracing = "0.1.41"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", features = ["sync", "macros"] }
tonic = { version = "0.12", default-features = false, features = ["prost"] }
prost = "0.13"
reqwest = { version = "0.12", features = ["json"] }
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3.69", features = ["Window"] }

[build-dependencies]
slint-build = "1.8.0"
tonic-build = "0.12"

[dev-dependencies]
mockito = "1.4.0"
