import { HorizontalBox } from "std-widgets.slint";

export component CustomToggle inherits HorizontalBox {
    in property <bool> checked: false;
    callback toggled();

    spacing: 8px;
    alignment: end;

    TouchArea {
        width: 44px;
        height: 24px;
        clicked => { toggled(); }
        Rectangle {
            width: 100%;
            height: 100%;
            border-radius: 12px;
            background: root.checked ? #10b981 : rgba(255, 255, 255, 0.2);

            Rectangle {
                width: 20px;
                height: 20px;
                border-radius: 10px;
                background: white;
                x: root.checked ? parent.width - self.width - 2px : 2px;
                y: 2px;
                animate x { duration: 150ms; easing: ease-in-out; }
            }
        }
    }
}
