import { PasswordInput } from "password_input.slint";
import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component SecureAgentConfig inherits Window {
    min-width: 375px;
    preferred-width: 400px;
    height: 400px;
    title: "Secure Agent Config";
    out property <string> test_title: root.title;

    callback save_config(string);

    in-out property <string> token: "";
    in-out property <string> error_text: "";

    background: #f8fafc;

    VerticalBox {
        spacing: 20px;
        padding: 32px;
        alignment: center;

        Text { text: "Helper Configuration"; font-size: 24px; font-weight: 700; color: #1e293b; }
        
        Text {
            text: "Enter your secure SPIFFE Enrollment Token to authenticate the agent.";
            color: #64748b;
            wrap: word-wrap;
        }

        PasswordInput {
            placeholder-text: "spiffe://ohc.os/agent/1234";
            text <=> token;
        }
        
        if (error_text != "") : Text { text: error_text; color: #ef4444; }

        Button {
            text: "Save Configuration";
            enabled: token != "" && error_text == "";
            clicked => { save_config(token); }
        }
    }
}
