export global TooltipRegistry {
    pure callback request_tooltip_text(string) -> string;

    in-out property <length> active_x: 0;
    in-out property <length> active_y: 0;
    in-out property <bool> is_visible: false;
    in-out property <string> active_text: "";

    public function show_tooltip(id: string, x: length, y: length) {
        active_text = request_tooltip_text(id);
        if (active_text != "") {
            active_x = x;
            active_y = y;
            is_visible = true;
        }
    }

    public function hide_tooltip() {
        is_visible = false;
    }
}
