import { TooltipRegistry } from "tooltip_registry.slint";

export component TooltipElement inherits Rectangle {
    in property <string> tooltip_id;

    layout := VerticalLayout {
        @children
    }

    preferred-width: layout.preferred-width;
    preferred-height: layout.preferred-height;

    ta := TouchArea {
        width: 100%;
        height: 100%;
        pointer-event(event) => {
            return EventResult.reject;
        }
    }

    property <bool> is_hovered: ta.has-hover;
    changed is_hovered => {
        if (is_hovered) {
            TooltipRegistry.show_tooltip(tooltip_id, self.absolute-position.x, self.absolute-position.y + self.height);
        } else {
            TooltipRegistry.hide_tooltip();
        }
    }
}
