import { TooltipRegistry } from "tooltip_registry.slint";

export component TooltipElement inherits Rectangle {
    in property <string> tooltip_id;

    ta := TouchArea {
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                long-press-timer.running = true;
            } else if (event.button == PointerEventButton.left && event.kind == PointerEventKind.up) {
                long-press-timer.running = false;
            }
        }
    }

    @children

    long-press-timer := Timer {
        interval: 500ms;
        running: false;
        triggered => {
            TooltipRegistry.show_tooltip(tooltip_id, root.absolute-position.x, root.absolute-position.y + root.height);
            self.running = false;
        }
    }

    property <bool> is_hovered: ta.has-hover;
    changed is_hovered => {
        if (is_hovered) {
            TooltipRegistry.show_tooltip(tooltip_id, self.absolute-position.x, self.absolute-position.y + self.height);
        } else {
            TooltipRegistry.hide_tooltip();
            long-press-timer.running = false;
        }
    }
}
