load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "events_proto",
    srcs = ["events.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "events_go_proto",
    compilers = ["@rules_go//proto:go_grpc"],
    importpath = "github.com/onehumancorp/ohc/src/proto/events",
    proto = ":events_proto",
    visibility = ["//visibility:public"],
)
