load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "crypto",
    srcs = ["encryption.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/lib/crypto",
    visibility = ["//visibility:public"],
)

go_test(
    name = "crypto_test",
    srcs = ["encryption_test.go"],
    embed = [":crypto"],
)
