// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/organization.proto

package organizationpb

import (
	common "github.com/onehumancorp/mono/srcs/proto/ohc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          common.Role            `protobuf:"varint,1,opt,name=role,proto3,enum=ohc.common.Role" json:"role,omitempty"`
	BasePrompt    string                 `protobuf:"bytes,2,opt,name=base_prompt,json=basePrompt,proto3" json:"base_prompt,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ContextInputs []string               `protobuf:"bytes,4,rep,name=context_inputs,json=contextInputs,proto3" json:"context_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleProfile) Reset() {
	*x = RoleProfile{}
	mi := &file_proto_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleProfile) ProtoMessage() {}

func (x *RoleProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleProfile.ProtoReflect.Descriptor instead.
func (*RoleProfile) Descriptor() ([]byte, []int) {
	return file_proto_organization_proto_rawDescGZIP(), []int{0}
}

func (x *RoleProfile) GetRole() common.Role {
	if x != nil {
		return x.Role
	}
	return common.Role(0)
}

func (x *RoleProfile) GetBasePrompt() string {
	if x != nil {
		return x.BasePrompt
	}
	return ""
}

func (x *RoleProfile) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RoleProfile) GetContextInputs() []string {
	if x != nil {
		return x.ContextInputs
	}
	return nil
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	CeoId         string                 `protobuf:"bytes,4,opt,name=ceo_id,json=ceoId,proto3" json:"ceo_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Members       []*TeamMember          `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	RoleProfiles  []*RoleProfile         `protobuf:"bytes,7,rep,name=role_profiles,json=roleProfiles,proto3" json:"role_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_proto_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_proto_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Organization) GetCeoId() string {
	if x != nil {
		return x.CeoId
	}
	return ""
}

func (x *Organization) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Organization) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Organization) GetRoleProfiles() []*RoleProfile {
	if x != nil {
		return x.RoleProfiles
	}
	return nil
}

type TeamMember struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role           common.Role            `protobuf:"varint,4,opt,name=role,proto3,enum=ohc.common.Role" json:"role,omitempty"`
	ManagerId      string                 `protobuf:"bytes,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	IsHuman        bool                   `protobuf:"varint,6,opt,name=is_human,json=isHuman,proto3" json:"is_human,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_proto_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_proto_organization_proto_rawDescGZIP(), []int{2}
}

func (x *TeamMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamMember) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TeamMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamMember) GetRole() common.Role {
	if x != nil {
		return x.Role
	}
	return common.Role(0)
}

func (x *TeamMember) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *TeamMember) GetIsHuman() bool {
	if x != nil {
		return x.IsHuman
	}
	return false
}

type OrganizationChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Members       []*TeamMember          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationChart) Reset() {
	*x = OrganizationChart{}
	mi := &file_proto_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationChart) ProtoMessage() {}

func (x *OrganizationChart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationChart.ProtoReflect.Descriptor instead.
func (*OrganizationChart) Descriptor() ([]byte, []int) {
	return file_proto_organization_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationChart) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *OrganizationChart) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_proto_organization_proto protoreflect.FileDescriptor

const file_proto_organization_proto_rawDesc = "" +
	"\n" +
	"\x18proto/organization.proto\x12\x10ohc.organization\x1a\x12proto/common.proto\"\x9f\x01\n" +
	"\vRoleProfile\x12$\n" +
	"\x04role\x18\x01 \x01(\x0e2\x10.ohc.common.RoleR\x04role\x12\x1f\n" +
	"\vbase_prompt\x18\x02 \x01(\tR\n" +
	"basePrompt\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12%\n" +
	"\x0econtext_inputs\x18\x04 \x03(\tR\rcontextInputs\"\x85\x02\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x15\n" +
	"\x06ceo_id\x18\x04 \x01(\tR\x05ceoId\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x126\n" +
	"\amembers\x18\x06 \x03(\v2\x1c.ohc.organization.TeamMemberR\amembers\x12B\n" +
	"\rrole_profiles\x18\a \x03(\v2\x1d.ohc.organization.RoleProfileR\froleProfiles\"\xb9\x01\n" +
	"\n" +
	"TeamMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12$\n" +
	"\x04role\x18\x04 \x01(\x0e2\x10.ohc.common.RoleR\x04role\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\tR\tmanagerId\x12\x19\n" +
	"\bis_human\x18\x06 \x01(\bR\aisHuman\"\x8f\x01\n" +
	"\x11OrganizationChart\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.ohc.organization.OrganizationR\forganization\x126\n" +
	"\amembers\x18\x02 \x03(\v2\x1c.ohc.organization.TeamMemberR\amembers2\xc8\x01\n" +
	"\x13OrganizationService\x12T\n" +
	"\x12CreateOrganization\x12\x1e.ohc.organization.Organization\x1a\x1e.ohc.organization.Organization\x12[\n" +
	"\x14GetOrganizationChart\x12\x1e.ohc.organization.Organization\x1a#.ohc.organization.OrganizationChartBIZGgithub.com/onehumancorp/mono/srcs/proto/ohc/organization;organizationpbb\x06proto3"

var (
	file_proto_organization_proto_rawDescOnce sync.Once
	file_proto_organization_proto_rawDescData []byte
)

func file_proto_organization_proto_rawDescGZIP() []byte {
	file_proto_organization_proto_rawDescOnce.Do(func() {
		file_proto_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_organization_proto_rawDesc), len(file_proto_organization_proto_rawDesc)))
	})
	return file_proto_organization_proto_rawDescData
}

var file_proto_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_organization_proto_goTypes = []any{
	(*RoleProfile)(nil),       // 0: ohc.organization.RoleProfile
	(*Organization)(nil),      // 1: ohc.organization.Organization
	(*TeamMember)(nil),        // 2: ohc.organization.TeamMember
	(*OrganizationChart)(nil), // 3: ohc.organization.OrganizationChart
	(common.Role)(0),          // 4: ohc.common.Role
}
var file_proto_organization_proto_depIdxs = []int32{
	4, // 0: ohc.organization.RoleProfile.role:type_name -> ohc.common.Role
	2, // 1: ohc.organization.Organization.members:type_name -> ohc.organization.TeamMember
	0, // 2: ohc.organization.Organization.role_profiles:type_name -> ohc.organization.RoleProfile
	4, // 3: ohc.organization.TeamMember.role:type_name -> ohc.common.Role
	1, // 4: ohc.organization.OrganizationChart.organization:type_name -> ohc.organization.Organization
	2, // 5: ohc.organization.OrganizationChart.members:type_name -> ohc.organization.TeamMember
	1, // 6: ohc.organization.OrganizationService.CreateOrganization:input_type -> ohc.organization.Organization
	1, // 7: ohc.organization.OrganizationService.GetOrganizationChart:input_type -> ohc.organization.Organization
	1, // 8: ohc.organization.OrganizationService.CreateOrganization:output_type -> ohc.organization.Organization
	3, // 9: ohc.organization.OrganizationService.GetOrganizationChart:output_type -> ohc.organization.OrganizationChart
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_organization_proto_init() }
func file_proto_organization_proto_init() {
	if File_proto_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_organization_proto_rawDesc), len(file_proto_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_organization_proto_goTypes,
		DependencyIndexes: file_proto_organization_proto_depIdxs,
		MessageInfos:      file_proto_organization_proto_msgTypes,
	}.Build()
	File_proto_organization_proto = out.File
	file_proto_organization_proto_goTypes = nil
	file_proto_organization_proto_depIdxs = nil
}
