load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cleanup_lib",
    srcs = ["prune.go"],
    importpath = "github.com/onehumancorp/mono/scripts/cleanup",
    visibility = ["//visibility:public"],
    deps = [
        "@in_gopkg_yaml_v3//:yaml_v3",
        "//srcs/orchestration:orchestration",
    ],
)

go_test(
    name = "cleanup_test",
    srcs = ["prune_test.go"],
    embed = [":cleanup_lib"],
)
