load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "translation",
    srcs = ["translation_worker.go"],
    importpath = "github.com/onehumancorp/mono/src/server/workers/translation",
    visibility = ["//visibility:public"],
)

go_test(
    name = "translation_test",
    srcs = ["translation_worker_test.go"],
    embed = [":translation"],
)
