load("@next_npm//:defs.bzl", "npm_link_all_packages")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

npm_link_all_packages(name = "node_modules")

exports_files(glob([
    "package.json",
    "e2e/*.spec.ts",
    "src/e2e/**/*.spec.ts",
    "src/e2e/fixtures/*",
]))

filegroup(
    name = "next_e2e_specs",
    srcs = glob([
        "e2e/*.spec.ts",
        "src/e2e/**/*.spec.ts",
        "src/e2e/fixtures/*",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "next_app_e2e_data",
    srcs = glob(
        [
            "src/**",
            "public/**",


            "*.mjs",
            "*.mts",
            "*.json",
            "*.ts",
            "*.png",
        ],
        exclude = [
            "src/e2e/**",
            "src/**/*.test.ts",
            "src/**/*.test.tsx",
        ],
    ) + [
        ":node_modules",
    ],
    visibility = ["//visibility:public"],
)

sh_test(
    name = "next_vitest",
    size = "large",
    srcs = ["bazel_vitest_test.sh"],
    data = glob([
        "src/**/*.css",
        "src/**/*.ts",
        "src/**/*.tsx",
    ]) + [
        "next-env.d.ts",
        "package.json",
        "package-lock.json",
        "tsconfig.json",
        "vitest.config.ts",
        "vitest.setup.ts",
        ":node_modules",
        "//deploy:hybrid_telemetry_dashboard_mirrors",
        "//src/server/monitoring:dashboards",
        "@nodejs//:node",
    ],
)
