load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "next_vitest",
    size = "large",
    srcs = ["bazel_vitest_test.sh"],
    data = glob([
        "src/**/*.ts",
        "src/**/*.tsx",
    ]) + [
        "next-env.d.ts",
        "package.json",
        "package-lock.json",
        "tsconfig.json",
        "vitest.config.ts",
        "vitest.setup.ts",
    ],
    tags = ["no-sandbox"],
)
