exports_files(["Cargo.toml"])

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "omnichannel",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:async-trait",
        "@crates//:chrono",
        "@crates//:sea-orm",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "omnichannel_test",
    crate = ":omnichannel",
    deps = [
        "@crates//:tokio",
    ],
)
