exports_files(
    ["sql_middleware.rs"],
    visibility = ["//visibility:public"],
)

# Requested embedsrcs for Bazel integration
filegroup(
    name = "embedsrcs",
    srcs = [
        "//src/server/migrations:migrations",
        "//src/server/db/migrations:migrations",
    ],
    visibility = ["//visibility:public"],
)
