load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "models",
    srcs = [
        "mesh_models.go",
        "session.go",
        "shared_tasks_v4.go",
        "tasks.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/db/models",
    visibility = ["//visibility:public"],
)
