load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync_adapter",
    srcs = ["powersync.go"],
    importpath = "github.com/onehumancorp/mono/src/server/integrations/sync_adapter",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server_old/lib/sync",
    ],
)

go_test(
    name = "sync_adapter_test",
    srcs = ["powersync_test.go"],
    embed = [":sync_adapter"],
    deps = [
        "//src/server_old/lib/sync",
    ],
)