load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(
    [
        "mod.rs",

        "service.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_services_subscription",
    srcs = [
        "bazel_lib.rs",
        "mod.rs",

        "service.rs",
    ],
    crate_root = "bazel_lib.rs",
    edition = "2024",
    proc_macro_deps = [



        "@crates//:async-trait",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:serde",


        "//src/server:server_lib",
        "//src/server/domain:server_domain",
        "@crates//:uuid",
        "@crates//:chrono",
        "@crates//:serde_json",
        "@crates//:sqlx",
    ],
)

rust_test(
    name = "server_services_subscription_unit_test",
    size = "small",
    crate = ":server_services_subscription",
    edition = "2024",
    deps = [
        "@crates//:serde",


        "@crates//:tokio",
    ],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
