load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(
    [
        "mod.rs",
        "service.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_services_subscription",
    srcs = [
        "mod.rs",
        "service.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/server:server_lib",
        "//src/server/domain:server_domain",
        "@crates//:uuid",
        "@crates//:chrono",
        "@crates//:sqlx",
    ],
)
