load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = [
        "lock.go",
        "mesh.go",
    ],
    importpath = "github.com/onehumancorp/mono/api/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

go_test(
    name = "mesh_test",
    srcs = [
        "lock_test.go",
        "mesh_test.go",
    ],
    embed = [":mesh"],
    deps = [
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
