load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "memory",
    srcs = ["worker.go"],
    importpath = "github.com/onehumancorp/mono/src/server/workers/memory",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
        "//src/server/memory/autodream",
    ],
)

go_test(
    name = "memory_test",
    srcs = ["worker_test.go"],
    embed = [":memory"],
    deps = [
        "//src/server/db",
        "//src/server/memory",
        "//src/server/memory/autodream",
    ],
)
