pub struct ThemeConfig {
    pub id: &'static str,
    pub name: String,
    pub description: String,
    pub primary_color: &'static str,
    pub secondary_color: &'static str,
    pub background_color: &'static str,
    pub text_color: &'static str,
    pub font_family: &'static str,
    pub spacing_unit: i32,
    pub border_radius: &'static str,
    pub is_premium: bool,
}

pub fn get_available_themes() -> Vec<ThemeConfig> {
    vec![
        ThemeConfig {
            id: "theme_0",
            name: "Modern Store".to_string(),
            description: "A modern theme perfectly suited for any store.".to_string(),
            primary_color: "#112233",
            secondary_color: "#000000",
            background_color: "#3357FF",
            text_color: "#33A1FF",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 14,
            border_radius: "12px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_1",
            name: "Modern Boutique".to_string(),
            description: "A modern theme perfectly suited for any boutique.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#123456",
            background_color: "#FFFFFF",
            text_color: "#654321",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 9,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_2",
            name: "Modern Shop".to_string(),
            description: "A modern theme perfectly suited for any shop.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#3357FF",
            background_color: "#123456",
            text_color: "#A133FF",
            font_family: "'Inter', sans-serif",
            spacing_unit: 6,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_3",
            name: "Modern Market".to_string(),
            description: "A modern theme perfectly suited for any market.".to_string(),
            primary_color: "#112233",
            secondary_color: "#A133FF",
            background_color: "#A133FF",
            text_color: "#112233",
            font_family: "'Inter', sans-serif",
            spacing_unit: 7,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_4",
            name: "Modern Emporium".to_string(),
            description: "A modern theme perfectly suited for any emporium.".to_string(),
            primary_color: "#778899",
            secondary_color: "#FFA133",
            background_color: "#33FF57",
            text_color: "#123456",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 5,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_5",
            name: "Modern Bazaar".to_string(),
            description: "A modern theme perfectly suited for any bazaar.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#000000",
            background_color: "#A133FF",
            text_color: "#33FF57",
            font_family: "'Lato', sans-serif",
            spacing_unit: 16,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_6",
            name: "Modern Outlet".to_string(),
            description: "A modern theme perfectly suited for any outlet.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#33A1FF",
            background_color: "#CBA987",
            text_color: "#33A1FF",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 4,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_7",
            name: "Modern Studio".to_string(),
            description: "A modern theme perfectly suited for any studio.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#FFFFFF",
            background_color: "#F333FF",
            text_color: "#CBA987",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 15,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_8",
            name: "Modern Gallery".to_string(),
            description: "A modern theme perfectly suited for any gallery.".to_string(),
            primary_color: "#112233",
            secondary_color: "#654321",
            background_color: "#CBA987",
            text_color: "#778899",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 8,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_9",
            name: "Modern Atelier".to_string(),
            description: "A modern theme perfectly suited for any atelier.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#FF5733",
            background_color: "#FFFFFF",
            text_color: "#FFA133",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 9,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_10",
            name: "Modern Hub".to_string(),
            description: "A modern theme perfectly suited for any hub.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#654321",
            background_color: "#A133FF",
            text_color: "#A1FF33",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 7,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_11",
            name: "Modern Nexus".to_string(),
            description: "A modern theme perfectly suited for any nexus.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#FF5733",
            background_color: "#FFFFFF",
            text_color: "#33A1FF",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 11,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_12",
            name: "Modern Portal".to_string(),
            description: "A modern theme perfectly suited for any portal.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#AABBCC",
            background_color: "#FFA133",
            text_color: "#A133FF",
            font_family: "'Lato', sans-serif",
            spacing_unit: 13,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_13",
            name: "Modern Space".to_string(),
            description: "A modern theme perfectly suited for any space.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#FFA133",
            background_color: "#AABBCC",
            text_color: "#FF5733",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 9,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_14",
            name: "Modern Lab".to_string(),
            description: "A modern theme perfectly suited for any lab.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#F333FF",
            background_color: "#AABBCC",
            text_color: "#33A1FF",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 8,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_15",
            name: "Modern Forge".to_string(),
            description: "A modern theme perfectly suited for any forge.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#FF5733",
            background_color: "#33A1FF",
            text_color: "#AABBCC",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 16,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_16",
            name: "Modern Workshop".to_string(),
            description: "A modern theme perfectly suited for any workshop.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#123456",
            background_color: "#CBA987",
            text_color: "#33A1FF",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 10,
            border_radius: "4px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_17",
            name: "Modern Guild".to_string(),
            description: "A modern theme perfectly suited for any guild.".to_string(),
            primary_color: "#000000",
            secondary_color: "#33FF57",
            background_color: "#CBA987",
            text_color: "#CBA987",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 15,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_18",
            name: "Modern Collective".to_string(),
            description: "A modern theme perfectly suited for any collective.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#FFA133",
            background_color: "#FFA133",
            text_color: "#654321",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 15,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_19",
            name: "Modern Syndicate".to_string(),
            description: "A modern theme perfectly suited for any syndicate.".to_string(),
            primary_color: "#445566",
            secondary_color: "#FFA133",
            background_color: "#33A1FF",
            text_color: "#778899",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 11,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_20",
            name: "Modern Depot".to_string(),
            description: "A modern theme perfectly suited for any depot.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#FF5733",
            background_color: "#3357FF",
            text_color: "#AABBCC",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 10,
            border_radius: "16px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_21",
            name: "Modern Station".to_string(),
            description: "A modern theme perfectly suited for any station.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#FFFFFF",
            background_color: "#112233",
            text_color: "#F333FF",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 6,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_22",
            name: "Modern Post".to_string(),
            description: "A modern theme perfectly suited for any post.".to_string(),
            primary_color: "#123456",
            secondary_color: "#3357FF",
            background_color: "#654321",
            text_color: "#FF33A1",
            font_family: "'Lato', sans-serif",
            spacing_unit: 5,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_23",
            name: "Classic Store".to_string(),
            description: "A classic theme perfectly suited for any store.".to_string(),
            primary_color: "#33FF57",
            secondary_color: "#F333FF",
            background_color: "#112233",
            text_color: "#FFA133",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 11,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_24",
            name: "Classic Boutique".to_string(),
            description: "A classic theme perfectly suited for any boutique.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#33FF57",
            background_color: "#AABBCC",
            text_color: "#33A1FF",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 16,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_25",
            name: "Classic Shop".to_string(),
            description: "A classic theme perfectly suited for any shop.".to_string(),
            primary_color: "#F333FF",
            secondary_color: "#112233",
            background_color: "#33A1FF",
            text_color: "#AABBCC",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 16,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_26",
            name: "Classic Market".to_string(),
            description: "A classic theme perfectly suited for any market.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#654321",
            background_color: "#FF5733",
            text_color: "#AABBCC",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 11,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_27",
            name: "Classic Emporium".to_string(),
            description: "A classic theme perfectly suited for any emporium.".to_string(),
            primary_color: "#CBA987",
            secondary_color: "#000000",
            background_color: "#33FF57",
            text_color: "#FFFFFF",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 13,
            border_radius: "4px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_28",
            name: "Classic Bazaar".to_string(),
            description: "A classic theme perfectly suited for any bazaar.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#A1FF33",
            background_color: "#33A1FF",
            text_color: "#CBA987",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 9,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_29",
            name: "Classic Outlet".to_string(),
            description: "A classic theme perfectly suited for any outlet.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#778899",
            background_color: "#FF5733",
            text_color: "#654321",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 16,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_30",
            name: "Classic Studio".to_string(),
            description: "A classic theme perfectly suited for any studio.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#A1FF33",
            background_color: "#654321",
            text_color: "#123456",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 5,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_31",
            name: "Classic Gallery".to_string(),
            description: "A classic theme perfectly suited for any gallery.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#112233",
            background_color: "#000000",
            text_color: "#33FF57",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 16,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_32",
            name: "Classic Atelier".to_string(),
            description: "A classic theme perfectly suited for any atelier.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#A133FF",
            background_color: "#778899",
            text_color: "#FFA133",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 8,
            border_radius: "9999px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_33",
            name: "Classic Hub".to_string(),
            description: "A classic theme perfectly suited for any hub.".to_string(),
            primary_color: "#33A1FF",
            secondary_color: "#FF33A1",
            background_color: "#AABBCC",
            text_color: "#CBA987",
            font_family: "'Inter', sans-serif",
            spacing_unit: 9,
            border_radius: "12px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_34",
            name: "Classic Nexus".to_string(),
            description: "A classic theme perfectly suited for any nexus.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#FF33A1",
            background_color: "#CBA987",
            text_color: "#FFA133",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 8,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_35",
            name: "Classic Portal".to_string(),
            description: "A classic theme perfectly suited for any portal.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#3357FF",
            background_color: "#FFA133",
            text_color: "#33FF57",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 8,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_36",
            name: "Classic Space".to_string(),
            description: "A classic theme perfectly suited for any space.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#33FF57",
            background_color: "#F333FF",
            text_color: "#789ABC",
            font_family: "'Lato', sans-serif",
            spacing_unit: 12,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_37",
            name: "Classic Lab".to_string(),
            description: "A classic theme perfectly suited for any lab.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#FFFFFF",
            background_color: "#AABBCC",
            text_color: "#A1FF33",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 16,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_38",
            name: "Classic Forge".to_string(),
            description: "A classic theme perfectly suited for any forge.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#AABBCC",
            background_color: "#F333FF",
            text_color: "#112233",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 9,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_39",
            name: "Classic Workshop".to_string(),
            description: "A classic theme perfectly suited for any workshop.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#33FFF3",
            background_color: "#123456",
            text_color: "#112233",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 12,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_40",
            name: "Classic Guild".to_string(),
            description: "A classic theme perfectly suited for any guild.".to_string(),
            primary_color: "#445566",
            secondary_color: "#AABBCC",
            background_color: "#CBA987",
            text_color: "#789ABC",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 4,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_41",
            name: "Classic Collective".to_string(),
            description: "A classic theme perfectly suited for any collective.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#789ABC",
            background_color: "#AABBCC",
            text_color: "#789ABC",
            font_family: "'Inter', sans-serif",
            spacing_unit: 7,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_42",
            name: "Classic Syndicate".to_string(),
            description: "A classic theme perfectly suited for any syndicate.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#789ABC",
            background_color: "#654321",
            text_color: "#CBA987",
            font_family: "'Lato', sans-serif",
            spacing_unit: 9,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_43",
            name: "Classic Depot".to_string(),
            description: "A classic theme perfectly suited for any depot.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#778899",
            background_color: "#112233",
            text_color: "#33FF57",
            font_family: "'Inter', sans-serif",
            spacing_unit: 12,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_44",
            name: "Classic Station".to_string(),
            description: "A classic theme perfectly suited for any station.".to_string(),
            primary_color: "#33A1FF",
            secondary_color: "#AABBCC",
            background_color: "#112233",
            text_color: "#F333FF",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 12,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_45",
            name: "Classic Post".to_string(),
            description: "A classic theme perfectly suited for any post.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#789ABC",
            background_color: "#112233",
            text_color: "#A133FF",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 11,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_46",
            name: "Bold Store".to_string(),
            description: "A bold theme perfectly suited for any store.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#778899",
            background_color: "#445566",
            text_color: "#FF33A1",
            font_family: "'Lato', sans-serif",
            spacing_unit: 5,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_47",
            name: "Bold Boutique".to_string(),
            description: "A bold theme perfectly suited for any boutique.".to_string(),
            primary_color: "#112233",
            secondary_color: "#FFFFFF",
            background_color: "#33FFF3",
            text_color: "#CBA987",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 14,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_48",
            name: "Bold Shop".to_string(),
            description: "A bold theme perfectly suited for any shop.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#FF5733",
            background_color: "#FFA133",
            text_color: "#789ABC",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 9,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_49",
            name: "Bold Market".to_string(),
            description: "A bold theme perfectly suited for any market.".to_string(),
            primary_color: "#123456",
            secondary_color: "#FFA133",
            background_color: "#FF33A1",
            text_color: "#FFA133",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 15,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_50",
            name: "Bold Emporium".to_string(),
            description: "A bold theme perfectly suited for any emporium.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#654321",
            background_color: "#F333FF",
            text_color: "#FF5733",
            font_family: "'Inter', sans-serif",
            spacing_unit: 16,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_51",
            name: "Bold Bazaar".to_string(),
            description: "A bold theme perfectly suited for any bazaar.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#000000",
            background_color: "#778899",
            text_color: "#33FF57",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 14,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_52",
            name: "Bold Outlet".to_string(),
            description: "A bold theme perfectly suited for any outlet.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#654321",
            background_color: "#123456",
            text_color: "#33FFF3",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 6,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_53",
            name: "Bold Studio".to_string(),
            description: "A bold theme perfectly suited for any studio.".to_string(),
            primary_color: "#789ABC",
            secondary_color: "#A133FF",
            background_color: "#A133FF",
            text_color: "#FF33A1",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 10,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_54",
            name: "Bold Gallery".to_string(),
            description: "A bold theme perfectly suited for any gallery.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#FFA133",
            background_color: "#445566",
            text_color: "#FF5733",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 10,
            border_radius: "16px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_55",
            name: "Bold Atelier".to_string(),
            description: "A bold theme perfectly suited for any atelier.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#789ABC",
            background_color: "#FF33A1",
            text_color: "#FFA133",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 15,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_56",
            name: "Bold Hub".to_string(),
            description: "A bold theme perfectly suited for any hub.".to_string(),
            primary_color: "#F333FF",
            secondary_color: "#FFFFFF",
            background_color: "#33FF57",
            text_color: "#A133FF",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 6,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_57",
            name: "Bold Nexus".to_string(),
            description: "A bold theme perfectly suited for any nexus.".to_string(),
            primary_color: "#CBA987",
            secondary_color: "#000000",
            background_color: "#CBA987",
            text_color: "#33A1FF",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 14,
            border_radius: "9999px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_58",
            name: "Bold Portal".to_string(),
            description: "A bold theme perfectly suited for any portal.".to_string(),
            primary_color: "#33A1FF",
            secondary_color: "#33A1FF",
            background_color: "#3357FF",
            text_color: "#789ABC",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 4,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_59",
            name: "Bold Space".to_string(),
            description: "A bold theme perfectly suited for any space.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#000000",
            background_color: "#FF5733",
            text_color: "#FF5733",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 9,
            border_radius: "0px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_60",
            name: "Bold Lab".to_string(),
            description: "A bold theme perfectly suited for any lab.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#FFA133",
            background_color: "#CBA987",
            text_color: "#123456",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 6,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_61",
            name: "Bold Forge".to_string(),
            description: "A bold theme perfectly suited for any forge.".to_string(),
            primary_color: "#000000",
            secondary_color: "#778899",
            background_color: "#3357FF",
            text_color: "#123456",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 8,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_62",
            name: "Bold Workshop".to_string(),
            description: "A bold theme perfectly suited for any workshop.".to_string(),
            primary_color: "#123456",
            secondary_color: "#112233",
            background_color: "#AABBCC",
            text_color: "#000000",
            font_family: "'Lato', sans-serif",
            spacing_unit: 5,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_63",
            name: "Bold Guild".to_string(),
            description: "A bold theme perfectly suited for any guild.".to_string(),
            primary_color: "#654321",
            secondary_color: "#445566",
            background_color: "#000000",
            text_color: "#123456",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 10,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_64",
            name: "Bold Collective".to_string(),
            description: "A bold theme perfectly suited for any collective.".to_string(),
            primary_color: "#123456",
            secondary_color: "#FF33A1",
            background_color: "#789ABC",
            text_color: "#CBA987",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 12,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_65",
            name: "Bold Syndicate".to_string(),
            description: "A bold theme perfectly suited for any syndicate.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#33FF57",
            background_color: "#F333FF",
            text_color: "#FF33A1",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 8,
            border_radius: "12px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_66",
            name: "Bold Depot".to_string(),
            description: "A bold theme perfectly suited for any depot.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#112233",
            background_color: "#33FFF3",
            text_color: "#FFA133",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 10,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_67",
            name: "Bold Station".to_string(),
            description: "A bold theme perfectly suited for any station.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#112233",
            background_color: "#123456",
            text_color: "#000000",
            font_family: "'Lato', sans-serif",
            spacing_unit: 10,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_68",
            name: "Bold Post".to_string(),
            description: "A bold theme perfectly suited for any post.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#A1FF33",
            background_color: "#A133FF",
            text_color: "#A133FF",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 9,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_69",
            name: "Elegant Store".to_string(),
            description: "A elegant theme perfectly suited for any store.".to_string(),
            primary_color: "#445566",
            secondary_color: "#FF5733",
            background_color: "#AABBCC",
            text_color: "#789ABC",
            font_family: "'Raleway', sans-serif",
            spacing_unit: 14,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_70",
            name: "Elegant Boutique".to_string(),
            description: "A elegant theme perfectly suited for any boutique.".to_string(),
            primary_color: "#33FF57",
            secondary_color: "#778899",
            background_color: "#33A1FF",
            text_color: "#000000",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 5,
            border_radius: "0px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_71",
            name: "Elegant Shop".to_string(),
            description: "A elegant theme perfectly suited for any shop.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#CBA987",
            background_color: "#112233",
            text_color: "#778899",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 16,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_72",
            name: "Elegant Market".to_string(),
            description: "A elegant theme perfectly suited for any market.".to_string(),
            primary_color: "#445566",
            secondary_color: "#123456",
            background_color: "#445566",
            text_color: "#F333FF",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 5,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_73",
            name: "Elegant Emporium".to_string(),
            description: "A elegant theme perfectly suited for any emporium.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#AABBCC",
            background_color: "#F333FF",
            text_color: "#33FFF3",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 8,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_74",
            name: "Elegant Bazaar".to_string(),
            description: "A elegant theme perfectly suited for any bazaar.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#FF5733",
            background_color: "#FF33A1",
            text_color: "#FFFFFF",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 16,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_75",
            name: "Elegant Outlet".to_string(),
            description: "A elegant theme perfectly suited for any outlet.".to_string(),
            primary_color: "#FFA133",
            secondary_color: "#33FF57",
            background_color: "#FF33A1",
            text_color: "#000000",
            font_family: "'Open Sans', sans-serif",
            spacing_unit: 10,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_76",
            name: "Elegant Studio".to_string(),
            description: "A elegant theme perfectly suited for any studio.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#654321",
            background_color: "#FFFFFF",
            text_color: "#FFA133",
            font_family: "'Inter', sans-serif",
            spacing_unit: 9,
            border_radius: "16px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_77",
            name: "Elegant Gallery".to_string(),
            description: "A elegant theme perfectly suited for any gallery.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#FFFFFF",
            background_color: "#3357FF",
            text_color: "#FFA133",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 4,
            border_radius: "9999px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_78",
            name: "Elegant Atelier".to_string(),
            description: "A elegant theme perfectly suited for any atelier.".to_string(),
            primary_color: "#112233",
            secondary_color: "#FFA133",
            background_color: "#654321",
            text_color: "#FF5733",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 8,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_79",
            name: "Elegant Hub".to_string(),
            description: "A elegant theme perfectly suited for any hub.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#654321",
            background_color: "#A133FF",
            text_color: "#778899",
            font_family: "'Montserrat', sans-serif",
            spacing_unit: 15,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_80",
            name: "Elegant Nexus".to_string(),
            description: "A elegant theme perfectly suited for any nexus.".to_string(),
            primary_color: "#778899",
            secondary_color: "#445566",
            background_color: "#33FFF3",
            text_color: "#445566",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 13,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_81",
            name: "Elegant Portal".to_string(),
            description: "A elegant theme perfectly suited for any portal.".to_string(),
            primary_color: "#FF33A1",
            secondary_color: "#33FFF3",
            background_color: "#FF5733",
            text_color: "#A133FF",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 12,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_82",
            name: "Elegant Space".to_string(),
            description: "A elegant theme perfectly suited for any space.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#F333FF",
            background_color: "#123456",
            text_color: "#123456",
            font_family: "'Inter', sans-serif",
            spacing_unit: 6,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_83",
            name: "Elegant Lab".to_string(),
            description: "A elegant theme perfectly suited for any lab.".to_string(),
            primary_color: "#000000",
            secondary_color: "#CBA987",
            background_color: "#F333FF",
            text_color: "#654321",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 4,
            border_radius: "16px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_84",
            name: "Elegant Forge".to_string(),
            description: "A elegant theme perfectly suited for any forge.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#CBA987",
            background_color: "#654321",
            text_color: "#778899",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 4,
            border_radius: "12px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_85",
            name: "Elegant Workshop".to_string(),
            description: "A elegant theme perfectly suited for any workshop.".to_string(),
            primary_color: "#778899",
            secondary_color: "#112233",
            background_color: "#778899",
            text_color: "#33FF57",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 10,
            border_radius: "4px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_86",
            name: "Elegant Guild".to_string(),
            description: "A elegant theme perfectly suited for any guild.".to_string(),
            primary_color: "#123456",
            secondary_color: "#654321",
            background_color: "#33FFF3",
            text_color: "#FFA133",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 10,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_87",
            name: "Elegant Collective".to_string(),
            description: "A elegant theme perfectly suited for any collective.".to_string(),
            primary_color: "#33A1FF",
            secondary_color: "#CBA987",
            background_color: "#A133FF",
            text_color: "#33FFF3",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 16,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_88",
            name: "Elegant Syndicate".to_string(),
            description: "A elegant theme perfectly suited for any syndicate.".to_string(),
            primary_color: "#FF5733",
            secondary_color: "#789ABC",
            background_color: "#A1FF33",
            text_color: "#000000",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 4,
            border_radius: "16px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_89",
            name: "Elegant Depot".to_string(),
            description: "A elegant theme perfectly suited for any depot.".to_string(),
            primary_color: "#112233",
            secondary_color: "#FFFFFF",
            background_color: "#FF5733",
            text_color: "#33FFF3",
            font_family: "'Oswald', sans-serif",
            spacing_unit: 8,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_90",
            name: "Elegant Station".to_string(),
            description: "A elegant theme perfectly suited for any station.".to_string(),
            primary_color: "#F333FF",
            secondary_color: "#33FFF3",
            background_color: "#FF5733",
            text_color: "#445566",
            font_family: "'Inter', sans-serif",
            spacing_unit: 16,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_91",
            name: "Elegant Post".to_string(),
            description: "A elegant theme perfectly suited for any post.".to_string(),
            primary_color: "#A133FF",
            secondary_color: "#A133FF",
            background_color: "#3357FF",
            text_color: "#33FF57",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 16,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_92",
            name: "Minimal Store".to_string(),
            description: "A minimal theme perfectly suited for any store.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#445566",
            background_color: "#CBA987",
            text_color: "#33FF57",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 16,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_93",
            name: "Minimal Boutique".to_string(),
            description: "A minimal theme perfectly suited for any boutique.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#33FFF3",
            background_color: "#FF33A1",
            text_color: "#445566",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 15,
            border_radius: "12px",
            is_premium: true,
        },
        ThemeConfig {
            id: "theme_94",
            name: "Minimal Shop".to_string(),
            description: "A minimal theme perfectly suited for any shop.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#654321",
            background_color: "#778899",
            text_color: "#33A1FF",
            font_family: "'Inter', sans-serif",
            spacing_unit: 5,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_95",
            name: "Minimal Market".to_string(),
            description: "A minimal theme perfectly suited for any market.".to_string(),
            primary_color: "#AABBCC",
            secondary_color: "#FF33A1",
            background_color: "#123456",
            text_color: "#789ABC",
            font_family: "'Outfit', sans-serif",
            spacing_unit: 11,
            border_radius: "8px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_96",
            name: "Minimal Emporium".to_string(),
            description: "A minimal theme perfectly suited for any emporium.".to_string(),
            primary_color: "#33A1FF",
            secondary_color: "#AABBCC",
            background_color: "#33A1FF",
            text_color: "#A133FF",
            font_family: "'Lato', sans-serif",
            spacing_unit: 13,
            border_radius: "9999px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_97",
            name: "Minimal Bazaar".to_string(),
            description: "A minimal theme perfectly suited for any bazaar.".to_string(),
            primary_color: "#FFFFFF",
            secondary_color: "#33FF57",
            background_color: "#FF5733",
            text_color: "#33FF57",
            font_family: "'Nunito', sans-serif",
            spacing_unit: 14,
            border_radius: "12px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_98",
            name: "Minimal Outlet".to_string(),
            description: "A minimal theme perfectly suited for any outlet.".to_string(),
            primary_color: "#3357FF",
            secondary_color: "#123456",
            background_color: "#33A1FF",
            text_color: "#FFA133",
            font_family: "'Roboto', sans-serif",
            spacing_unit: 6,
            border_radius: "0px",
            is_premium: false,
        },
        ThemeConfig {
            id: "theme_99",
            name: "Minimal Studio".to_string(),
            description: "A minimal theme perfectly suited for any studio.".to_string(),
            primary_color: "#33FFF3",
            secondary_color: "#000000",
            background_color: "#F333FF",
            text_color: "#33FF57",
            font_family: "'Poppins', sans-serif",
            spacing_unit: 5,
            border_radius: "8px",
            is_premium: false,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_available_themes() {
        let themes = get_available_themes();
        assert!(!themes.is_empty());
        assert_eq!(themes.len(), 100);
    }

    #[test]
    fn test_theme_properties() {
        let themes = get_available_themes();
        let first = &themes[0];
        assert!(!first.name.is_empty());
        assert!(!first.description.is_empty());
        assert!(first.spacing_unit >= 4);
    }
}
