load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "api",
    srcs = ["growth.go"],
    importpath = "github.com/onehumancorp/mono/services/growth/api",
    visibility = ["//visibility:public"],
)

go_test(
    name = "api_test",
    srcs = ["growth_test.go"],
    embed = [":api"],
)
