load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "growth_legacy",
    srcs = [
        "ab.go",
        "quota_service.go",
        "referral.go",
        "referrals_repo.go",
        "team_service.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/services/growth_legacy",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/lib/analytics",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

go_test(
    name = "growth_legacy_test",
    srcs = [
        "ab_test_test.go",
        "quota_service_test.go",
        "referral_test.go",
        "referrals_repo_test.go",
        "team_service_test.go",
    ],
    embed = [":growth_legacy"],
    deps = [
        "//src/server/lib/analytics",
        "@com_github_alicebob_miniredis_v2//:miniredis",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)
