load("@aspect_rules_js//js:defs.bzl", "js_binary")

exports_files([
    "msvc_lib_ar_wrapper.sh",
    "protoc-gen-es.js",
    "ts_proto_wrapper.js",
])

toolchain_type(
    name = "gradle_toolchain_type",
    visibility = ["//visibility:public"],
)

# Hermetic ts-proto wrapper that correctly resolves dependencies in the sandbox
js_binary(
    name = "ts_proto_wrapper",
    data = ["//:node_modules/ts-proto"],
    entry_point = ":ts_proto_wrapper.js",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//visibility:public"],
)
