#!/usr/bin/env python3
# Copyright 2024 One Human Corp
# SPDX-License-Identifier: Apache-2.0
#
# Generates a .pbyaml.dart file with YAML extension methods for every top-level
# proto message found in the input .proto file.
#
# Usage: gen_dart_yaml.py <proto_file> <output_file>

import os
import re
import sys


_HEADER = """\
// GENERATED CODE – DO NOT MODIFY BY HAND
// Generated by gen_dart_yaml.py (proto_dart_library rule)
// ignore_for_file: annotate_overrides, camel_case_types
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unused_import, unused_shown_name

import 'dart:convert';

import 'package:yaml/yaml.dart';
"""

# Dart helper functions emitted once per generated file.
_HELPERS = r"""
// ── Internal helpers ──────────────────────────────────────────────────────────

/// Converts a Proto3 JSON value (as returned by [GeneratedMessage.toProto3Json])
/// to a YAML-formatted string.
String _protoToYaml(Object? value, [int depth = 0]) {
  if (value == null) return 'null\n';
  if (value is bool || value is num) return '$value\n';
  if (value is String) {
    if (value.isEmpty ||
        value.contains(':') ||
        value.contains('#') ||
        value.contains('\n') ||
        value.startsWith(' ') ||
        value.startsWith('-') ||
        value.startsWith("'")) {
      final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
      return '"$escaped"\n';
    }
    return '$value\n';
  }
  if (value is List) {
    if (value.isEmpty) return '[]\n';
    final indent = '  ' * depth;
    final buf = StringBuffer('\n');
    for (final item in value) {
      buf.write('$indent- ${_protoToYaml(item, depth + 1)}');
    }
    return buf.toString();
  }
  if (value is Map) {
    if (value.isEmpty) return '{}\n';
    final indent = '  ' * depth;
    final buf = StringBuffer('\n');
    for (final entry in (value as Map<String, dynamic>).entries) {
      buf.write('$indent${entry.key}: ${_protoToYaml(entry.value, depth + 1)}');
    }
    return buf.toString();
  }
  return '$value\n';
}
"""


def _message_extension(msg: str) -> str:
    """Return the Dart extension block for a single message class."""
    return f"""\
/// YAML helpers for [{msg}].
extension {msg}YamlExt on {msg} {{
  /// Serializes this message to a YAML string.
  String toYaml() => _protoToYaml(toProto3Json());

  /// Deserializes a YAML string into a [{msg}].
  static {msg} fromYaml(String yamlString) => {msg}()
      ..mergeFromProto3Json(
          jsonDecode(jsonEncode(loadYaml(yamlString))) as Map<String, dynamic>);
}}
"""


def generate(proto_path: str, output_path: str) -> None:
    with open(proto_path) as f:
        content = f.read()

    base = os.path.basename(proto_path).replace(".proto", "")

    # Extract top-level message names (handles proto2/3/editions syntax).
    messages = re.findall(r"^\s*message\s+(\w+)\s*\{", content, re.MULTILINE)
    # Deduplicate while preserving order.
    seen: set[str] = set()
    unique_messages = []
    for m in messages:
        if m not in seen:
            seen.add(m)
            unique_messages.append(m)

    parts = [
        _HEADER,
        f"import '{base}.pb.dart';\n",
        f"export '{base}.pb.dart';\n",
    ]

    for msg in unique_messages:
        parts.append("\n" + _message_extension(msg))

    parts.append(_HELPERS)

    with open(output_path, "w") as f:
        f.write("\n".join(parts))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <proto_file> <output_file>", file=sys.stderr)
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
