load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "interoppb",
    srcs = ["interop.pb.go"],
    importpath = "onehumancorp/srcs/server/pb/interoppb",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
