load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync",
    srcs = [
        "autodream_sync.go",
        "crdt.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/sync",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server_old/db",
        "//src/server_old/orchestration",
        "//src/server_old/telemetry",
    ],
)

go_test(
    name = "sync_test",
    srcs = [
        "autodream_sync_test.go",
        "crdt_e2e_test.go",
        "crdt_test.go",
    ],
    embed = [":sync"],
    deps = [
        "//src/server_old/db",
        "//src/server_old/telemetry",
    ],
)
