-- +goose Up
-- Add missing RLS policies to enforce tenant isolation

ALTER TABLE IF EXISTS affiliate_ledgers ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_affiliate_ledgers ON affiliate_ledgers USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS affiliate_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_affiliate_links ON affiliate_links USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS affiliate_payouts ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_affiliate_payouts ON affiliate_payouts USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS agent_actions ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_agent_actions ON agent_actions USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS agent_session_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_agent_session_data ON agent_session_data USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_appointments ON appointments USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS availability_blocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_availability_blocks ON availability_blocks USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS booking_resource_reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_booking_resource_reservations ON booking_resource_reservations USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS booking_resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_booking_resources ON booking_resources USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS crdt_deltas ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_crdt_deltas ON crdt_deltas USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS customer_loyalty_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_customer_loyalty_accounts ON customer_loyalty_accounts USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS deposit_requirements ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_deposit_requirements ON deposit_requirements USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS embedding_cache ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_embedding_cache ON embedding_cache USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS fulfillment_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_fulfillment_batches ON fulfillment_batches USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS invoice_communication_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_invoice_communication_events ON invoice_communication_events USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS job_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_job_templates ON job_templates USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS loyalty_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_loyalty_ledger ON loyalty_ledger USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS loyalty_programs ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_loyalty_programs ON loyalty_programs USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS loyalty_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_loyalty_rewards ON loyalty_rewards USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS loyalty_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_loyalty_transactions ON loyalty_transactions USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_collective ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_collective ON ohc_collective USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_collective_loyalty_balance ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_collective_loyalty_balance ON ohc_collective_loyalty_balance USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_collective_member ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_collective_member ON ohc_collective_member USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_fx_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_fx_rates ON ohc_fx_rates USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_i18n_strings ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_i18n_strings ON ohc_i18n_strings USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_multi_currency_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_multi_currency_ledger ON ohc_multi_currency_ledger USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_shared_offer ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_shared_offer ON ohc_shared_offer USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_staff_member ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_staff_member ON ohc_staff_member USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_timecard_event ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_timecard_event ON ohc_timecard_event USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS ohc_translation_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_ohc_translation_preferences ON ohc_translation_preferences USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS pre_order_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_pre_order_entries ON pre_order_entries USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS service_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_service_leads ON service_leads USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS service_resource_requirements ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_service_resource_requirements ON service_resource_requirements USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS services ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_services ON services USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS staff_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_staff_profiles ON staff_profiles USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS sub_agent_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_sub_agent_queue ON sub_agent_queue USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS subscribers ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_subscribers ON subscribers USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS subscription_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_subscription_plans ON subscription_plans USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_subscriptions ON subscriptions USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
ALTER TABLE IF EXISTS waitlist_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_waitlist_campaigns ON waitlist_campaigns USING (tenant_id::text = current_setting('app.current_tenant', true)) WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));
-- +goose Down
