-- Enable RLS for missing tables
ALTER TABLE IF EXISTS integration_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tool_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS fulfillment_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mcp_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bus_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bus_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bus_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS local_queue_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stress_workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sync_queue ENABLE ROW LEVEL SECURITY;
