load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_services_delivery",
    srcs = glob(["*.rs"]),
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:delivery_prost",
        "//src/proto:delivery_tonic",
        "@crates//:tonic",
        "@crates//:sqlx",
        "@crates//:uuid",
        "@crates//:tracing",
        "@crates//:chrono",
        "@crates//:serde",
        "@crates//:serde_json",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)

rust_test(
    name = "server_services_delivery_unit_test",
    crate = ":server_services_delivery",
    edition = "2024",
)
