load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "teams",
    srcs = [
        "mod.rs",
        "client.rs",
        "provider.rs",
    ],
    crate_root = "mod.rs",
    crate_name = "server_integrations_teams",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/integrations/core:server_integrations_core",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
        "@crates//:tracing",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)

rust_test(
    name = "server_integrations_teams_unit_test",
    crate = ":teams",
    edition = "2024",
)
exports_files(["Cargo.toml"], visibility = ["//visibility:public"])
