load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kairos",
    srcs = [
        "mesh.go",
        "metrics.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/kairos",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

go_test(
    name = "kairos_test",
    srcs = [
        "mesh_test.go",
        "metrics_test.go",
    ],
    embed = [":kairos"],
    deps = [
        "@com_github_alicebob_miniredis_v2//:miniredis",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_stretchr_testify//assert",
    ],
)
