// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mesh_event.proto

package kairos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeammateMeshEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	MsgId         string                 `protobuf:"bytes,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeammateMeshEvent) Reset() {
	*x = TeammateMeshEvent{}
	mi := &file_mesh_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeammateMeshEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeammateMeshEvent) ProtoMessage() {}

func (x *TeammateMeshEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeammateMeshEvent.ProtoReflect.Descriptor instead.
func (*TeammateMeshEvent) Descriptor() ([]byte, []int) {
	return file_mesh_event_proto_rawDescGZIP(), []int{0}
}

func (x *TeammateMeshEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TeammateMeshEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TeammateMeshEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TeammateMeshEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TeammateMeshEvent) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type SyncStateHandoff struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StateId         string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	SerializedState []byte                 `protobuf:"bytes,3,opt,name=serialized_state,json=serializedState,proto3" json:"serialized_state,omitempty"`
	ModeSource      string                 `protobuf:"bytes,4,opt,name=mode_source,json=modeSource,proto3" json:"mode_source,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EntityType      string                 `protobuf:"bytes,6,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncStateHandoff) Reset() {
	*x = SyncStateHandoff{}
	mi := &file_mesh_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateHandoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateHandoff) ProtoMessage() {}

func (x *SyncStateHandoff) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateHandoff.ProtoReflect.Descriptor instead.
func (*SyncStateHandoff) Descriptor() ([]byte, []int) {
	return file_mesh_event_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStateHandoff) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SyncStateHandoff) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *SyncStateHandoff) GetSerializedState() []byte {
	if x != nil {
		return x.SerializedState
	}
	return nil
}

func (x *SyncStateHandoff) GetModeSource() string {
	if x != nil {
		return x.ModeSource
	}
	return ""
}

func (x *SyncStateHandoff) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SyncStateHandoff) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

var File_mesh_event_proto protoreflect.FileDescriptor

const file_mesh_event_proto_rawDesc = "" +
	"\n" +
	"\x10mesh_event.proto\x12\x06kairos\"\x8f\x01\n" +
	"\x11TeammateMeshEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x15\n" +
	"\x06msg_id\x18\x05 \x01(\tR\x05msgId\"\xd5\x01\n" +
	"\x10SyncStateHandoff\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x12)\n" +
	"\x10serialized_state\x18\x03 \x01(\fR\x0fserializedState\x12\x1f\n" +
	"\vmode_source\x18\x04 \x01(\tR\n" +
	"modeSource\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\ventity_type\x18\x06 \x01(\tR\n" +
	"entityTypeB/Z-onehumancorp/srcs/server/orchestration/kairosb\x06proto3"

var (
	file_mesh_event_proto_rawDescOnce sync.Once
	file_mesh_event_proto_rawDescData []byte
)

func file_mesh_event_proto_rawDescGZIP() []byte {
	file_mesh_event_proto_rawDescOnce.Do(func() {
		file_mesh_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_event_proto_rawDesc), len(file_mesh_event_proto_rawDesc)))
	})
	return file_mesh_event_proto_rawDescData
}

var file_mesh_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mesh_event_proto_goTypes = []any{
	(*TeammateMeshEvent)(nil), // 0: kairos.TeammateMeshEvent
	(*SyncStateHandoff)(nil),  // 1: kairos.SyncStateHandoff
}
var file_mesh_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_event_proto_init() }
func file_mesh_event_proto_init() {
	if File_mesh_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_event_proto_rawDesc), len(file_mesh_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_event_proto_goTypes,
		DependencyIndexes: file_mesh_event_proto_depIdxs,
		MessageInfos:      file_mesh_event_proto_msgTypes,
	}.Build()
	File_mesh_event_proto = out.File
	file_mesh_event_proto_goTypes = nil
	file_mesh_event_proto_depIdxs = nil
}
