// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED     Role = 0
	Role_CEO                  Role = 1
	Role_PRODUCT_MANAGER      Role = 2
	Role_SOFTWARE_ENGINEER    Role = 3
	Role_ENGINEERING_DIRECTOR Role = 4
	Role_QA_TESTER            Role = 5
	Role_SECURITY_ENGINEER    Role = 6
	Role_DESIGNER             Role = 7
	Role_MARKETING_MANAGER    Role = 8
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "CEO",
		2: "PRODUCT_MANAGER",
		3: "SOFTWARE_ENGINEER",
		4: "ENGINEERING_DIRECTOR",
		5: "QA_TESTER",
		6: "SECURITY_ENGINEER",
		7: "DESIGNER",
		8: "MARKETING_MANAGER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":     0,
		"CEO":                  1,
		"PRODUCT_MANAGER":      2,
		"SOFTWARE_ENGINEER":    3,
		"ENGINEERING_DIRECTOR": 4,
		"QA_TESTER":            5,
		"SECURITY_ENGINEER":    6,
		"DESIGNER":             7,
		"MARKETING_MANAGER":    8,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

type AgentStatus int32

const (
	AgentStatus_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_IDLE               AgentStatus = 1
	AgentStatus_ACTIVE             AgentStatus = 2
	AgentStatus_IN_MEETING         AgentStatus = 3
	AgentStatus_BLOCKED            AgentStatus = 4
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "IDLE",
		2: "ACTIVE",
		3: "IN_MEETING",
		4: "BLOCKED",
	}
	AgentStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"IDLE":               1,
		"ACTIVE":             2,
		"IN_MEETING":         3,
		"BLOCKED":            4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\n" +
	"ohc.common*\xb6\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03CEO\x10\x01\x12\x13\n" +
	"\x0fPRODUCT_MANAGER\x10\x02\x12\x15\n" +
	"\x11SOFTWARE_ENGINEER\x10\x03\x12\x18\n" +
	"\x14ENGINEERING_DIRECTOR\x10\x04\x12\r\n" +
	"\tQA_TESTER\x10\x05\x12\x15\n" +
	"\x11SECURITY_ENGINEER\x10\x06\x12\f\n" +
	"\bDESIGNER\x10\a\x12\x15\n" +
	"\x11MARKETING_MANAGER\x10\b*X\n" +
	"\vAgentStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\x0e\n" +
	"\n" +
	"IN_MEETING\x10\x03\x12\v\n" +
	"\aBLOCKED\x10\x04B=Z;github.com/onehumancorp/mono/srcs/proto/ohc/common;commonpbb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_proto_goTypes = []any{
	(Role)(0),        // 0: ohc.common.Role
	(AgentStatus)(0), // 1: ohc.common.AgentStatus
}
var file_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
