load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "harness",
    srcs = ["harness.go"],
    importpath = "github.com/onehumancorp/mono/srcs/harness",
    visibility = ["//visibility:public"],
    deps = ["//srcs/harness/sandbox"],
)

go_test(
    name = "harness_test",
    srcs = ["harness_test.go"],
    embed = [":harness"],
    deps = ["@com_github_stretchr_testify//assert"],
)
