load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "harness",
    srcs = [
        "harness.go",
        "proxy.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/backend/harness",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "harness_test",
    srcs = ["harness_test.go"],
    embed = [":harness"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
    ],
)
