load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "departments",
    srcs = [
        "builtin.go",
        "department.go",
        "manager.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/departments",
    visibility = ["//visibility:public"],
)

go_test(
    name = "departments_test",
    srcs = [
        "department_e2e_test.go",
        "manager_test.go",
    ],
    embed = [":departments"],
    deps = [
        "//srcs/server/db",
    ],
)
