import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import FulfillmentHub from './page';
vi.mock('../../components/NetworkStatusIndicator',()=>({NetworkStatusIndicator:()=>null}));
vi.mock('../../lib/sync/MutationService',()=>({MutationService:{getInstance:()=>({executeMutation:vi.fn()})}}));
const queue={to_pack:[],awaiting_pickup:[{id:'order-a',delivery_task_id:'task-a',fulfillment_mode:'Shipping',status:'LABEL_CREATED',customer_name:null,items:[],organization_id:'tenant-a',binding_status:'bound'}]};
describe('FulfillmentHub evidence',()=>{
 beforeEach(()=>{global.fetch=vi.fn();});
 it('shows an unavailable queue instead of announcing all caught up',async()=>{vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({error:'Storage unavailable'}),{status:503}));render(<FulfillmentHub/>);expect(await screen.findByRole('alert')).toHaveTextContent('Storage unavailable');expect(screen.queryByText('All caught up!')).toBeNull();});
 it('shows actual label-created status without claiming pickup or delivery',async()=>{vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify(queue)));render(<FulfillmentHub/>);expect(await screen.findByText('Label created')).toBeVisible();expect(screen.getByRole('link',{name:'Manage shipping'})).toHaveAttribute('href','/orders/order-a');expect(screen.queryByText('Ready for Shipping')).toBeNull();expect(screen.queryByRole('button',{name:'Swipe to Hand Off'})).toBeNull();});
 it('keeps local readiness pending until a successful durable response',async()=>{let resolve:((value:Response)=>void)|undefined;vi.mocked(fetch).mockImplementation(async(_url,options)=>{if(options?.method==='POST')return new Promise<Response>(r=>{resolve=r;});return new Response(JSON.stringify({to_pack:[{...queue.awaiting_pickup[0],fulfillment_mode:'LocalDelivery',status:'PENDING'}],awaiting_pickup:[]}));});render(<FulfillmentHub/>);const button=await screen.findByRole('button',{name:/Mark ready/i});fireEvent.click(button);await waitFor(()=>expect(button).toBeDisabled());expect(screen.getByText('Pending')).toBeVisible();resolve?.(new Response(JSON.stringify({success:false,error:'Order changed; refresh'}),{status:409}));expect(await screen.findByRole('alert')).toHaveTextContent('Order changed; refresh');expect(screen.getByText('Pending')).toBeVisible();});
 it('shows unsupported dispatch without claiming a driver was requested',async()=>{vi.mocked(fetch).mockImplementation(async(_url,options)=>new Response(JSON.stringify(options?.method==='POST'?{success:false,error:'Driver dispatch is not connected; no driver was requested'}:{to_pack:[],awaiting_pickup:[{...queue.awaiting_pickup[0],fulfillment_mode:'LocalDelivery',status:'ReadyForPickup'}]}),{status:options?.method==='POST'?501:200}));render(<FulfillmentHub/>);fireEvent.click(await screen.findByRole('button',{name:/^Request driver/i}));expect(await screen.findByRole('alert')).toHaveTextContent('no driver was requested');expect(screen.queryByText('Driver requested')).toBeNull();});
});
