import {createOriginLockManager} from './test-support/origin-locks.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const paths=['src/ui/tauri/src/ui/setup.html',...['setup.html','ui/setup.html','api/ui/setup.html','api/v1/ui/setup.html'].map(p=>`src/ui/next/public/${p}`)];
const owner={userId:'user-1',tenantId:'org-1'};
const key='omnisolo_onboarding_owned_v1:'+encodeURIComponent(JSON.stringify([owner.userId,owner.tenantId]))+':legacy-draft';
const manual={work_context:'Agency',business_name:'Owner Studio',first_offer:'Owner Service',location:'Portland',target_audience:'Local founders',categories:'Design',template_selection:'Modern'};
const until=async condition=>{const end=Date.now()+1500;while(!condition()){if(Date.now()>end)throw Error('Expected actual setup condition did not occur');await new Promise(r=>setTimeout(r,5));}};
async function setup(path,options={}){
 const dom=new JSDOM(await readFile(new URL('../'+path,import.meta.url),'utf8'),{url:'https://workspace.example/setup.html',runScripts:'outside-only',pretendToBeVisual:true});const requests=[];let currentOwner=owner;
 Object.defineProperty(dom.window.navigator,'locks',{value:createOriginLockManager()});
 dom.window.fetch=async(url,init={})=>{requests.push({url,init});if(url.endsWith('/session-identity'))return Response.json({...currentOwner,expiresAt:Date.now()+60000});if(options.fetch)return options.fetch(url,init);return Response.json({});};
 dom.window.localStorage.setItem(key,options.raw||JSON.stringify({format:1,state:options.stored||{},revision:'owned-fixture',acknowledgedRevision:'owned-fixture'}));
 dom.window.HTMLElement.prototype.scrollTo=()=>{};dom.window.HTMLElement.prototype.scrollIntoView=()=>{};Object.defineProperty(dom.window.HTMLElement.prototype,'innerText',{get(){return this.textContent;},set(v){this.textContent=v;}});
 dom.window.eval([...dom.window.document.scripts].find(s=>s.textContent.includes('const container =')).textContent);
 await until(()=>(dom.window.document.getElementById('form-container')||dom.window.document.getElementById('setup-screen')).style.visibility!=='hidden');return{dom,d:dom.window.document,requests,setOwner:value=>{currentOwner=value;}};
}
const starts=f=>f.requests.filter(r=>/\/(start|launch)$/.test(r.url));
async function failChat(f){f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='My actual pottery studio idea';f.d.getElementById('chat-send-btn').click();await until(()=>!f.d.getElementById('chat-send-btn').disabled);}
const unconfigured=(url)=>Response.json(url.endsWith('/chat')||url.endsWith('/start_zero_click')?{error:'onboarding_ai_unconfigured',message:'AI-assisted setup is unavailable.'}:{},{status:url.endsWith('/chat')||url.endsWith('/start_zero_click')?503:200});
for(const path of paths){
 test(`${path}: exact unconfigured chat offers manual review without invented fields or preparation`,async()=>{const f=await setup(path,{fetch:unconfigured});try{await failChat(f);const button=f.d.getElementById('chat-manual-review');assert.ok(button);assert.equal(starts(f).length,0);button.click();assert.ok(f.d.getElementById('step-context').classList.contains('active'));assert.match(f.d.getElementById('manual-intake-context').textContent,/My actual pottery studio idea/);assert.equal(f.d.getElementById('business-name').value,'');assert.equal(f.d.getElementById('first-offer').value,'');assert.equal(f.d.getElementById('first-product-price').value,'');assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 test(`${path}: exact unconfigured instant intake retains the actual prompt for manual review`,async()=>{const f=await setup(path,{fetch:unconfigured});try{f.dom.window.goToStep('step-instant');const input=f.d.getElementById('instant-bio');input.value='Owner-entered bakery plan';input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));f.d.getElementById('generate-storefront-btn').click();await until(()=>f.d.getElementById('instant-manual-review'));assert.equal(starts(f).length,0);f.d.getElementById('instant-manual-review').click();assert.match(f.d.getElementById('manual-intake-context').textContent,/Owner-entered bakery plan/);assert.equal(input.value,'Owner-entered bakery plan');assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 test(`${path}: an unrelated503 does not authorize an unconfigured-provider continuation`,async()=>{const f=await setup(path,{fetch:url=>Response.json(url.endsWith('/chat')?{error:'database_unavailable'}:{},{status:url.endsWith('/chat')?503:200})});try{await failChat(f);assert.equal(f.d.getElementById('chat-manual-review'),null);assert.match(f.d.getElementById('chat-messages').textContent,/Failed to connect/);assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 test(`${path}: missing manual price cannot silently prepare a free product`,async()=>{const f=await setup(path,{stored:manual});try{f.d.getElementById('template-selection').value='Modern';f.d.getElementById('finish-btn').click();await new Promise(r=>setTimeout(r,20));assert.equal(starts(f).length,0);assert.ok(f.d.getElementById('step-offer').classList.contains('active'));assert.match(f.d.getElementById('first-product-price-error').textContent,/enter.*price/i);}finally{f.dom.window.close();}});
 for(const price of ['0','25.50'])test(`${path}: explicit owner price ${price} reaches preparation only after Finish`,async()=>{let payload;const f=await setup(path,{stored:manual,fetch:(url,init)=>{if(url.endsWith('/start')){payload=JSON.parse(init.body);return new Promise(()=>{});}return Response.json({});}});try{const input=f.d.getElementById('first-product-price');assert.ok(input);input.value=price;input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));f.d.getElementById('template-selection').value='Modern';assert.equal(starts(f).length,0);f.d.getElementById('finish-btn').click();await until(()=>payload);assert.equal(payload.first_product_price,price);assert.equal(payload.first_product_name,'Owner Service');assert.equal(payload.company_name,'Owner Studio');assert.equal(f.requests.some(r=>r.url.endsWith('/launch')),false);}finally{f.dom.window.close();}});
 test(`${path}: price survives the actual owned draft save and reload`,async()=>{let saved;const f=await setup(path,{stored:{...manual,firstProductPrice:'25.50'},fetch:(url,init)=>{if(url.endsWith('/draft')&&init.method==='POST')saved=JSON.parse(init.body);return Response.json({});}});let raw;try{const input=f.d.getElementById('first-product-price');assert.equal(input.value,'25.50');input.value='29.95';input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));f.d.querySelector('#step-offer .save-draft-btn').click();await until(()=>saved);assert.equal(saved.firstProductPrice,'29.95');raw=f.dom.window.localStorage.getItem(key);assert.equal(JSON.parse(raw).state.firstProductPrice,'29.95');}finally{f.dom.window.close();}const restored=await setup(path,{raw});try{assert.equal(restored.d.getElementById('first-product-price').value,'29.95');}finally{restored.dom.window.close();}});
 test(`${path}: retiring the owner clears manual context and review actions`,async()=>{const f=await setup(path,{fetch:unconfigured});try{await failChat(f);f.d.getElementById('chat-manual-review').click();assert.match(f.d.getElementById('manual-intake-context').textContent,/actual pottery/);f.dom.window.dispatchEvent(new f.dom.window.Event('pagehide'));assert.equal(f.d.getElementById('manual-intake-context')?.textContent||'','');assert.equal(f.d.getElementById('chat-manual-review'),null);assert.equal(f.d.getElementById('first-product-price').value,'');assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 for(const [status,data] of [[500,{error:'onboarding_ai_unconfigured'}],[503,{error:'onboarding_ai_unconfigured',success:true}]])test(`${path}: contradictory or wrong-status intake failure ${status} has no manual shortcut`,async()=>{const f=await setup(path,{fetch:url=>url.endsWith('/chat')?Response.json(data,{status}):Response.json({})});try{await failChat(f);assert.equal(f.d.getElementById('chat-manual-review'),null);assert.match(f.d.getElementById('chat-messages').textContent,/Failed to connect/);assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 test(`${path}: invalid prices hold preparation while keeping actual fields editable`,async()=>{const f=await setup(path,{stored:manual});try{const input=f.d.getElementById('first-product-price');for(const value of [' ','-1','NaN','1e3']){input.value=value;f.d.getElementById('finish-btn').click();await new Promise(r=>setTimeout(r,0));assert.equal(starts(f).length,0);assert.equal(input.disabled,false);assert.equal(input.value,value);assert.match(f.d.getElementById('first-product-price-error').textContent,/non-negative price/);}}finally{f.dom.window.close();}});
 test(`${path}: fallback keeps previously entered manual fields and price`,async()=>{const f=await setup(path,{stored:{...manual,tagline:'Owner-authored description',firstProductPrice:'12.75'},fetch:unconfigured});try{await failChat(f);f.d.getElementById('chat-manual-review').click();assert.equal(f.d.getElementById('business-name').value,'Owner Studio');assert.equal(f.d.getElementById('business-tagline').value,'Owner-authored description');assert.equal(f.d.getElementById('first-offer').value,'Owner Service');assert.equal(f.d.getElementById('first-product-price').value,'12.75');assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});
 test(`${path}: a late unconfigured response cannot reopen a retired owner's manual view`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{fetch:url=>url.endsWith('/chat')?pending:Response.json({})});try{f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='Private old owner prompt';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));f.dom.window.dispatchEvent(new f.dom.window.Event('pagehide'));resolve(Response.json({error:'onboarding_ai_unconfigured'},{status:503}));await new Promise(r=>setTimeout(r,10));assert.equal(f.d.getElementById('chat-manual-review'),null);assert.doesNotMatch(f.d.getElementById('chat-messages').textContent,/Private old owner prompt/);assert.equal(starts(f).length,0);}finally{f.dom.window.close();}});

 test(`${path}: chat history persists locally before an unresolved provider and reload after503`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{fetch:url=>url.endsWith('/chat')?pending:Response.json({})});let raw;try{f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='Preserved owner history';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));const entry=JSON.parse(f.dom.window.localStorage.getItem(key));assert.equal(entry.state.chat_history[0]?.content,'Preserved owner history');assert.notEqual(entry.revision,entry.acknowledgedRevision);resolve(Response.json({error:'onboarding_ai_unconfigured'},{status:503}));await until(()=>!f.d.getElementById('chat-send-btn').disabled);raw=f.dom.window.localStorage.getItem(key);assert.equal(f.requests.some(r=>r.url.endsWith('/draft')&&r.init.method==='POST'),false);}finally{f.dom.window.close();}const restored=await setup(path,{raw});try{assert.match(restored.d.getElementById('chat-messages').textContent,/Preserved owner history/);}finally{restored.dom.window.close();}});
 test(`${path}: chat history records the actual assistant reply as a pending local edit`,async()=>{const f=await setup(path,{fetch:url=>url.endsWith('/chat')?Response.json({reply:'Actual response asks for details',is_complete:false}):Response.json({})});try{await failChat(f);const entry=JSON.parse(f.dom.window.localStorage.getItem(key));assert.deepEqual(entry.state.chat_history.map(x=>[x.role,x.content]),[['user','My actual pottery studio idea'],['assistant','Actual response asks for details']]);assert.notEqual(entry.revision,entry.acknowledgedRevision);}finally{f.dom.window.close();}});
 test(`${path}: chat history storage failure remains visible and preserves the prior bytes`,async()=>{const f=await setup(path,{fetch:url=>url.endsWith('/chat')?new Promise(()=>{}):Response.json({})});try{f.dom.window.goToStep('step-chat');const prior=f.dom.window.localStorage.getItem(key);const original=f.dom.window.Storage.prototype.setItem;f.dom.window.Storage.prototype.setItem=function(k,v){if(k===key)throw new Error('storage unavailable');return original.call(this,k,v);};f.d.getElementById('chat-input').value='Not durably recorded';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));assert.match(f.d.getElementById('setup-session-status').textContent,/could not save/);assert.equal(f.dom.window.localStorage.getItem(key),prior);}finally{f.dom.window.close();}});
 test(`${path}: chat history rejects a late assistant after an owner switch`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{fetch:url=>url.endsWith('/chat')?pending:Response.json({})});try{f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='Owner A private history';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));f.setOwner({userId:'user-b',tenantId:'org-b'});f.dom.window.dispatchEvent(new f.dom.window.Event('omnisolo_auth_changed'));await until(()=>f.d.getElementById('chat-messages').textContent==='');resolve(Response.json({reply:'Late owner A reply',is_complete:false}));await new Promise(r=>setTimeout(r,10));assert.equal(f.d.getElementById('chat-messages').textContent,'');assert.match(f.dom.window.localStorage.getItem(key),/Owner A private history/);const other='omnisolo_onboarding_owned_v1:'+encodeURIComponent(JSON.stringify(['user-b','org-b']))+':legacy-draft';assert.doesNotMatch(f.dom.window.localStorage.getItem(other)||'',/Owner A|Late owner/);}finally{f.dom.window.close();}});

 test(`${path}: deferred assistant history cannot overwrite another view's newer local fields`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{stored:{...manual,firstProductPrice:'25.00'},fetch:url=>url.endsWith('/chat')?pending:Response.json({})});try{f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='User history before other view';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));const prior=JSON.parse(f.dom.window.localStorage.getItem(key));const updated={...prior,state:{...prior.state,business_name:'Newer second-view name',firstProductPrice:'39.95'},revision:'second-view-revision'};const bytes=JSON.stringify(updated);f.dom.window.localStorage.setItem(key,bytes);resolve(Response.json({reply:'Late assistant details',is_complete:false}));await until(()=>!f.d.getElementById('chat-send-btn').disabled);assert.equal(f.dom.window.localStorage.getItem(key),bytes);assert.match(f.d.getElementById('setup-session-status').textContent,/draft changed.*another view/i);}finally{f.dom.window.close();}});
 test(`${path}: metadata-only acknowledgement does not discard an unchanged draft's reply`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{fetch:url=>url.endsWith('/chat')?pending:Response.json({})});try{f.dom.window.goToStep('step-chat');f.d.getElementById('chat-input').value='User history with same fields';f.d.getElementById('chat-send-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/chat')));const entry=JSON.parse(f.dom.window.localStorage.getItem(key));f.dom.window.localStorage.setItem(key,JSON.stringify({...entry,acknowledgedRevision:entry.revision}));resolve(Response.json({reply:'Actual unchanged-draft reply',is_complete:false}));await until(()=>!f.d.getElementById('chat-send-btn').disabled);const saved=JSON.parse(f.dom.window.localStorage.getItem(key));assert.equal(saved.state.chat_history.at(-1).content,'Actual unchanged-draft reply');assert.notEqual(saved.revision,saved.acknowledgedRevision);}finally{f.dom.window.close();}});

 test(`${path}: deferred instant fallback cannot replace a newer local draft`,async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const f=await setup(path,{stored:manual,fetch:url=>url.endsWith('/start_zero_click')?pending:Response.json({})});try{f.dom.window.goToStep('step-instant');const input=f.d.getElementById('instant-bio');input.value='Actual initial instant prompt';input.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));f.d.getElementById('generate-storefront-btn').click();await until(()=>f.requests.some(r=>r.url.endsWith('/start_zero_click')));const entry=JSON.parse(f.dom.window.localStorage.getItem(key));const newer=JSON.stringify({...entry,state:{...entry.state,business_name:'Newer same-owner fields'},revision:'newer-instant-revision'});f.dom.window.localStorage.setItem(key,newer);resolve(Response.json({error:'onboarding_ai_unconfigured'},{status:503}));await until(()=>!f.d.getElementById('generate-storefront-btn').disabled);assert.equal(f.dom.window.localStorage.getItem(key),newer);assert.equal(f.d.getElementById('instant-manual-review'),null);assert.match(f.d.getElementById('setup-session-status').textContent,/draft changed.*another view/i);}finally{f.dom.window.close();}});

}
