load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "grpc",
    srcs = [
        "auth.go",
        "client.go",
        "doc.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server_old/agents/grpc",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//peer",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "grpc_test",
    srcs = ["auth_test.go"],
    deps = [
        ":grpc",
        "//src/proto/agentservice",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
    ],
)
