load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tokencalc",
    srcs = [
        "calculator.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/lib/pricing/tokencalc",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tokencalc_test",
    srcs = [
        "calculator_test.go",
    ],
    embed = [":tokencalc"],
)
