load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sync",
    srcs = [
        "repository.go",
        "sync_interfaces.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/sync",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
    ],
)

go_test(
    name = "sync_test",
    srcs = ["repository_test.go"],
    embed = [":sync"],
    deps = [
        "//srcs/server/db",
        "@org_modernc_sqlite//:sqlite",
    ],
)
