load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "departments",
    srcs = [
        "department.go",
        "implementations.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/domain/departments",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/orchestration",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
    ],
)

go_test(
    name = "departments_test",
    srcs = ["department_test.go"],
    embed = [":departments"],
    deps = [
        "//src/server/orchestration",
    ],
)
