[package]
name = "server_integrations_square"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
server_integrations_core = { path = "../core" }
uuid = { workspace = true, features = ["v4", "fast-rng", "macro-diagnostics"] }

[lints]
workspace = true
