apiVersion: v2
name: ohc
description: One Human Corp backend/frontend chart (includes Valkey and CloudNative-PG)
type: application
version: 0.4.42
appVersion: "0.4.42"
dependencies:
  - name: valkey
    version: "0.9.4"
    repository: "https://valkey-io.github.io/valkey-helm/"
    condition: valkey.enabled
  - name: kube-prometheus-stack
    version: "58.1.3"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
