load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "webhooks",
    srcs = ["receiver.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/services/webhooks",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/api/mesh",
        "//srcs/server/orchestration",
    ],
)

go_test(
    name = "webhooks_test",
    srcs = ["receiver_test.go"],
    embed = [":webhooks"],
    deps = [
        "//srcs/server/api/mesh",
        "//srcs/server/orchestration",
    ],
)
