filegroup(
    name = "srcs",
    srcs = [
        "b2b.rs",
        "blueprint.rs",
        "compute.rs",
        "federation.rs",
        "mod.rs",
        "model.rs",
        "organization.rs",
        "sre.rs",
        "unified_tenant_test.rs",
        "//src/server/domain/repository:srcs",
    ],
    visibility = ["//src/server:__pkg__"],
)
