load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

filegroup(
    name = "dashboards",
    srcs = glob(["dashboards/*.json"]),
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_monitoring",
    srcs = [
        "bazel_lib.rs",
    ],
    crate_root = "bazel_lib.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
)

rust_test(
    name = "server_monitoring_test",
    crate = ":server_monitoring",
)
