load("@rules_rust//rust:defs.bzl", "rust_test")
filegroup(
    name = "srcs",
    srcs = [


    ],
    visibility = ["//src/server:__pkg__"],
)

rust_test(
    name = "dummy_test",
    srcs = ["dummy.rs"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
