[package]
name = "server_common"
version = "0.1.0"
edition = "2024"

[dependencies]
server_config = { path = "../config" }
serde = { workspace = true }
sqlx = { version = "0.8", features = ["postgres", "sqlite", "runtime-tokio-rustls", "chrono", "uuid", "macros"] }

[lib]
path = "mod.rs"

[lints]
workspace = true
