load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_telemetry",
    srcs = [
        "mod.rs",
        "forecaster.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/config:server_config",
        "@crates//:chrono",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:tracing",
        "@crates//:opentelemetry",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "server_telemetry_unit_test",
    size = "small",
    crate = ":server_telemetry",
    edition = "2024",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
