load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "hub",
    srcs = ["autodream_sync.go"],
    importpath = "onehumancorp/srcs/server/hub",
    visibility = ["//visibility:public"],
)

go_test(
    name = "hub_test",
    srcs = ["autodream_sync_test.go"],
    embed = [":hub"],
)
