load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testutil",
    srcs = ["testutil.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/db/testutil",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
        "@org_modernc_sqlite//:sqlite",
    ],
)
