// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: src/proto/agent_service.proto

package agentservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// A partial text chunk from the assistant.
	EventType_TEXT_CHUNK EventType = 1
	// A tool has been invoked.
	EventType_TOOL_CALL EventType = 2
	// The agent has finished (final response in content).
	EventType_TASK_COMPLETE EventType = 3
	// A fatal error has occurred.
	EventType_TASK_ERROR EventType = 4
	// The agent accepted the task and initialized its runtime state.
	EventType_RUN_STARTED EventType = 5
	// A new ReAct iteration began.
	EventType_ITERATION_STARTED EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "TEXT_CHUNK",
		2: "TOOL_CALL",
		3: "TASK_COMPLETE",
		4: "TASK_ERROR",
		5: "RUN_STARTED",
		6: "ITERATION_STARTED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"TEXT_CHUNK":             1,
		"TOOL_CALL":              2,
		"TASK_COMPLETE":          3,
		"TASK_ERROR":             4,
		"RUN_STARTED":            5,
		"ITERATION_STARTED":      6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_agent_service_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_src_proto_agent_service_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

// MCPTransportType specifies the transport used to connect to an MCP server.
type MCPTransportType int32

const (
	MCPTransportType_MCP_TRANSPORT_UNSPECIFIED MCPTransportType = 0
	// Launch a subprocess and communicate over stdin/stdout (stdio transport).
	MCPTransportType_MCP_TRANSPORT_STDIO MCPTransportType = 1
	// Connect to a running HTTP server via Server-Sent Events.
	MCPTransportType_MCP_TRANSPORT_SSE MCPTransportType = 2
)

// Enum value maps for MCPTransportType.
var (
	MCPTransportType_name = map[int32]string{
		0: "MCP_TRANSPORT_UNSPECIFIED",
		1: "MCP_TRANSPORT_STDIO",
		2: "MCP_TRANSPORT_SSE",
	}
	MCPTransportType_value = map[string]int32{
		"MCP_TRANSPORT_UNSPECIFIED": 0,
		"MCP_TRANSPORT_STDIO":       1,
		"MCP_TRANSPORT_SSE":         2,
	}
)

func (x MCPTransportType) Enum() *MCPTransportType {
	p := new(MCPTransportType)
	*p = x
	return p
}

func (x MCPTransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPTransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_agent_service_proto_enumTypes[1].Descriptor()
}

func (MCPTransportType) Type() protoreflect.EnumType {
	return &file_src_proto_agent_service_proto_enumTypes[1]
}

func (x MCPTransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPTransportType.Descriptor instead.
func (MCPTransportType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

type SubagentLifecycleEvent_EventType int32

const (
	SubagentLifecycleEvent_EVENT_UNSPECIFIED SubagentLifecycleEvent_EventType = 0
	SubagentLifecycleEvent_SPAWNED           SubagentLifecycleEvent_EventType = 1
	SubagentLifecycleEvent_HEARTBEAT         SubagentLifecycleEvent_EventType = 2
	SubagentLifecycleEvent_COMPLETED         SubagentLifecycleEvent_EventType = 3
	SubagentLifecycleEvent_FAILED            SubagentLifecycleEvent_EventType = 4
	SubagentLifecycleEvent_KILLED            SubagentLifecycleEvent_EventType = 5
)

// Enum value maps for SubagentLifecycleEvent_EventType.
var (
	SubagentLifecycleEvent_EventType_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "SPAWNED",
		2: "HEARTBEAT",
		3: "COMPLETED",
		4: "FAILED",
		5: "KILLED",
	}
	SubagentLifecycleEvent_EventType_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"SPAWNED":           1,
		"HEARTBEAT":         2,
		"COMPLETED":         3,
		"FAILED":            4,
		"KILLED":            5,
	}
)

func (x SubagentLifecycleEvent_EventType) Enum() *SubagentLifecycleEvent_EventType {
	p := new(SubagentLifecycleEvent_EventType)
	*p = x
	return p
}

func (x SubagentLifecycleEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubagentLifecycleEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_agent_service_proto_enumTypes[2].Descriptor()
}

func (SubagentLifecycleEvent_EventType) Type() protoreflect.EnumType {
	return &file_src_proto_agent_service_proto_enumTypes[2]
}

func (x SubagentLifecycleEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubagentLifecycleEvent_EventType.Descriptor instead.
func (SubagentLifecycleEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{12, 0}
}

// AgentRuntimeConfig is the control surface for agent defaults and
// per-request execution settings.
type AgentRuntimeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LlmProvider        string                 `protobuf:"bytes,1,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	Model              string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	LlmEndpoint        string                 `protobuf:"bytes,3,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	SystemPrompt       string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens          int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature        float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxIterations      int32                  `protobuf:"varint,7,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	MaxContextMessages int32                  `protobuf:"varint,8,opt,name=max_context_messages,json=maxContextMessages,proto3" json:"max_context_messages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRuntimeConfig) Reset() {
	*x = AgentRuntimeConfig{}
	mi := &file_src_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuntimeConfig) ProtoMessage() {}

func (x *AgentRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuntimeConfig.ProtoReflect.Descriptor instead.
func (*AgentRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRuntimeConfig) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *AgentRuntimeConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRuntimeConfig) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *AgentRuntimeConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentRuntimeConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentRuntimeConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AgentRuntimeConfig) GetMaxContextMessages() int32 {
	if x != nil {
		return x.MaxContextMessages
	}
	return 0
}

// RunTaskRequest is sent from the main server to the agent to start a task.
type RunTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task identifier for tracing and output file naming.
	TaskId string `protobuf:"bytes,11,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The task description / user prompt.
	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// LLM model name (e.g. "gpt-4o", "claude-3-5-sonnet", "llama3").
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// LLM provider: "openai" | "anthropic" | "ollama".
	LlmProvider string `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	// Optional endpoint override (primarily for Ollama).
	LlmEndpoint string `protobuf:"bytes,4,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	// System prompt override. Empty → use built-in default.
	SystemPrompt string `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Maximum tokens for a single LLM response.
	MaxTokens int32 `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// LLM temperature in [0, 2].
	Temperature float32 `protobuf:"fixed32,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Maximum number of messages retained in the context window before trimming.
	MaxContextMessages int32 `protobuf:"varint,8,opt,name=max_context_messages,json=maxContextMessages,proto3" json:"max_context_messages,omitempty"`
	// Preferred configuration surface; when populated these values override
	// the process defaults and supersede the legacy fields above.
	RuntimeConfig *AgentRuntimeConfig `protobuf:"bytes,9,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	// Toolset configuration: which built-in tools, MCP servers, and skills to
	// make available for this specific run.  When absent the agent uses its
	// process-level defaults.
	ToolsetConfig *ToolsetConfig `protobuf:"bytes,10,opt,name=toolset_config,json=toolsetConfig,proto3" json:"toolset_config,omitempty"`
	// The OHC department handling the task.
	Department    string `protobuf:"bytes,12,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_src_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *RunTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *RunTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunTaskRequest) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *RunTaskRequest) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *RunTaskRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *RunTaskRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *RunTaskRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *RunTaskRequest) GetMaxContextMessages() int32 {
	if x != nil {
		return x.MaxContextMessages
	}
	return 0
}

func (x *RunTaskRequest) GetRuntimeConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

func (x *RunTaskRequest) GetToolsetConfig() *ToolsetConfig {
	if x != nil {
		return x.ToolsetConfig
	}
	return nil
}

func (x *RunTaskRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

// RunTaskEvent is a single streamed event from the agent back to the server.
type RunTaskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=ohc.agent.service.EventType" json:"type,omitempty"`
	// Present for TEXT_CHUNK and TASK_COMPLETE.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Present for TOOL_CALL.
	ToolName     string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArgsJson string `protobuf:"bytes,4,opt,name=tool_args_json,json=toolArgsJson,proto3" json:"tool_args_json,omitempty"`
	ToolResult   string `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	// Present for TASK_ERROR.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Present for RUN_STARTED and ITERATION_STARTED.
	Iteration     int32 `protobuf:"varint,7,opt,name=iteration,proto3" json:"iteration,omitempty"`
	MessageCount  int32 `protobuf:"varint,8,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskEvent) Reset() {
	*x = RunTaskEvent{}
	mi := &file_src_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskEvent) ProtoMessage() {}

func (x *RunTaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskEvent.ProtoReflect.Descriptor instead.
func (*RunTaskEvent) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *RunTaskEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RunTaskEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RunTaskEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RunTaskEvent) GetToolArgsJson() string {
	if x != nil {
		return x.ToolArgsJson
	}
	return ""
}

func (x *RunTaskEvent) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *RunTaskEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunTaskEvent) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *RunTaskEvent) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

// PingRequest / PingResponse for health-check.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_src_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_src_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// SubAgentRequest dispatches work to a sub-agent.
type SubAgentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Task         string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Model        string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	LlmProvider  string                 `protobuf:"bytes,3,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	LlmEndpoint  string                 `protobuf:"bytes,4,opt,name=llm_endpoint,json=llmEndpoint,proto3" json:"llm_endpoint,omitempty"`
	SystemPrompt string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	MaxTokens    int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature  float32                `protobuf:"fixed32,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Optional remote gRPC endpoint for the sub-agent (host:port).
	// When empty, the receiving agent executes the request in-process via goroutine.
	SubAgentAddress string `protobuf:"bytes,8,opt,name=sub_agent_address,json=subAgentAddress,proto3" json:"sub_agent_address,omitempty"`
	// Preferred configuration surface for sub-agent execution.
	RuntimeConfig *AgentRuntimeConfig `protobuf:"bytes,9,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	// Toolset configuration for the sub-agent.
	ToolsetConfig *ToolsetConfig `protobuf:"bytes,10,opt,name=toolset_config,json=toolsetConfig,proto3" json:"toolset_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAgentRequest) Reset() {
	*x = SubAgentRequest{}
	mi := &file_src_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAgentRequest) ProtoMessage() {}

func (x *SubAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAgentRequest.ProtoReflect.Descriptor instead.
func (*SubAgentRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubAgentRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *SubAgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SubAgentRequest) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *SubAgentRequest) GetLlmEndpoint() string {
	if x != nil {
		return x.LlmEndpoint
	}
	return ""
}

func (x *SubAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *SubAgentRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SubAgentRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SubAgentRequest) GetSubAgentAddress() string {
	if x != nil {
		return x.SubAgentAddress
	}
	return ""
}

func (x *SubAgentRequest) GetRuntimeConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

func (x *SubAgentRequest) GetToolsetConfig() *ToolsetConfig {
	if x != nil {
		return x.ToolsetConfig
	}
	return nil
}

// SubAgentResponse carries the sub-agent's final answer.
type SubAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAgentResponse) Reset() {
	*x = SubAgentResponse{}
	mi := &file_src_proto_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAgentResponse) ProtoMessage() {}

func (x *SubAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAgentResponse.ProtoReflect.Descriptor instead.
func (*SubAgentResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubAgentResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SubAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// MCPServerConfig describes a single MCP server the agent should connect to.
type MCPServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name for this server (used in logs and tool namespacing).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Transport type.
	Transport MCPTransportType `protobuf:"varint,2,opt,name=transport,proto3,enum=ohc.agent.service.MCPTransportType" json:"transport,omitempty"`
	// STDIO transport: command and arguments to launch the MCP process.
	// command[0] is the executable; subsequent elements are its arguments.
	Command []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	// SSE transport: base URL of the MCP HTTP endpoint.
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Environment variables forwarded to the MCP subprocess (STDIO only).
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If non-empty, expose only these tool names from this server.
	// An empty list means all tools from the server are exposed.
	AllowedTools  []string `protobuf:"bytes,6,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServerConfig) Reset() {
	*x = MCPServerConfig{}
	mi := &file_src_proto_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServerConfig) ProtoMessage() {}

func (x *MCPServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServerConfig.ProtoReflect.Descriptor instead.
func (*MCPServerConfig) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *MCPServerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPServerConfig) GetTransport() MCPTransportType {
	if x != nil {
		return x.Transport
	}
	return MCPTransportType_MCP_TRANSPORT_UNSPECIFIED
}

func (x *MCPServerConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MCPServerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MCPServerConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MCPServerConfig) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

// SkillConfig defines a named skill that the agent can use as a sub-capability.
// Skills are modelled as sub-agents with a focused instruction.
// All fields are stored in the database and passed from user → agent → subagent
// without any additional serialization step.
type SkillConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name for the skill.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One-line description used when the orchestrator selects this skill.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The instruction / system prompt for this skill sub-agent.
	Instruction string `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// Optional: which built-in tools to enable for this skill.
	// When empty, the skill inherits the parent agent's toolset.
	AllowedTools []string `protobuf:"bytes,4,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	// Optional: override the LLM model for this skill sub-agent.
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// Optional: the toolset configuration for this skill's sub-agent.
	// Overrides the parent toolset if provided.
	Toolset       *ToolsetConfig `protobuf:"bytes,6,opt,name=toolset,proto3" json:"toolset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillConfig) Reset() {
	*x = SkillConfig{}
	mi := &file_src_proto_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillConfig) ProtoMessage() {}

func (x *SkillConfig) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillConfig.ProtoReflect.Descriptor instead.
func (*SkillConfig) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *SkillConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillConfig) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *SkillConfig) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

func (x *SkillConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SkillConfig) GetToolset() *ToolsetConfig {
	if x != nil {
		return x.Toolset
	}
	return nil
}

// ToolsetConfig fully describes the tools, MCP servers, and skills that should
// be available to a builtin agent instance.  It replaces hardcoded Go tool
// lists and is the single source of truth for agent capability.
type ToolsetConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Built-in tool names to expose (Bash, Read, Write, Glob, Grep, WebFetch,
	// WebSearch, SendMessage, TodoWrite, ToolSearch, TaskCreate, TaskGet,
	// TaskList, TaskUpdate).
	// An empty list enables ALL built-in tools (default behaviour).
	BuiltinTools []string `protobuf:"bytes,1,rep,name=builtin_tools,json=builtinTools,proto3" json:"builtin_tools,omitempty"`
	// MCP servers to connect; tools from each server are added to the agent.
	McpServers []*MCPServerConfig `protobuf:"bytes,2,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	// Skills to register as callable sub-capabilities.
	Skills        []*SkillConfig `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsetConfig) Reset() {
	*x = ToolsetConfig{}
	mi := &file_src_proto_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsetConfig) ProtoMessage() {}

func (x *ToolsetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsetConfig.ProtoReflect.Descriptor instead.
func (*ToolsetConfig) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *ToolsetConfig) GetBuiltinTools() []string {
	if x != nil {
		return x.BuiltinTools
	}
	return nil
}

func (x *ToolsetConfig) GetMcpServers() []*MCPServerConfig {
	if x != nil {
		return x.McpServers
	}
	return nil
}

func (x *ToolsetConfig) GetSkills() []*SkillConfig {
	if x != nil {
		return x.Skills
	}
	return nil
}

// TaskNotification is sent to the parent agent when a sub-agent task completes.
// It replaces the legacy XML <task-notification> format.
type TaskNotification struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ToolUseId  string                 `protobuf:"bytes,2,opt,name=tool_use_id,json=toolUseId,proto3" json:"tool_use_id,omitempty"`
	OutputFile string                 `protobuf:"bytes,3,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	// Terminal status: "completed" | "failed" | "killed"
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary       string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Result        string `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	TokenCount    int64  `protobuf:"varint,7,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ToolUses      int64  `protobuf:"varint,8,opt,name=tool_uses,json=toolUses,proto3" json:"tool_uses,omitempty"`
	DurationMs    int64  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskNotification) Reset() {
	*x = TaskNotification{}
	mi := &file_src_proto_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskNotification) ProtoMessage() {}

func (x *TaskNotification) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskNotification.ProtoReflect.Descriptor instead.
func (*TaskNotification) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *TaskNotification) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskNotification) GetToolUseId() string {
	if x != nil {
		return x.ToolUseId
	}
	return ""
}

func (x *TaskNotification) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *TaskNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskNotification) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TaskNotification) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskNotification) GetTokenCount() int64 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *TaskNotification) GetToolUses() int64 {
	if x != nil {
		return x.ToolUses
	}
	return 0
}

func (x *TaskNotification) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// SubagentHeartbeat is published periodically by a running sub-agent.
// The parent considers the sub-agent dead if no heartbeat arrives within
// the configured heartbeat_timeout window (default 30 minutes).
type SubagentHeartbeat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Current status: "running" | "completed" | "failed"
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TokenCount    int64  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ToolUseCount  int64  `protobuf:"varint,5,opt,name=tool_use_count,json=toolUseCount,proto3" json:"tool_use_count,omitempty"`
	LastActivity  string `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubagentHeartbeat) Reset() {
	*x = SubagentHeartbeat{}
	mi := &file_src_proto_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubagentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubagentHeartbeat) ProtoMessage() {}

func (x *SubagentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubagentHeartbeat.ProtoReflect.Descriptor instead.
func (*SubagentHeartbeat) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *SubagentHeartbeat) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubagentHeartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *SubagentHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubagentHeartbeat) GetTokenCount() int64 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *SubagentHeartbeat) GetToolUseCount() int64 {
	if x != nil {
		return x.ToolUseCount
	}
	return 0
}

func (x *SubagentHeartbeat) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

// SubagentLifecycleEvent is the unified event type for the subagent pub/sub bus.
// Agents publish and subscribe to these events instead of polling.
type SubagentLifecycleEvent struct {
	state     protoimpl.MessageState           `protogen:"open.v1"`
	EventType SubagentLifecycleEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=ohc.agent.service.SubagentLifecycleEvent_EventType" json:"event_type,omitempty"`
	TaskId    string                           `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// parent_task_id links this sub-agent to its spawning parent.
	ParentTaskId string `protobuf:"bytes,3,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"`
	TimestampMs  int64  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// payload is set according to event_type.
	// HEARTBEAT → heartbeat; COMPLETED/FAILED/KILLED → notification.
	Heartbeat     *SubagentHeartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Notification  *TaskNotification  `protobuf:"bytes,6,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubagentLifecycleEvent) Reset() {
	*x = SubagentLifecycleEvent{}
	mi := &file_src_proto_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubagentLifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubagentLifecycleEvent) ProtoMessage() {}

func (x *SubagentLifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubagentLifecycleEvent.ProtoReflect.Descriptor instead.
func (*SubagentLifecycleEvent) Descriptor() ([]byte, []int) {
	return file_src_proto_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *SubagentLifecycleEvent) GetEventType() SubagentLifecycleEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return SubagentLifecycleEvent_EVENT_UNSPECIFIED
}

func (x *SubagentLifecycleEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubagentLifecycleEvent) GetParentTaskId() string {
	if x != nil {
		return x.ParentTaskId
	}
	return ""
}

func (x *SubagentLifecycleEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *SubagentLifecycleEvent) GetHeartbeat() *SubagentHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *SubagentLifecycleEvent) GetNotification() *TaskNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_src_proto_agent_service_proto protoreflect.FileDescriptor

const file_src_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsrc/proto/agent_service.proto\x12\x11ohc.agent.service\"\xaf\x02\n" +
	"\x12AgentRuntimeConfig\x12!\n" +
	"\fllm_provider\x18\x01 \x01(\tR\vllmProvider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_endpoint\x18\x03 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12%\n" +
	"\x0emax_iterations\x18\a \x01(\x05R\rmaxIterations\x120\n" +
	"\x14max_context_messages\x18\b \x01(\x05R\x12maxContextMessages\"\xe8\x03\n" +
	"\x0eRunTaskRequest\x12\x17\n" +
	"\atask_id\x18\v \x01(\tR\x06taskId\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12!\n" +
	"\fllm_endpoint\x18\x04 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x02R\vtemperature\x120\n" +
	"\x14max_context_messages\x18\b \x01(\x05R\x12maxContextMessages\x12L\n" +
	"\x0eruntime_config\x18\t \x01(\v2%.ohc.agent.service.AgentRuntimeConfigR\rruntimeConfig\x12G\n" +
	"\x0etoolset_config\x18\n" +
	" \x01(\v2 .ohc.agent.service.ToolsetConfigR\rtoolsetConfig\x12\x1e\n" +
	"\n" +
	"department\x18\f \x01(\tR\n" +
	"department\"\x97\x02\n" +
	"\fRunTaskEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.ohc.agent.service.EventTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12$\n" +
	"\x0etool_args_json\x18\x04 \x01(\tR\ftoolArgsJson\x12\x1f\n" +
	"\vtool_result\x18\x05 \x01(\tR\n" +
	"toolResult\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1c\n" +
	"\titeration\x18\a \x01(\x05R\titeration\x12#\n" +
	"\rmessage_count\x18\b \x01(\x05R\fmessageCount\"\r\n" +
	"\vPingRequest\"C\n" +
	"\fPingResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xaa\x03\n" +
	"\x0fSubAgentRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fllm_provider\x18\x03 \x01(\tR\vllmProvider\x12!\n" +
	"\fllm_endpoint\x18\x04 \x01(\tR\vllmEndpoint\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x02R\vtemperature\x12*\n" +
	"\x11sub_agent_address\x18\b \x01(\tR\x0fsubAgentAddress\x12L\n" +
	"\x0eruntime_config\x18\t \x01(\v2%.ohc.agent.service.AgentRuntimeConfigR\rruntimeConfig\x12G\n" +
	"\x0etoolset_config\x18\n" +
	" \x01(\v2 .ohc.agent.service.ToolsetConfigR\rtoolsetConfig\"@\n" +
	"\x10SubAgentResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xba\x02\n" +
	"\x0fMCPServerConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\ttransport\x18\x02 \x01(\x0e2#.ohc.agent.service.MCPTransportTypeR\ttransport\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12=\n" +
	"\x03env\x18\x05 \x03(\v2+.ohc.agent.service.MCPServerConfig.EnvEntryR\x03env\x12#\n" +
	"\rallowed_tools\x18\x06 \x03(\tR\fallowedTools\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\vSkillConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\x12#\n" +
	"\rallowed_tools\x18\x04 \x03(\tR\fallowedTools\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12:\n" +
	"\atoolset\x18\x06 \x01(\v2 .ohc.agent.service.ToolsetConfigR\atoolset\"\xb1\x01\n" +
	"\rToolsetConfig\x12#\n" +
	"\rbuiltin_tools\x18\x01 \x03(\tR\fbuiltinTools\x12C\n" +
	"\vmcp_servers\x18\x02 \x03(\v2\".ohc.agent.service.MCPServerConfigR\n" +
	"mcpServers\x126\n" +
	"\x06skills\x18\x03 \x03(\v2\x1e.ohc.agent.service.SkillConfigR\x06skills\"\x95\x02\n" +
	"\x10TaskNotification\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vtool_use_id\x18\x02 \x01(\tR\ttoolUseId\x12\x1f\n" +
	"\voutput_file\x18\x03 \x01(\tR\n" +
	"outputFile\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1f\n" +
	"\vtoken_count\x18\a \x01(\x03R\n" +
	"tokenCount\x12\x1b\n" +
	"\ttool_uses\x18\b \x01(\x03R\btoolUses\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\"\xd3\x01\n" +
	"\x11SubagentHeartbeat\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x03R\n" +
	"tokenCount\x12$\n" +
	"\x0etool_use_count\x18\x05 \x01(\x03R\ftoolUseCount\x12#\n" +
	"\rlast_activity\x18\x06 \x01(\tR\flastActivity\"\xc2\x03\n" +
	"\x16SubagentLifecycleEvent\x12R\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e23.ohc.agent.service.SubagentLifecycleEvent.EventTypeR\teventType\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12$\n" +
	"\x0eparent_task_id\x18\x03 \x01(\tR\fparentTaskId\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12B\n" +
	"\theartbeat\x18\x05 \x01(\v2$.ohc.agent.service.SubagentHeartbeatR\theartbeat\x12G\n" +
	"\fnotification\x18\x06 \x01(\v2#.ohc.agent.service.TaskNotificationR\fnotification\"e\n" +
	"\tEventType\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSPAWNED\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\n" +
	"\n" +
	"\x06KILLED\x10\x05*\x91\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_CHUNK\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\x11\n" +
	"\rTASK_COMPLETE\x10\x03\x12\x0e\n" +
	"\n" +
	"TASK_ERROR\x10\x04\x12\x0f\n" +
	"\vRUN_STARTED\x10\x05\x12\x15\n" +
	"\x11ITERATION_STARTED\x10\x06*a\n" +
	"\x10MCPTransportType\x12\x1d\n" +
	"\x19MCP_TRANSPORT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MCP_TRANSPORT_STDIO\x10\x01\x12\x15\n" +
	"\x11MCP_TRANSPORT_SSE\x10\x022\x87\x02\n" +
	"\fAgentService\x12O\n" +
	"\aRunTask\x12!.ohc.agent.service.RunTaskRequest\x1a\x1f.ohc.agent.service.RunTaskEvent0\x01\x12G\n" +
	"\x04Ping\x12\x1e.ohc.agent.service.PingRequest\x1a\x1f.ohc.agent.service.PingResponse\x12]\n" +
	"\x12DispatchToSubAgent\x12\".ohc.agent.service.SubAgentRequest\x1a#.ohc.agent.service.SubAgentResponseBDZBgithub.com/onehumancorp/mono/src/proto/agentservice;agentservicepbb\x06proto3"

var (
	file_src_proto_agent_service_proto_rawDescOnce sync.Once
	file_src_proto_agent_service_proto_rawDescData []byte
)

func file_src_proto_agent_service_proto_rawDescGZIP() []byte {
	file_src_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_src_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_agent_service_proto_rawDesc), len(file_src_proto_agent_service_proto_rawDesc)))
	})
	return file_src_proto_agent_service_proto_rawDescData
}

var file_src_proto_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_src_proto_agent_service_proto_goTypes = []any{
	(EventType)(0),                        // 0: ohc.agent.service.EventType
	(MCPTransportType)(0),                 // 1: ohc.agent.service.MCPTransportType
	(SubagentLifecycleEvent_EventType)(0), // 2: ohc.agent.service.SubagentLifecycleEvent.EventType
	(*AgentRuntimeConfig)(nil),            // 3: ohc.agent.service.AgentRuntimeConfig
	(*RunTaskRequest)(nil),                // 4: ohc.agent.service.RunTaskRequest
	(*RunTaskEvent)(nil),                  // 5: ohc.agent.service.RunTaskEvent
	(*PingRequest)(nil),                   // 6: ohc.agent.service.PingRequest
	(*PingResponse)(nil),                  // 7: ohc.agent.service.PingResponse
	(*SubAgentRequest)(nil),               // 8: ohc.agent.service.SubAgentRequest
	(*SubAgentResponse)(nil),              // 9: ohc.agent.service.SubAgentResponse
	(*MCPServerConfig)(nil),               // 10: ohc.agent.service.MCPServerConfig
	(*SkillConfig)(nil),                   // 11: ohc.agent.service.SkillConfig
	(*ToolsetConfig)(nil),                 // 12: ohc.agent.service.ToolsetConfig
	(*TaskNotification)(nil),              // 13: ohc.agent.service.TaskNotification
	(*SubagentHeartbeat)(nil),             // 14: ohc.agent.service.SubagentHeartbeat
	(*SubagentLifecycleEvent)(nil),        // 15: ohc.agent.service.SubagentLifecycleEvent
	nil,                                   // 16: ohc.agent.service.MCPServerConfig.EnvEntry
}
var file_src_proto_agent_service_proto_depIdxs = []int32{
	3,  // 0: ohc.agent.service.RunTaskRequest.runtime_config:type_name -> ohc.agent.service.AgentRuntimeConfig
	12, // 1: ohc.agent.service.RunTaskRequest.toolset_config:type_name -> ohc.agent.service.ToolsetConfig
	0,  // 2: ohc.agent.service.RunTaskEvent.type:type_name -> ohc.agent.service.EventType
	3,  // 3: ohc.agent.service.SubAgentRequest.runtime_config:type_name -> ohc.agent.service.AgentRuntimeConfig
	12, // 4: ohc.agent.service.SubAgentRequest.toolset_config:type_name -> ohc.agent.service.ToolsetConfig
	1,  // 5: ohc.agent.service.MCPServerConfig.transport:type_name -> ohc.agent.service.MCPTransportType
	16, // 6: ohc.agent.service.MCPServerConfig.env:type_name -> ohc.agent.service.MCPServerConfig.EnvEntry
	12, // 7: ohc.agent.service.SkillConfig.toolset:type_name -> ohc.agent.service.ToolsetConfig
	10, // 8: ohc.agent.service.ToolsetConfig.mcp_servers:type_name -> ohc.agent.service.MCPServerConfig
	11, // 9: ohc.agent.service.ToolsetConfig.skills:type_name -> ohc.agent.service.SkillConfig
	2,  // 10: ohc.agent.service.SubagentLifecycleEvent.event_type:type_name -> ohc.agent.service.SubagentLifecycleEvent.EventType
	14, // 11: ohc.agent.service.SubagentLifecycleEvent.heartbeat:type_name -> ohc.agent.service.SubagentHeartbeat
	13, // 12: ohc.agent.service.SubagentLifecycleEvent.notification:type_name -> ohc.agent.service.TaskNotification
	4,  // 13: ohc.agent.service.AgentService.RunTask:input_type -> ohc.agent.service.RunTaskRequest
	6,  // 14: ohc.agent.service.AgentService.Ping:input_type -> ohc.agent.service.PingRequest
	8,  // 15: ohc.agent.service.AgentService.DispatchToSubAgent:input_type -> ohc.agent.service.SubAgentRequest
	5,  // 16: ohc.agent.service.AgentService.RunTask:output_type -> ohc.agent.service.RunTaskEvent
	7,  // 17: ohc.agent.service.AgentService.Ping:output_type -> ohc.agent.service.PingResponse
	9,  // 18: ohc.agent.service.AgentService.DispatchToSubAgent:output_type -> ohc.agent.service.SubAgentResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_src_proto_agent_service_proto_init() }
func file_src_proto_agent_service_proto_init() {
	if File_src_proto_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_agent_service_proto_rawDesc), len(file_src_proto_agent_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_src_proto_agent_service_proto_depIdxs,
		EnumInfos:         file_src_proto_agent_service_proto_enumTypes,
		MessageInfos:      file_src_proto_agent_service_proto_msgTypes,
	}.Build()
	File_src_proto_agent_service_proto = out.File
	file_src_proto_agent_service_proto_goTypes = nil
	file_src_proto_agent_service_proto_depIdxs = nil
}
