// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package agentpb

import (
	common "github.com/onehumancorp/mono/srcs/proto/ohc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role           common.Role            `protobuf:"varint,2,opt,name=role,proto3,enum=ohc.common.Role" json:"role,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status         common.AgentStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=ohc.common.AgentStatus" json:"status,omitempty"`
	OrganizationId string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetRole() common.Role {
	if x != nil {
		return x.Role
	}
	return common.Role(0)
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetStatus() common.AgentStatus {
	if x != nil {
		return x.Status
	}
	return common.AgentStatus(0)
}

func (x *Agent) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type AgentMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAgentId    string                 `protobuf:"bytes,2,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	ToAgentId      string                 `protobuf:"bytes,3,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"`
	MessageType    string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MeetingId      string                 `protobuf:"bytes,6,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMessage) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *AgentMessage) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *AgentMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMessage) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *AgentMessage) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\tohc.agent\x1a\x12proto/common.proto\"\xab\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04role\x18\x02 \x01(\x0e2\x10.ohc.common.RoleR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.ohc.common.AgentStatusR\x06status\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\"\xe8\x01\n" +
	"\fAgentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rfrom_agent_id\x18\x02 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x03 \x01(\tR\ttoAgentId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x06 \x01(\tR\tmeetingId\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix2\x8d\x01\n" +
	"\x12AgentOrchestration\x123\n" +
	"\rRegisterAgent\x12\x10.ohc.agent.Agent\x1a\x10.ohc.agent.Agent\x12B\n" +
	"\x0ePublishMessage\x12\x17.ohc.agent.AgentMessage\x1a\x17.ohc.agent.AgentMessageB;Z9github.com/onehumancorp/mono/srcs/proto/ohc/agent;agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agent_proto_goTypes = []any{
	(*Agent)(nil),           // 0: ohc.agent.Agent
	(*AgentMessage)(nil),    // 1: ohc.agent.AgentMessage
	(common.Role)(0),        // 2: ohc.common.Role
	(common.AgentStatus)(0), // 3: ohc.common.AgentStatus
}
var file_proto_agent_proto_depIdxs = []int32{
	2, // 0: ohc.agent.Agent.role:type_name -> ohc.common.Role
	3, // 1: ohc.agent.Agent.status:type_name -> ohc.common.AgentStatus
	0, // 2: ohc.agent.AgentOrchestration.RegisterAgent:input_type -> ohc.agent.Agent
	1, // 3: ohc.agent.AgentOrchestration.PublishMessage:input_type -> ohc.agent.AgentMessage
	0, // 4: ohc.agent.AgentOrchestration.RegisterAgent:output_type -> ohc.agent.Agent
	1, // 5: ohc.agent.AgentOrchestration.PublishMessage:output_type -> ohc.agent.AgentMessage
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
