exports_files(["Cargo.toml"])

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "llm",
    srcs = [
        "anthropic.rs",
        "gemini.rs",
        "mod.rs",
        "ollama.rs",
        "openai.rs",
    ],
    crate_root = "mod.rs",
    crate_name = "ohc_builtin_agent_llm",

    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/agents/builtin:core",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
        "@crates//:tracing",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],

)

rust_test(
    name = "llm_unit_test",
    crate = ":llm",
    edition = "2024",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
