[package]
name = "ohc_builtin_agent_llm"
version = "0.1.0"
edition = "2024"

[lib]
path = "mod.rs"

[dependencies]
async-trait = "0.1"
ohc_builtin_agent_core = { path = "../core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
