load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "server_inbox",
    srcs = ["mod.rs", "service.rs"],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/ohc:server_ohc",
        "@crates//:tonic",
    ],
)

rust_test(
    name = "test",
    crate = ":server_inbox",
    deps = [
        "@crates//:tokio",
    ],
)
