load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "harness",
    srcs = ["macos_sandbox.go"],
    importpath = "onehumancorp/srcs/server/orchestration/harness",
    visibility = ["//visibility:public"],
)

go_test(
    name = "harness_test",
    srcs = ["macos_sandbox_test.go"],
    embed = [":harness"],
)
