load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "queue",
    srcs = [
        "queue.go",
        "worker_pool.go",
    ],
    importpath = "mono/srcs/server/orchestration/queue",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "queue_test",
    srcs = ["worker_test.go"],
    embed = [":queue"],
)
