load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "queue",
    srcs = [
        "inmem_job_queue.go",
        "postgres_queue.go",
        "queue.go",
        "queue_manager.go",
        "queue_manager_loop.go",
        "redis_job_queue.go",
        "redis_queue.go",
        "sqlite_queue.go",
        "worker.go",
        "worker_pool.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/orchestration/queue",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/db",
        "//srcs/server/telemetry",
        "@com_github_redis_rueidis//:rueidis",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "queue_test",
    srcs = [
        "job_queue_test.go",
        "queue_manager_loop_test.go",
        "queue_test.go",
        "redis_queue_test.go",
        "worker_test.go",
    ],
    embed = [":queue"],
    deps = [
        "//srcs/server/db",
        "@com_github_redis_rueidis//:rueidis",
        "@org_modernc_sqlite//:sqlite",
    ],
)
