load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "memory",
    srcs = [
        "src/lib.rs",
        "src/memory.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:redis",
    ],
)

rust_test(
    name = "memory_test",
    crate = ":memory",
    deps = [
        "@crates//:redis",
    ],
)
