load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "authz",
    srcs = ["authorizer.go"],
    importpath = "github.com/onehumancorp/mono/src/server/harness/authz",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/telemetry",
        "//src/server/db",
        "//src/server/db/models",
    ],
)
