load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mcp",
    srcs = ["client_manager.go"],
    importpath = "github.com/onehumancorp/mono/src/server/harness/mcp",
    visibility = ["//visibility:public"],
    deps = ["//src/server_old/agents/local", "//src/server_old/utils"],
)

go_test(
    name = "mcp_test",
    srcs = ["client_manager_test.go"],
    embed = [":mcp"],
    deps = ["//src/server_old/agents/local", "//src/server_old/utils"],
)
