load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pricing",
    srcs = [
        "budget.go",
        "cache.go",
        "calculator.go",
        "compression.go",
        "deduplicator.go",
        "pricing.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/lib/pricing",
    visibility = ["//visibility:public"],
)

go_test(
    name = "pricing_test",
    srcs = [
        "budget_test.go",
        "cache_test.go",
        "calculator_test.go",
        "compression_test.go",
        "deduplicator_test.go",
        "pricing_test.go",
    ],
    embed = [":pricing"],
)
