load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pricing",
    srcs = ["calculator.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/lib/pricing",
    visibility = ["//visibility:public"],
)

go_test(
    name = "pricing_test",
    srcs = ["calculator_test.go"],
    embed = [":pricing"],
)
