load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(
    [
        "mod.rs",
        "fx_cache.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "server_services_localization",
    srcs = [
        "mod.rs",
        "fx_cache.rs",
    ],
    crate_root = "mod.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:sqlx",
        "@crates//:redis",
    ],
)
