load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = ["mesh_handler.go"],
    importpath = "onehumancorp/srcs/server/api/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "//srcs/server/orchestration:orchestration",
        "//srcs/server/pb:pb",
    ],
)

go_test(
    name = "mesh_test",
    srcs = ["mesh_handler_test.go"],
    embed = [":mesh"],
    deps = [
        "//srcs/server/orchestration:orchestration",
        "//srcs/server/pb:pb",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
