load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "server_omnichannel",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = [
        "@crates//:axum",
        "@crates//:tokio",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:uuid",
        "@crates//:chrono",
    ],
    visibility = ["//visibility:public"],
)
