export const E2E_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  PRICING: '/pricing',
  LOGS: '/logs',
  MEETINGS: '/meetings',
  DIAGNOSTICS: '/diagnostics',
  SERVICES: '/services',
  SCALING: '/scaling',
  MY_PLAN: '/my-plan',
  WEBSITE_BUILDER: '/website-builder',
  SOCIAL_POSTING: '/social-posting',
  AGENTS: '/agents',
  INBOX: '/inbox',
  REFERRALS: '/referrals',
  APP: '/app',
  USERS: '/users',
  ONBOARDING: '/onboarding',
  HELP: '/help',
  ADMIN: '/admin',
  GROWTH: '/growth',
  TEAM: '/team',
  STORE: '/store',
  MARKETING: '/marketing',
  SECURITY: '/security',
};

export const UI_LOCATORS = {
  NEXT_BUTTON: 'button:has-text("Next")',
  LOGIN_BUTTON: 'button:has-text("Login")',
  PASSWORD_INPUT: 'input[type="password"]',
  WELCOME_TEXT: 'text="Welcome back, Human."',
  CONFETTI: 'text=/CONFETTI.*SUCCESS/i',
  PHYSICAL_PRODUCTS: 'text=Physical products',
  ONLINE_ONLY: 'text=Online only',
  ONLINE_STORE: 'text=Online Store',
  MODERN: 'text=Modern',
  FREE_DOMAIN: 'text=Free OHC Domain',
  ONBOARDING_COMPLETE: 'text="Onboarding Complete!"',
  ALMOST_THERE: 'text="Almost there"',
  WELCOME_CHECKLIST: 'text="Welcome Checklist"',
  SETUP_CHECKLIST: 'text="Continue to Setup Checklist"',
  GET_STARTED: 'button:has-text("Get Started")',
  CONTINUE: 'button:has-text("Continue")',
  SAVE: 'button:has-text("Save")',
  CANCEL: 'button:has-text("Cancel")',
  SUBMIT: 'button:has-text("Submit")',
  CREATE: 'button:has-text("Create")',
  DELETE: 'button:has-text("Delete")',
  EDIT: 'button:has-text("Edit")',
  DASHBOARD_TITLE: 'text="Dashboard"',
  SETTINGS_TITLE: 'text="Settings"',
  LOGOUT: 'button:has-text("Logout")',
  PROFILE: 'text="Profile"',
  EMAIL_INPUT: 'input[type="email"]',
  SEARCH_INPUT: 'input[type="search"]',
  AGENTS_TITLE: 'text="Agents"',
  MEETINGS_TITLE: 'text="Meetings"',
  SUCCESS_TOAST: 'text="Success"',
  ERROR_TOAST: 'text="Error"',
  SCHEDULE_MEETING: 'button:has-text("Schedule"), button:has-text("New Meeting")',
  CUSTOMER_INBOX: 'text="Customer Inbox"',
  SERVICE_CLASS: '[class*="service"]',
  REFERRAL_PROGRAM: 'text=Referral Program',
  TEAM_USERS: 'button:has-text("Users"), button:has-text("Team"), a[href*="/users"]',
  REFERRALS_BTN: 'button:has-text("Referrals")',
  AUTHORIZING: 'text=/authorizing|connecting/i',
  PUBLISH_BUSINESS: 'text="Publish my business →"',
  ADD_USER: 'button:has-text("Add User"), button:has-text("Invite")',
  MARK_ORDER_READY: 'button:has-text("Mark Order Ready")',
  UPDATE_BTN: 'button:has-text("Update")',
  DASHBOARD_TEXT: 'text=Dashboard',
  STAGE_CLASS: '[class*="stage"]',
  VEGAN_CAKES: 'text="Do you do vegan cakes?"',
  SCALE_UP: 'text=Scale Up Your Team',
  LAUNCH_BUSINESS: 'text="Launch My Business →"',
  START_MY_BUSINESS: 'button:has-text("🚀 Start My Business")',
  PUBLISHING_SITE: 'text="Publishing Site..."',
  PENDING_INVITES: 'button:has-text("Pending"), button:has-text("Invitations")',
  USER_CLASS: '[class*="user"]',
  ADVANCED_TEXT: 'text=Advanced',
  FIRST_SALE: 'text=First Sale!',
  SELECT_INPUT: 'select',
  SETUP_WIZARD: 'text="Setup Wizard"',
  MEETING_CLASS: '[class*="meeting"]',
  LOG_CLASS: '[class*="log"]',
  SIGN_IN_MANAGE: 'text="Sign in to manage your business"',
  HIRE_AGENT: 'button:has-text("Hire Agent")',
  SERVICES_APPT: 'text=📅 Services / appointments',
  FOOD_BEV: 'text=🍕 Food & beverages',
  YOUR_LIVE_STOREFRONT: 'text=Your live storefront!',
  DESIGNING_STOREFRONT: 'text=Designing your storefront...',
  START_MY_BUSINESS_TEXT: 'text=🚀 Start My Business',
  INSTANT_BUILD: 'text=⚡ Instant Build (AI) →',
  THE_AMBASSADOR: 'text=The Ambassador',
  RAW_CONFIG: 'text=Raw Config Settings',
  WHAT_KIND_BUSINESS: 'text=/What kind of business/i',
  SUCCESS_BUSINESS_LIVE: 'text=/Success! Your business is live/i',
  READY_TO_LAUNCH: 'text=/Ready to launch/i',
  LAUNCH_MY_BUSINESS: 'button:has-text("Launch My Business")',
  CHOOSE_TEMPLATE: 'text="Choose a template"',
  SHARE_OHC: 'text=Share OHC with a friend, both get 1 month free Pro.',
  INVITE_USER: 'button:has-text("Invite User")',
  START_BUSINESS_SETUP: 'button:has-text("🚀 Start Business Setup")',
  NAV: 'nav',
  DELETE_REMOVE: 'button:has-text("Delete"), button:has-text("Remove")',
  ROLE_CLASS: '[class*="role"]',
  INVALID_TEXT: 'text="Invalid"',
  ACTIONABLE_INSIGHTS: 'text="Actionable Insights"',
  CHECKBOX_INPUT: 'input[type="checkbox"]',
  SIGN_IN_BTN: 'button:has-text("Sign In")',
  HYBRID_CORRELATION: 'text=[ Dynamic Hybrid Correlation Chart ]',
  RAG_LATENCY: 'text=RAG Latency',
  LLM_CACHE_HITS: 'text=LLM Cache Hits',
  AUTODREAM_PIPELINE: 'text=AutoDream Memory Pipeline',
  DISMISS_BTN: 'button:has-text("Dismiss")',
  DRAFTED_IG_POST: 'text=Drafted Instagram Post',
  NAV_AGENTS: 'nav a:has-text("Agents")',
  SAVE_TEXT: 'text=Save',
  CANCEL_TEXT: 'text=Cancel',
  SUBMIT_TEXT: 'text=Submit',
  DELETE_TEXT: 'text=Delete',
  EDIT_TEXT: 'text=Edit',
  BACK_TEXT: 'text=Back',
  FORWARD_TEXT: 'text=Forward',
  CONTINUE_TEXT: 'text=Continue',
  START_TEXT: 'text=Start',
  STOP_TEXT: 'text=Stop',
  HELP_TEXT: 'text=Help',
  INFO_TEXT: 'text=Info',
  WARNING_TEXT: 'text=Warning',
  SETTINGS_TEXT: 'text=Settings',
  PROFILE_TEXT: 'text=Profile',
  LOGOUT_TEXT: 'text=Logout',
  ACCOUNT_TEXT: 'text=Account',
  BILLING_TEXT: 'text=Billing',
  PRICING_TEXT: 'text=Pricing',
  PLANS_TEXT: 'text=Plans',
  UPGRADE_TEXT: 'text=Upgrade',
  DOWNGRADE_TEXT: 'text=Downgrade',
  SUBSCRIBE_TEXT: 'text=Subscribe',
  UNSUBSCRIBE_TEXT: 'text=Unsubscribe',
  LOGIN_TEXT: 'text=Login',
  REGISTER_TEXT: 'text=Register',
  SIGN_UP_TEXT: 'text=Sign Up',
  FORGOT_PASSWORD_TEXT: 'text=Forgot Password',
  RESET_PASSWORD_TEXT: 'text=Reset Password',
  CONFIRM_TEXT: 'text=Confirm',
  VERIFY_TEXT: 'text=Verify',
  ACCEPT_TEXT: 'text=Accept',
  DECLINE_TEXT: 'text=Decline',
  AGREE_TEXT: 'text=Agree',
  DISAGREE_TEXT: 'text=Disagree',
  UPLOAD_TEXT: 'text=Upload',
  DOWNLOAD_TEXT: 'text=Download',
  IMPORT_TEXT: 'text=Import',
  EXPORT_TEXT: 'text=Export',
  SHARE_TEXT: 'text=Share',
  COPY_TEXT: 'text=Copy',
  PASTE_TEXT: 'text=Paste',
  CUT_TEXT: 'text=Cut',
  UNDO_TEXT: 'text=Undo',
  REDO_TEXT: 'text=Redo',
  SEARCH_TEXT: 'text=Search',
  FIND_TEXT: 'text=Find',
  FILTER_TEXT: 'text=Filter',
  SORT_TEXT: 'text=Sort',
  GROUP_TEXT: 'text=Group',
  ADD_TEXT: 'text=Add',
  REMOVE_TEXT: 'text=Remove',
  CLEAR_TEXT: 'text=Clear',
  RESET_TEXT: 'text=Reset',
  APPLY_TEXT: 'text=Apply',
  VIEW_TEXT: 'text=View',
  HIDE_TEXT: 'text=Hide',
  SHOW_TEXT: 'text=Show',
  EXPAND_TEXT: 'text=Expand',
  COLLAPSE_TEXT: 'text=Collapse',
  OPEN_TEXT: 'text=Open',
  CLOSE_TEXT: 'text=Close',
  MENU_TEXT: 'text=Menu',
  NAVIGATION_TEXT: 'text=Navigation',
  HOME_TEXT: 'text=Home',
  DASHBOARD_TEXT_2: 'text=Dashboard',
  WELCOME_TEXT_2: 'text=Welcome',
  GOODBYE_TEXT: 'text=Goodbye',
  HELLO_TEXT: 'text=Hello',
  STATUS_TEXT: 'text=Status',
  ERROR_TEXT_2: 'text=Error',
  WARNING_TEXT_2: 'text=Warning',
  INFO_TEXT_2: 'text=Info',
  SUCCESS_TEXT_2: 'text=Success',
  FAIL_TEXT: 'text=Fail',
  PASS_TEXT: 'text=Pass',
  ACTIVE_TEXT: 'text=Active',
  INACTIVE_TEXT: 'text=Inactive',
  ONLINE_TEXT: 'text=Online',
  OFFLINE_TEXT: 'text=Offline',
  BUSY_TEXT: 'text=Busy',
  AWAY_TEXT: 'text=Away',
  AVAILABLE_TEXT: 'text=Available',
  UNAVAILABLE_TEXT: 'text=Unavailable',
  ADMIN_TEXT: 'text=Admin',
  USER_TEXT: 'text=User',
  GUEST_TEXT: 'text=Guest',
  MANAGER_TEXT: 'text=Manager',
  AGENT_TEXT: 'text=Agent',
  CLIENT_TEXT: 'text=Client',
  CUSTOMER_TEXT: 'text=Customer',
  PARTNER_TEXT: 'text=Partner',
  VENDOR_TEXT: 'text=Vendor',
  SUPPLIER_TEXT: 'text=Supplier',
  EMPLOYEE_TEXT: 'text=Employee',
  CONTRACTOR_TEXT: 'text=Contractor',
};
