import { expect, test } from './fixtures';

test('unified inbox E2E flow', async ({ page }) => {
  // 1. Navigate to integrations
  await page.goto('/integrations');
  await expect(page.getByRole('heading', { name: 'Tool Integrations' }).first()).toBeVisible();

  // Handle alerts generated by clicking "Connect" on the mocked OAuth flow
  page.on('dialog', async dialog => {
    await dialog.accept();
  });

  // 2. Connect Meta
  const metaCard = page.locator('div').filter({ hasText: /^Meta \(Facebook, Instagram, WhatsApp\)/ }).first();
  await expect(metaCard).toBeVisible();
  await metaCard.getByRole('button', { name: 'Connect' }).click();
  // Status should update to "Manage" or "connected" in UI (but since there's an alert, let's just make sure we clicked it)

  // 3. Connect TikTok
  const tiktokCard = page.locator('div').filter({ hasText: /^TikTok Business/ }).first();
  await expect(tiktokCard).toBeVisible();
  await tiktokCard.getByRole('button', { name: 'Connect' }).click();

  // 4. Navigate to unified inbox
  await page.goto('/inbox');
  await expect(page.getByRole('heading', { name: 'Customer Inbox' }).first()).toBeVisible();

  // 5. Verify messages from all platforms exist
  await expect(page.getByText('Facebook User').first()).toBeVisible();
  await expect(page.getByText('📘').first()).toBeVisible();
  await expect(page.getByText('Instagram User').first()).toBeVisible();
  await expect(page.getByText('📸').first()).toBeVisible();
  await expect(page.getByText('WhatsApp User').first()).toBeVisible();
  await expect(page.getByText('💬').first()).toBeVisible();
  await expect(page.getByText('TikTok User').first()).toBeVisible();
  await expect(page.getByText('🎵').first()).toBeVisible();

  // 6. Test replying to a message (TikTok)
  const tiktokMessage = page.locator('div').filter({ hasText: /^TikTok User/ }).filter({ hasText: /Do you have a physical store\?/ }).first();
  // The structure wraps the whole message block
  const draftElement = tiktokMessage.locator('..').locator('..').locator('text=Yes, we are located downtown!');
  await expect(draftElement).toBeVisible();

  // Find the send button associated with this draft
  const sendButton = tiktokMessage.locator('..').locator('..').getByRole('button', { name: 'Send' }).first();
  await expect(sendButton).toBeVisible();
  await sendButton.click();

  // Verify the reply appears as sent by "Me"
  await expect(page.getByText('Just now').first()).toBeVisible();
  await expect(page.getByText('Me').first()).toBeVisible();
  await expect(page.getByText('Yes, we are located downtown!').first()).toBeVisible();
});
