load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kairos",
    srcs = [
        "kairos_shared_task.go",
        "mesh.go",
        "mesh_api.go",
        "metrics.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/orchestration/kairos",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_nats_io_nats_go//:nats_go",
    ],
)

go_test(
    name = "kairos_test",
    srcs = [
        "kairos_shared_task_test.go",
        "mesh_test.go",
        "mesh_api_test.go",
        "metrics_test.go",
    ],
    embed = [":kairos"],
    deps = [
        "//src/server/db",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_alicebob_miniredis_v2//:miniredis",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_nats_io_nats_go//:nats_go",
        "@com_github_stretchr_testify//assert",
    ],
)
