load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tasks",
    srcs = ["orchestration.go"],
    importpath = "github.com/onehumancorp/mono/src/server/tasks",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
    ],
)

go_test(
    name = "tasks_test",
    srcs = ["orchestration_test.go"],
    embed = [":tasks"],
    deps = [
        "//src/server/db",
    ],
)
