-- Enable RLS for all new tables
ALTER TABLE agent_session_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE swarm_truth_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_tasks_v4 ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE swarm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE hybrid_fs_sync_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_tasks_decomposition ENABLE ROW LEVEL SECURITY;
ALTER TABLE department_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE autodream_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE state_machine_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE consolidated_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_transcripts ENABLE ROW LEVEL SECURITY;

-- Default policies to avoid default-deny locking out normal traffic
CREATE POLICY tenant_isolation_policy ON agent_session_data USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON swarm_truth_embeddings USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON shared_tasks_v4 USING (organization_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON shared_tasks USING (organization_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON agent_approvals USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON swarm_tasks USING (organization_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON onboarding_state USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON referrals USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON competitor_metrics USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON agent_violations USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON hybrid_fs_sync_queue USING (organization_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON shared_tasks_decomposition USING (organization_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON department_tasks USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON autodream_memories USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON state_machine_transitions USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON pages USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON memories USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON consolidated_memory USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON agent_inbox USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON meeting_rooms USING (tenant_id = current_setting('app.current_tenant_id', true));
CREATE POLICY tenant_isolation_policy ON meeting_transcripts USING (tenant_id = current_setting('app.current_tenant_id', true));
