ALTER TABLE epics ADD COLUMN IF NOT EXISTS parent_plan_id TEXT;
ALTER TABLE epics ADD COLUMN IF NOT EXISTS dependencies JSONB DEFAULT '[]';

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS parent_plan_id TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS dependencies JSONB DEFAULT '[]';
