-- +goose Up
-- Migration 052: Add missing RLS to tables

ALTER TABLE IF EXISTS telemetry_buffer ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS business_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS epics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_dependencies ENABLE ROW LEVEL SECURITY;

-- +goose Down
-- Reverse Migration 052

ALTER TABLE IF EXISTS task_dependencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS epics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS business_milestones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS telemetry_buffer DISABLE ROW LEVEL SECURITY;
