ALTER TABLE tasks ADD COLUMN IF NOT EXISTS epic_id TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS payload TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
