-- Final RLS Audit
ALTER TABLE IF EXISTS crdt_deltas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS local_mcp_rag_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS department_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_violations ENABLE ROW LEVEL SECURITY;
