-- 079_enable_row_level_security.sql

ALTER TABLE IF EXISTS shared_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shared_tasks_decomposition ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consolidated_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shared_tasks_v4 ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_memory_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS hybrid_fs_sync_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS autodream_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scheduled_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS department_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS crdt_deltas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS local_mcp_rag_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meeting_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meeting_transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS revoked_tokens ENABLE ROW LEVEL SECURITY;
