-- +goose Up
-- Migration 032: Add missing ENABLE ROW LEVEL SECURITY to tables with tenant_id

ALTER TABLE order_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE po_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE depletion_logs ENABLE ROW LEVEL SECURITY;

-- +goose Down
ALTER TABLE order_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE agent_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_timeline DISABLE ROW LEVEL SECURITY;
ALTER TABLE business_milestones DISABLE ROW LEVEL SECURITY;
ALTER TABLE raw_materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE bom_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE po_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE depletion_logs DISABLE ROW LEVEL SECURITY;
