-- +goose Up
-- Enable missing RLS on specific tables

ALTER TABLE IF EXISTS depletion_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS po_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS raw_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customer_timeline ENABLE ROW LEVEL SECURITY;

-- +goose Down
ALTER TABLE IF EXISTS depletion_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS po_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bom_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS raw_materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customer_timeline DISABLE ROW LEVEL SECURITY;
