ALTER TABLE IF EXISTS embedding_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS epics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS telemetry_buffer ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shared_task_dependencies ENABLE ROW LEVEL SECURITY;
