-- +goose Up
-- Migration 215: Add missing tenant_id indexes for performance
-- +goose NO TRANSACTION
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_actions_tenant_id ON agent_actions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_approvals_tenant_id ON agent_approvals(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_departments_tenant_id ON agent_departments(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_draft_tenant_id ON agent_draft(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_inbox_tenant_id ON agent_inbox(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_jobs_tenant_id ON agent_jobs(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_kv_store_tenant_id ON agent_kv_store(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_memories_tenant_id ON agent_memories(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_missions_tenant_id ON agent_missions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_status_tenant_id ON agent_status(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_violations_tenant_id ON agent_violations(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agents_tenant_id ON agents(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ai_memories_tenant_id ON ai_memories(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_artifacts_tenant_id ON assistant_artifacts(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_connectors_tenant_id ON assistant_connectors(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_file_changes_tenant_id ON assistant_file_changes(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_memory_records_tenant_id ON assistant_memory_records(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_messages_tenant_id ON assistant_messages(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_skills_tenant_id ON assistant_skills(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_tasks_tenant_id ON assistant_tasks(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_assistant_workspaces_tenant_id ON assistant_workspaces(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_auto_reply_policies_tenant_id ON auto_reply_policies(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_autodream_memories_tenant_id ON autodream_memories(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_availability_schedules_tenant_id ON availability_schedules(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bom_items_tenant_id ON bom_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_builder_blocks_tenant_id ON builder_blocks(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_builder_brand_toolboxes_tenant_id ON builder_brand_toolboxes(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_builder_pages_tenant_id ON builder_pages(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_builder_sites_tenant_id ON builder_sites(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_businesses_tenant_id ON businesses(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_calendar_integrations_tenant_id ON calendar_integrations(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_campaign_assets_tenant_id ON campaign_assets(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_campaigns_tenant_id ON campaigns(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cart_items_tenant_id ON cart_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_carts_tenant_id ON carts(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_channel_executions_tenant_id ON channel_executions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_checkout_sessions_tenant_id ON checkout_sessions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_competitor_metrics_tenant_id ON competitor_metrics(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_conflict_queue_tenant_id ON conflict_queue(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_context_snippets_tenant_id ON context_snippets(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_conversational_checkout_sessions_tenant_id ON conversational_checkout_sessions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_crdt_deltas_tenant_id ON crdt_deltas(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_customer_identities_tenant_id ON customer_identities(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_customer_profile_tenant_id ON customer_profile(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_customers_tenant_id ON customers(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_department_dead_letters_tenant_id ON department_dead_letters(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_department_tasks_tenant_id ON department_tasks(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_depletion_logs_tenant_id ON depletion_logs(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_entity_versions_tenant_id ON entity_versions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hybrid_fs_sync_queue_tenant_id ON hybrid_fs_sync_queue(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_inbound_signals_tenant_id ON inbound_signals(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_integration_credentials_tenant_id ON integration_credentials(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_interaction_event_jobs_tenant_id ON interaction_event_jobs(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_interaction_events_tenant_id ON interaction_events(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_interactions_tenant_id ON interactions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_interactive_proposal_line_items_tenant_id ON interactive_proposal_line_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_interactive_proposals_tenant_id ON interactive_proposals(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_knowledge_embeddings_tenant_id ON knowledge_embeddings(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_lead_gen_campaigns_tenant_id ON lead_gen_campaigns(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loyalty_ledgers_tenant_id ON loyalty_ledgers(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_meeting_rooms_tenant_id ON meeting_rooms(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_meeting_transcripts_tenant_id ON meeting_transcripts(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_memories_tenant_id ON memories(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mutation_queue_tenant_id ON mutation_queue(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ohc_fx_rates_tenant_id ON ohc_fx_rates(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ohc_shared_offer_tenant_id ON ohc_shared_offer(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ohc_staff_member_tenant_id ON ohc_staff_member(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ohc_timecard_event_tenant_id ON ohc_timecard_event(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_omni_inbox_messages_tenant_id ON omni_inbox_messages(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_onboarding_state_tenant_id ON onboarding_state(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_operation_intents_tenant_id ON operation_intents(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_order_items_tenant_id ON order_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_order_line_items_tenant_id ON order_line_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pages_tenant_id ON pages(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_po_line_items_tenant_id ON po_line_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pos_offline_transactions_tenant_id ON pos_offline_transactions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pos_terminal_sessions_tenant_id ON pos_terminal_sessions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pre_order_entries_tenant_id ON pre_order_entries(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pricing_heuristics_tenant_id ON pricing_heuristics(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_product_variants_tenant_id ON product_variants(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_products_tenant_id ON products(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_promotion_codes_tenant_id ON promotion_codes(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_proposal_line_items_tenant_id ON proposal_line_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_proposals_tenant_id ON proposals(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_proposed_bookings_tenant_id ON proposed_bookings(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_quote_line_items_tenant_id ON quote_line_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_quote_requests_tenant_id ON quote_requests(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_quotes_tenant_id ON quotes(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_raw_materials_tenant_id ON raw_materials(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_recovery_attempts_tenant_id ON recovery_attempts(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_recovery_campaigns_tenant_id ON recovery_campaigns(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_revoked_tokens_tenant_id ON revoked_tokens(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_reward_claims_tenant_id ON reward_claims(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_roles_tenant_id ON roles(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_route_stops_tenant_id ON route_stops(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_service_items_tenant_id ON service_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_service_requests_tenant_id ON service_requests(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_shared_tasks_tenant_id ON shared_tasks(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_shared_tasks_v4_tenant_id ON shared_tasks_v4(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_social_post_proposals_tenant_id ON social_post_proposals(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_state_machine_transitions_tenant_id ON state_machine_transitions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sub_agent_queue_tenant_id ON sub_agent_queue(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sync_conflict_queue_tenant_id ON sync_conflict_queue(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sync_events_tenant_id ON sync_events(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_task_envelopes_tenant_id ON task_envelopes(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_team_invites_tenant_id ON team_invites(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tenant_ai_budgets_tenant_id ON tenant_ai_budgets(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tenant_feed_items_tenant_id ON tenant_feed_items(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_test_sync_entities_tenant_id ON test_sync_entities(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tool_integrations_tenant_id ON tool_integrations(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_triage_proposed_actions_tenant_id ON triage_proposed_actions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_unified_messages_tenant_id ON unified_messages(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_unified_threads_tenant_id ON unified_threads(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_unified_triage_actions_tenant_id ON unified_triage_actions(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_tenant_id ON users(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_waitlist_campaigns_tenant_id ON waitlist_campaigns(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_work_intents_tenant_id ON work_intents(tenant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_work_tasks_tenant_id ON work_tasks(tenant_id);

-- +goose Down
DROP INDEX IF EXISTS idx_agent_actions_tenant_id;
DROP INDEX IF EXISTS idx_agent_approvals_tenant_id;
DROP INDEX IF EXISTS idx_agent_departments_tenant_id;
DROP INDEX IF EXISTS idx_agent_draft_tenant_id;
DROP INDEX IF EXISTS idx_agent_inbox_tenant_id;
DROP INDEX IF EXISTS idx_agent_jobs_tenant_id;
DROP INDEX IF EXISTS idx_agent_kv_store_tenant_id;
DROP INDEX IF EXISTS idx_agent_memories_tenant_id;
DROP INDEX IF EXISTS idx_agent_missions_tenant_id;
DROP INDEX IF EXISTS idx_agent_status_tenant_id;
DROP INDEX IF EXISTS idx_agent_violations_tenant_id;
DROP INDEX IF EXISTS idx_agents_tenant_id;
DROP INDEX IF EXISTS idx_ai_memories_tenant_id;
DROP INDEX IF EXISTS idx_assistant_artifacts_tenant_id;
DROP INDEX IF EXISTS idx_assistant_connectors_tenant_id;
DROP INDEX IF EXISTS idx_assistant_file_changes_tenant_id;
DROP INDEX IF EXISTS idx_assistant_memory_records_tenant_id;
DROP INDEX IF EXISTS idx_assistant_messages_tenant_id;
DROP INDEX IF EXISTS idx_assistant_skills_tenant_id;
DROP INDEX IF EXISTS idx_assistant_tasks_tenant_id;
DROP INDEX IF EXISTS idx_assistant_workspaces_tenant_id;
DROP INDEX IF EXISTS idx_auto_reply_policies_tenant_id;
DROP INDEX IF EXISTS idx_autodream_memories_tenant_id;
DROP INDEX IF EXISTS idx_availability_schedules_tenant_id;
DROP INDEX IF EXISTS idx_bom_items_tenant_id;
DROP INDEX IF EXISTS idx_builder_blocks_tenant_id;
DROP INDEX IF EXISTS idx_builder_brand_toolboxes_tenant_id;
DROP INDEX IF EXISTS idx_builder_pages_tenant_id;
DROP INDEX IF EXISTS idx_builder_sites_tenant_id;
DROP INDEX IF EXISTS idx_businesses_tenant_id;
DROP INDEX IF EXISTS idx_calendar_integrations_tenant_id;
DROP INDEX IF EXISTS idx_campaign_assets_tenant_id;
DROP INDEX IF EXISTS idx_campaigns_tenant_id;
DROP INDEX IF EXISTS idx_cart_items_tenant_id;
DROP INDEX IF EXISTS idx_carts_tenant_id;
DROP INDEX IF EXISTS idx_channel_executions_tenant_id;
DROP INDEX IF EXISTS idx_checkout_sessions_tenant_id;
DROP INDEX IF EXISTS idx_competitor_metrics_tenant_id;
DROP INDEX IF EXISTS idx_conflict_queue_tenant_id;
DROP INDEX IF EXISTS idx_context_snippets_tenant_id;
DROP INDEX IF EXISTS idx_conversational_checkout_sessions_tenant_id;
DROP INDEX IF EXISTS idx_crdt_deltas_tenant_id;
DROP INDEX IF EXISTS idx_customer_identities_tenant_id;
DROP INDEX IF EXISTS idx_customer_profile_tenant_id;
DROP INDEX IF EXISTS idx_customers_tenant_id;
DROP INDEX IF EXISTS idx_department_dead_letters_tenant_id;
DROP INDEX IF EXISTS idx_department_tasks_tenant_id;
DROP INDEX IF EXISTS idx_depletion_logs_tenant_id;
DROP INDEX IF EXISTS idx_entity_versions_tenant_id;
DROP INDEX IF EXISTS idx_hybrid_fs_sync_queue_tenant_id;
DROP INDEX IF EXISTS idx_inbound_signals_tenant_id;
DROP INDEX IF EXISTS idx_integration_credentials_tenant_id;
DROP INDEX IF EXISTS idx_interaction_event_jobs_tenant_id;
DROP INDEX IF EXISTS idx_interaction_events_tenant_id;
DROP INDEX IF EXISTS idx_interactions_tenant_id;
DROP INDEX IF EXISTS idx_interactive_proposal_line_items_tenant_id;
DROP INDEX IF EXISTS idx_interactive_proposals_tenant_id;
DROP INDEX IF EXISTS idx_knowledge_embeddings_tenant_id;
DROP INDEX IF EXISTS idx_lead_gen_campaigns_tenant_id;
DROP INDEX IF EXISTS idx_loyalty_ledgers_tenant_id;
DROP INDEX IF EXISTS idx_meeting_rooms_tenant_id;
DROP INDEX IF EXISTS idx_meeting_transcripts_tenant_id;
DROP INDEX IF EXISTS idx_memories_tenant_id;
DROP INDEX IF EXISTS idx_mutation_queue_tenant_id;
DROP INDEX IF EXISTS idx_ohc_fx_rates_tenant_id;
DROP INDEX IF EXISTS idx_ohc_shared_offer_tenant_id;
DROP INDEX IF EXISTS idx_ohc_staff_member_tenant_id;
DROP INDEX IF EXISTS idx_ohc_timecard_event_tenant_id;
DROP INDEX IF EXISTS idx_omni_inbox_messages_tenant_id;
DROP INDEX IF EXISTS idx_onboarding_state_tenant_id;
DROP INDEX IF EXISTS idx_operation_intents_tenant_id;
DROP INDEX IF EXISTS idx_order_items_tenant_id;
DROP INDEX IF EXISTS idx_order_line_items_tenant_id;
DROP INDEX IF EXISTS idx_pages_tenant_id;
DROP INDEX IF EXISTS idx_po_line_items_tenant_id;
DROP INDEX IF EXISTS idx_pos_offline_transactions_tenant_id;
DROP INDEX IF EXISTS idx_pos_terminal_sessions_tenant_id;
DROP INDEX IF EXISTS idx_pre_order_entries_tenant_id;
DROP INDEX IF EXISTS idx_pricing_heuristics_tenant_id;
DROP INDEX IF EXISTS idx_product_variants_tenant_id;
DROP INDEX IF EXISTS idx_products_tenant_id;
DROP INDEX IF EXISTS idx_promotion_codes_tenant_id;
DROP INDEX IF EXISTS idx_proposal_line_items_tenant_id;
DROP INDEX IF EXISTS idx_proposals_tenant_id;
DROP INDEX IF EXISTS idx_proposed_bookings_tenant_id;
DROP INDEX IF EXISTS idx_quote_line_items_tenant_id;
DROP INDEX IF EXISTS idx_quote_requests_tenant_id;
DROP INDEX IF EXISTS idx_quotes_tenant_id;
DROP INDEX IF EXISTS idx_raw_materials_tenant_id;
DROP INDEX IF EXISTS idx_recovery_attempts_tenant_id;
DROP INDEX IF EXISTS idx_recovery_campaigns_tenant_id;
DROP INDEX IF EXISTS idx_revoked_tokens_tenant_id;
DROP INDEX IF EXISTS idx_reward_claims_tenant_id;
DROP INDEX IF EXISTS idx_roles_tenant_id;
DROP INDEX IF EXISTS idx_route_stops_tenant_id;
DROP INDEX IF EXISTS idx_service_items_tenant_id;
DROP INDEX IF EXISTS idx_service_requests_tenant_id;
DROP INDEX IF EXISTS idx_shared_tasks_tenant_id;
DROP INDEX IF EXISTS idx_shared_tasks_v4_tenant_id;
DROP INDEX IF EXISTS idx_social_post_proposals_tenant_id;
DROP INDEX IF EXISTS idx_state_machine_transitions_tenant_id;
DROP INDEX IF EXISTS idx_sub_agent_queue_tenant_id;
DROP INDEX IF EXISTS idx_sync_conflict_queue_tenant_id;
DROP INDEX IF EXISTS idx_sync_events_tenant_id;
DROP INDEX IF EXISTS idx_task_envelopes_tenant_id;
DROP INDEX IF EXISTS idx_team_invites_tenant_id;
DROP INDEX IF EXISTS idx_tenant_ai_budgets_tenant_id;
DROP INDEX IF EXISTS idx_tenant_feed_items_tenant_id;
DROP INDEX IF EXISTS idx_test_sync_entities_tenant_id;
DROP INDEX IF EXISTS idx_tool_integrations_tenant_id;
DROP INDEX IF EXISTS idx_triage_proposed_actions_tenant_id;
DROP INDEX IF EXISTS idx_unified_messages_tenant_id;
DROP INDEX IF EXISTS idx_unified_threads_tenant_id;
DROP INDEX IF EXISTS idx_unified_triage_actions_tenant_id;
DROP INDEX IF EXISTS idx_users_tenant_id;
DROP INDEX IF EXISTS idx_waitlist_campaigns_tenant_id;
DROP INDEX IF EXISTS idx_work_intents_tenant_id;
DROP INDEX IF EXISTS idx_work_tasks_tenant_id;
