-- Migration 217: Ensure user authentication columns and TEXT id format exist regardless of table creation order
ALTER TABLE IF EXISTS user_sessions DROP CONSTRAINT IF EXISTS fk_rails_9fa262d742;
ALTER TABLE IF EXISTS users ALTER COLUMN id TYPE TEXT USING id::text;

ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS username TEXT UNIQUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS tenant_id TEXT DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS oidc_subject TEXT UNIQUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS roles TEXT[] DEFAULT '{}';
