[package]
name = "server_integrations_wallet_pass"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = "0.1"
passes = "1.0.1"
uuid = { version = "1", features = ["v4"] }
