load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "utils",
    srcs = ["json_minify.go", "gzip_middleware.go", "fs.go"],
    importpath = "github.com/onehumancorp/mono/srcs/server/utils",
    visibility = ["//visibility:public"],
)

go_test(
    name = "utils_test",
    srcs = ["json_minify_test.go", "gzip_middleware_test.go"],
    embed = [":utils"],
)
