load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "utils",
    srcs = [
        "fs.go",
        "gzip_middleware.go",
        "json_minify.go",
    ],
    importpath = "github.com/onehumancorp/mono/srcs/server/utils",
    visibility = ["//visibility:public"],
)

go_test(
    name = "utils_test",
    srcs = [
        "gzip_middleware_test.go",
        "json_minify_test.go",
    ],
    embed = [":utils"],
)
