load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = [
        "broker.go",
        "http_handler.go",
        "local_broker.go",
        "local_mesh.go",
        "mesh.go",
        "redis_broker.go",
        "redis_mesh.go",
        "server.go",
        "mesh_coordinator.go",
    ],
    importpath = "github.com/onehumancorp/mono/src/server/orchestration/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/db",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_redis_rueidis//:rueidis",
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_websocket//:websocket",

        "//src/proto:mesh_go_proto",
        "@org_golang_google_protobuf//proto",
],
)

go_test(
    name = "mesh_test",
    srcs = [
        "broker_test.go",
        "mesh_test.go",
        "mesh_coordinator_test.go",
        "http_handler_test.go",
    ],
    embed = [":mesh"],
    deps = [
        "//src/server/db",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_alicebob_miniredis_v2//:miniredis",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_modernc_sqlite//:sqlite",
        "@com_github_gorilla_websocket//:websocket",

        "//src/proto:mesh_go_proto",
        "@org_golang_google_protobuf//proto",
],
)
