load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mesh",
    srcs = ["hub.go", "server.go"],
    importpath = "github.com/onehumancorp/mono/src/server/orchestration/mesh",
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:hub_go_proto",
        "@com_github_redis_rueidis//:rueidis",
        "//src/server/orchestration/telemetry:telemetry",
    ],
)

go_test(
    name = "mesh_test",
    srcs = ["hub_test.go"],
    embed = [":mesh"],
    deps = ["//src/proto:hub_go_proto"],
)

load("@rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "mesh_server",
    srcs = ["main.go"],
    deps = [
        ":mesh",
        "//src/proto:hub_go_proto",
        "@org_golang_google_grpc//:grpc",
    ],
    visibility = ["//visibility:public"],
)
