load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "chat_engine",
    srcs = glob(["*.rs", "**/*.rs"]),
    crate_root = "mod.rs",
    visibility = ["//visibility:public"],
    deps = [
        "//src/server/integrations/core:server_integrations_core",
        "@crates//:axum",
        "@crates//:reqwest",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:uuid",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)

rust_test(
    name = "chat_engine_test",
    crate = ":chat_engine",
    deps = [
        "@crates//:tokio",
    ],
)
